### ISSUE TITLE
Optimize optimized paragraph layout

### ISSUE THREAD

**Issue by rpitasky** [typst/typst#1030]
Notwithstanding some confusion about what “runtime complexity” is, this should definitely be looked at.

### Discussed in https://github.com/typst/typst/discussions/489

<div type='discussions-op-text'>

<sup>Originally posted by **TS40** March 31, 2023</sup>
I looked a bit how Typst scales when more than a few pages are created.
While it is much faster than PdfTeX for a few pages, it will be ca. 2 times slower with many pages.
So, I was interested what complexity it has.

Here are my first ideas using `#lorem` and `#set par(justify: true)`.
I edited the source code to print the calls to `line` function and at the end iterated over the lines result and printed the widths to verify I got it correct.

```
lorem5000(default width):     200882 calls to line;    345 final lines; runtime=582*N
lorem50000(default width):   1992536 calls to line;   3442 final lines; runtime=579*N
lorem500000(default width): 20018244 calls to line;  34323 final lines; runtime=583*N
```

With the default settings and additionally `#set par(justify: true)` the complexity will be <= 580*N where N is the number of text lines in the document (because the document is not only text lines and other things are probably cheaper).

I have not yet understood the algorithm good enough. But I think it is possible to make the constant 580 quite a bit smaller by either some kind of binary searching or by filtering impossible candidates without shaping them (but maybe this is already done, not sure).

Note that the smaller the text width and the less text lines, the faster it will be:

```
lorem500(width: 5cm):           5443  calls to line;    157 final lines; runtime=35*N
lorem5000(width: 5cm):         51576  calls to line;   1570 final lines; runtime=33*N
lorem50000(width: 5cm):       511380  calls to line;  15686 final lines; runtime=33*N
```

Update:
[Here](https://github.com/jaroslov/knuth-plass-thoughts/blob/master/plass.md#further-optimizations--features) it says, the runtime of the algorithm is approximately `max_number_of_words_in_a_line * number_of_linebreaks` in an optimized variant of the algorithm. In the created pdf with default width, we have approximately 20 words per line, so this is quite a bit different from 580. But maybe I mixed up some parameters like "lines" and "line breaks".</div>

**Comment by peng1999** [comment]
The current algorithm implemented in typst call `line` function $c=\alpha mn$ times, where $m$ is words per line, $n$ is the number of total words in text, and $\alpha$ is some constant. Actually we can calculate $\alpha$ from your data:

| $n$ | $c$ | $l=$ line count | $m=n/l$| $\alpha m=c/n$ | $\alpha=c/(mn)$|
|--------|--------|--------|--|--|--|
| 5000   | 200882   | 345   | 14.49 | 40.18 | 2.8 |
| 50000  | 1992536  | 3442  | 14.53 | 39.85 | 2.7 |
| 500000 | 20018244 | 34323 | 14.57 | 40.04 | 2.7 |
| 500    | 5443     | 157   | 3.18  | 10.89 | 3.4 |
| 5000   | 51576    | 1570  | 3.18  | 10.32 | 3.2 |
| 50000  | 511380   | 15686 | 3.19  | 10.23 | 3.2 |

So $\alpha$ is roughly a constant of 3, it's related to hyphenation, so bigger for shorter lines (i.e. smaller $m$) because more hyphenation is needed.

So assuming `line` has $O(1)$ complexity, we can conclude that the total running time of current line breaking algorithm is linear to text length, and linear to line width.

More efficient algorithm is possible. Like what described in [this paper](https://core.ac.uk/download/pdf/161439515.pdf). But that is not a priority. Maybe we should wait for a volunteer to implement it.

**Comment by laurmaedje** [comment]
Note that not every call to `line` actually shapes the whole line. It mostly just reuses results from an initial shaping pass. Sometimes it needs to reshape parts of the line because shaping can depend on the exact break, but this is more a consideration for more complex scripts like Arabic or Devanagari.

**Comment by peng1999** [comment]
> But as I said before, this is not a problem with Typst, but with the used algorithm in general. It is not designed to be very fast.

It is possible to optimize the current $O(mn)$ algorithm to $O(n)$, using the technic in paper I mentioned above. But I doubt @laurmaedje , or any other contributor have interest implementing it.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/4483
