### ISSUE TITLE
Set/show rules for math symbols

### ISSUE THREAD

**Issue by sitandr** [typst/typst#1051]
### Description

Hello, I'm totally new to `typst` and I really appreciate the way math is handled. However, I skimmed through the docs and issues and didn't find any way of manipulation of math symbols like the general `typst` idea of handling the styles. So, when I want to write very basic expression like integral from `a` to `b` with limits, I need to write

```typst
$ limits(integral)_a^b f(x) dx $
```

It is not that bad, but in general I want to use "limits" on *all integrals* I encounter, so that seems a bit of excess. However, if I try to use that approach "just use show/set rules" and try to write a rule that edits `math.integral`, it gives a message "*expected function, label, string, regular expression, or selector, found symbol*".

Of course, it is possible to use variables to create new integral with limits:

```
#let integral =  math.limits(math.integral)
$ integral_0^oo f(x) dx $
```

It is even possible to set it from templates if using `import *` (but not from constructor functions). But is seems to me than changing a way limits are placed or symbol is written (in fact replacing it with some other combination of commands and symbols) is the "style thing", so it seems more consistent to change them through styles rules.

### Use Case

What is more, using styles instead of reassinging commands will allow changing rendering for some *categories of symbols* or symbols that meet certain conditions. In case of integrals, that would be adding limits for *all types* of integrals, not just one symbol. If rules for symbols work, that requires just adding *selectors for symbol groups*.

I suppose that this is a useful thing for maths that is just not implemented yet. I believe that developing rules for proper math editing will lead to much easier math typing. Of course, over- and misuse of such rules could make math less intuitive. E.g., users can reassign symbols with long names to shorter ones. Nevertheless, this is the problem that `typst` encounters in general, and it seems that it doesn't cause much fuss.

Again, I'm totally new to `typst`, so I could get it all wrong. In that case, I would be grateful to someone who can tell me how to properly deal with this problem.

**Comment by user202729** [comment]
Seems related to #305 and #262.

That having said, your choice of putting the limits above/below the integral is definitely a bit weird. (as in generally speaking the built-in behavior of Typst _should_ be the typographically best and users should not deviate from that)

In this specific case though, I don't see much functional difference between show rule and redefining the symbol.

**Comment by sitandr** [comment]
Well, in fact there are numerous math things that relate to symbols style. For example, in math community of my country `sinh` is usually written as `sh`, trigonometric functions like `сsc` (cosecant) are never used (`1/sin` is written instead) and so on. Placing limits that way is also that kind of thing. Sadly, sometimes it is impossible to make the things the best way for everybody. It is possible to add special symbols for such localizations, but it would become harder to share source between different communities. Changing some settings in the header is easier than replacing things in all the document.

Of course, its could be managed through several "localization" packages with "import *", but I don't think it is a good way. It would be great if I could call some functions from one package to set up my "localization", but as there are no global variables allowed, that would require some state management (and that seems too complicated).

Again, I think that rules could be used for some more complicated things, like reducing spacing if symbol stays in fraction (that will need some new math selectors to be added). I can't think of all the potential uses right now, but I think that that could  reduce boilerplate for non-trivial customization.

Probably, it is better to listen to someone more experienced in typing math as I haven't written large math doc in typst yet.

**Comment by donRumata03** [comment]
More thoughts in support of this feature:

- Conceptually, it's like _dependency injection_ in programming: the math formulas become generic over styling and the entities predefined by typst specification (e.g. `integral` in this case) implicitly become interfaces whereas the filters become their implementations. So, we can have a single way to represent, what is written, but different ways to show it.
- This opens up a wide scope for imagination:
  - One can write an article once and then adopt it for different localizations just by changing filters
  - Imagine a person has realized that all the previously written code needs a slight but a systematic styling shift and from now on he or she would use other visual primitives to represent math entities. In that case, post-processing is the right choice because it would need less effort (that changing all formulas) and would maintain consistency within the document.
- Сoncerning сonsistency, math-mode filters would be consistent with ones in non-math mode (their presence is generally what people expect) so it follows the major design goal of typst: **Simplicity through Consistency**

(Still, this arguments only show that such feature would be useful. However it's not obvious how important it is…)

**Comment by laurmaedje** [comment]
In principle, I agree that styling is the right way to configure this as opposed to redefining the symbol. I'd have to think a bit more about the implementation implications though.
