### ISSUE TITLE
Double line spacing

### ISSUE THREAD

**Issue by lespea** [typst/typst#106]
Say I need double spaced paragraphs... I don't see a way to do that.  Am I just missing something?

**Comment by johanvx** [comment]
While it's true that line spacing can be changed by setting [`leading`](https://typst.app/docs/reference/layout/par/#parameters--leading) with a certain [`length`](https://typst.app/docs/reference/types/length), I think that it would be great to have something as handy as `\onehalfspacing` and `\doublespacing` (provided by [setspace](https://ctan.org/pkg/setspace)) in LaTeX (maybe something like `#set par(leading: "double")`).

Personally, I suggest to add some examples showing how to obtain single/one-half/double spaced paragraphs with `#set par(leading: ??em)` if this is possible and accurate.

**Comment by reknih** [comment]
So the default leading is `0.65em` so you can go from there with `#set par(leading: ??em)`.

**Comment by Mr-Blue-Sky-Candy** [comment]
@reknih I tried using the same method. However, I got these abominable headings since `#set par` only for the paragraphs:
![resim](https://github.com/typst/typst/assets/131680576/303216ff-d767-4ab8-8729-e0d28bc5c229)
How can I set double line spacing for the whole document?

**Comment by laurmaedje** [comment]
You can adjust spacing around headings with `#show heading: set block(above: ??em, below: ??em)`.

**Comment by laurmaedje** [comment]
I'm not sure how exactly Word defines double-spacing, but the most reasonable definition would in my opinion be that the distance between two baselines is 2em.

Typst's line spacing model works differently. The `par.leading` value doesn't define the distance between baselines, but rather the distance between the `bottom-edge` of the upper line and the `top-edge` of the lower line. By default, the values for these two properties are up to the font (baseline & cap-height), so baseline-baseline distance of exactly 2em would need to be judged visually. However, you can also override the edges to fixed values. One possible way to to achieve exactly 2em baseline gap is

```typ
#set text(top-edge: 0.7em, bottom-edge: -0.3em)
#set par(leading: 1em)
``` 
How you distribute the `1em` between top & bottom-edge here affects how close the first line will be to the top of the page / top of its container and the last line to the bottom. You can visualize that by putting the text in a `rect`.

**Comment by ARakhamimov** [comment]
Hello! 

I'm adding onto this closed discussion because unfortunately the solution posted by @laurmaedje also changed the spacing in my header and off centered text in packages like gentleclues. My university requires double spacing for master's theses (booooooo), so this may be a useful alternative for anyone else looking to only double space the text in paragraphs and headings (like you might expect from "double spacing" in other apps).

```typst
set par(
    leading: 1.3em,
    spacing: 1.95em
  )
show heading: set block(
    below: 1em, 
    above: 2em)
```

The reason behind using both "leading" and "spacing" is that new paragraphs would otherwise appear at the same distance as new lines in the same paragraph, so it would be hard to distinguish without starting new paragraphs with tabs.

These numbers are estimates based on the 0.65em default + what looked nice to my eye, so you can and should play around with your own document. If you have the time, compare to something like word/google docs for a more precise "double spacing."
