### ISSUE TITLE
#block ignore figure's cetertal align

### ISSUE THREAD

**Issue by retsyo** [typst/typst#1061]
### Description

I think "pic 5" should continue the center-align, but it does not. So I think it is a bug with #block
 
<pre>
#set heading(numbering: "1.1")

#show figure: it => align(center)[
  #it.body
  #it.supplement #counter(heading).display()-#counter(figure).display(it.numbering) #it.caption
]

#show heading: it => [
 #counter(figure).update(0)
 #it
]

= Chapter One

in @fig1

#figure(
  image("img/1.png", width: 30%),
  caption: [A curious figure.]
) <fig1>

== subheading of chap 1

in @fig2

#figure(
  image("img/2.png", width: 30%),
  caption: [A curious figure.]
) <fig2>

in @fig3

#figure(
  image("img/3.png", width: 30%),
  caption: [A curious figure.]
) <fig3>

= Chapter Two

#figure(
  image("img/4.png", width: 30%),
  caption: [A curious figure.]
) <fig4>

#block(breakable: false)[
    #figure(
      image("img/5.png", width: 30%),
      caption: [A curious figure.]
    ) <fig5>
]

#figure(
  image("img/6.png", width: 30%),
  caption: [A curious figure.]
) <fig6>

= Chapter Three

#figure(
  image("img/7.png", width: 30%),
  caption: [A curious figure.]
) <fig7>
</pre>

and if needed, the `1.png` ~ `7.png` is zipped:  
[img.zip](https://github.com/typst/typst/files/11366072/img.zip)

![bug](https://user-images.githubusercontent.com/7960913/235473318-6481525f-d976-45b9-88cd-e2323884d478.png)

### Operating system

Windows

### Typst version

- [ ] I am using the latest version of Typst

**Comment by PgBiel** [comment]
When you `#block` it, you are changing the context the figure is placed in to the block's context (instead of the whole page). As such, the figure will think that the block (which has precisely the width and height of its contents, by default) is the whole page, and centering won't do anything. Instead, you need to specify `#block(width: 100%)` to make the block span the whole page, and then the figure will center relative to the whole block which will have the whole page's width.
