### ISSUE TITLE
Math limit formatting overlap

### ISSUE THREAD

**Issue by cmoog** [typst/typst#112]
## Code

```
sup_(x in P_i)
```

## LaTeX
<img width="250" alt="Screenshot 2023-03-22 at 7 52 03 AM" src="https://user-images.githubusercontent.com/7585078/226910133-ec8302f8-46a9-486d-b6d4-4858b1574229.png">

## Typst

<img width="380" alt="Screenshot 2023-03-21 at 11 00 37 PM" src="https://user-images.githubusercontent.com/7585078/226798938-e77977df-8c2f-4167-93a4-b90b78f74293.png">

**Comment by rpitasky** [comment]
I did some tracing of this bug and made some headway towards a potential fix; while I can’t fix it right now because of time constraints, I can dump my knowledge to reduce repeated effort.

Some additional code needs to be added to handle this case in [this function](https://github.com/typst/typst/blob/2fbb14f712708188649181525813b3ac5a02e0fb/library/src/math/attach.rs#L214). LaTeX skirts around this issue by having \sup be its own object and special-casing it out. I think that for Typst, the more elegant way to solve this problem is by first checking if the limits attachment are being added to text, then measuring how far the text dips below the baseline, and ensuring a specific amount of clearance is maintained. Because math layout is done after text shaping, this isn’t too hard to do, but it’ll be a bit of spaghetti code because the information about the font measurements is nested like five levels deep into the relevant objects.

**Comment by laurmaedje** [comment]
Maybe the text's top-edge and bottom-edge should be tight bounding boxes in math.

**Comment by cmoog** [comment]
Another issue shown in this example is that alignment / mis-alignment of the baseline of `P` with `in`.
