### ISSUE TITLE
Space between text and symbols in math mode

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1199]
### Description

```
$
psi in "abc" \
sum_(psi in "abc") \
sum_(psi in a)
$
```

![image](https://github.com/typst/typst/assets/9490724/68bf29f1-3367-4573-8690-845c82ccfe4b)

I'm not sure what the expected behavior is here, but there should either be a space both before and after `in` or none at all.

**Comment by SUPERCILEX** [comment]
Just checked and latex puts no spaces when inside an attach. So the 3rd equation is correct and the 2nd one needs to be fixed to match.

**Comment by EpicEricEE** [comment]
>  Though I do not understand why the behavior is different outside of a limit.

The spacing around the "in" symbol (which I think is a relation) is automatically added _only_ if it's not in script style: https://github.com/typst/typst/blob/1fa56a317c8d8da76546e6b5e19b279d84380837/library/src/math/spacing.rs#L40-L44

So, if you have `sum_(psi in "abc")`, the space before `"abc"` is still added because of what Laurenz mentioned, but the other space before the "in" symbol is not, because the limits are in script style.

While it may be unintuitive, at least there is some logic behind it 😄

**Comment by laurmaedje** [comment]
This will be fixed by having a clearer distinction between text and multi-letter variables in math. The remaining spacing behaviour (limits vs top-level) is the same in LaTeX.

**Comment by Atreyu-94** [comment]
Just for context, this topic is related to #1125

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/274
