### ISSUE TITLE
error: cannot compare length and length

### ISSUE THREAD

**Issue by sroracle** [typst/typst#1231]
### Description

typst version 0.3.0 (b1e0de00) does not seem to be able to compare `em` to any of the other length units (`pt`, `mm`, `cm`, `in`). Errors are generated with `calc.max`, `calc.min`, `<`, `>`, `<=`, `>=`:

```
error: cannot compare length and length
  ┌─ tbl-test.typ:4:15
  │
4 │ #calc.max(1em, 1pt)
  │                ^^^
```

Interestingly, no error is generated for `==` and `!=`, but the comparison always seems to be unequal:

```
#set text(size: 12pt)
#(1em == 12pt)
// false
```

**Edit:** this seems to affect arithmetic operations as well:

```
error: cannot multiply length with length
  ┌─ tbl-test.typ:5:6
  │
5 │ #repr(1em * 1pt)
  │       ^^^^^^^^^

```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is because the size of `1em` always depends on the current font size (which can be changed at any point of the document), so it is always unknown, except at content display time. Converting to `pt` for comparison is necessary, but you will need to wrap your functions in a `style(styles => ...)` element (which always returns content, which detects the current styles - including font size - on display time and runs your callback with that info, contained in this strange and opaque `styles` object). Right now, there is no simple way to use this `styles` convert `em` lengths to `pt`, but you can work around this by simply measuring a line with that length: `measure(line(length: 1em), styles).width` will convert `1em` to `pt` (for example).

That technique doesn't work for ratios (`6%` for e.g.), which are _even more_ dependent on the context - they can be, for example, a ratio in relation to the page width, the page height, a diagonal's length... any length at all! So you need to obtain that length first, and then multiply it by the ratio (or by `float(ratio)`). However, what you _can_ do to get the current page width/height (actually the innermost container's width/height - not necessarily the page's), if that's what you're going for, is to use `layout(size => ...)`: it runs your callback with a dictionary `(width: ..., height: ...)` - here assigned to the `size` variable - indicating the width and height of the _innermost container_ (box, block, page, ...) it is in. In particular, if it is placed directly on the page (outside any blocks or boxes), it will give you the page width/height (but that doesn't matter as ratio is usually relative to the innermost container's dimensions anyway, so `layout`'s `size` will be accurate for most usages). Still, you will need to choose between width and height to multiply by the ratio (i.e. `6% * size.width` or `6% * size.height`) - and that will depend on what you need. (Either way, you might not desire the page width/height at all and instead just want to multiply the ratio by an arbitrary length you have. It's up to you.)

Finally, it gets even _weirder_ when you combine ratios and normal lengths: `56% + 1em + 2pt`. Here, you will currently need to use `regex()` on the `repr` (conversion to string) of that length to parse out the `56%` (which will then require the `layout` technique above to convert to `pt`, if working with page/container dimensions) and separate it from the `1em + 2pt`  part (which requires the line measuring trick to convert it fully to `pt`). I plan on improving this situation with this PR: #790 , though it's still draft as I haven't had much time to work on what's missing yet.

With all that said, if you just need something that will work, use this function from my tablex library: https://github.com/PgBiel/typst-tablex/blob/32823fea0189461a1662e8a169cce1310afac604/tablex.typ#L358-L431
Note that you will have to specify `styles` and/or `page_size` to convert `em` (`styles`) and/or ratio (`page_size`), which can be obtained with `style(styles => ...)` and `layout(size => ...)` respectively, as described above.

For more info (I know this is a lot of information), take a look at the docs: 
1. **style() function:** https://typst.app/docs/reference/meta/style/
2. **layout() function:** https://typst.app/docs/reference/meta/layout/

**Comment by edhebi** [comment]
at the very least, it'd be nice for the error message to talk about "relative length" vs "absolute length"

**Comment by laurmaedje** [comment]
The compiler error message could be clearer. At least it could say that it can't compare _these two_ lengths instead of stating that it cannot compare lengths at all.

> at the very least, it'd be nice for the error message to talk about "relative length" vs "absolute length"

A relative length is something different though. It uses percentages, not just em.

> this seems to affect arithmetic operations as well

I would say that makes sense as the result is not representable in any unit Typst supports. (It would be length^2)

**Comment by laurmaedje** [comment]
Should be an easy PR. :)
