### ISSUE TITLE
Replace "Linux Libertine" with the more up to date fork "Libertinus Serif"

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1257]
> Over time it grew into to a full-fledged fork addressing many of the bugs in the Libertine fonts.

https://github.com/alerque/libertinus

(Note that the web app already has the math font Libertinus Math)

**Comment by Enivex** [comment]
@reknih Regarding the label, doesn't the binary also ship with this font? I thought it was the actual default.

**Comment by reknih** [comment]
It does! More like an "and" thing

**Comment by Andrew15-5** [comment]
Is this issue has some difficulties to be resolved or why it seems that there is no progress for a while now?

**Comment by alerque** [comment]
Sure, but the longer you wait the harder it will get, and *Linux Libertine* is an abandoned project with hundreds of known issues that are fixed in *Libertinus*.

I suggest some sort of migration period where both fonts are included and any use of the former throws a warning that it will be removed from built-in status in a future version, suggesting the new name. The longer you wait to announce such a deprecation the more documents will be faced with transition.

**Comment by Andrew15-5** [comment]
I don't see any issues with documents using old font.
1. If the old font will be deprecated and still included, then literally nothing will change except the default (unset) font (which still looks almost exactly the same as the current default font).
2. Typst is still in beta, which means that there are probably will be more breaking changes, which means that changing default font (and removing an old one) can be just another breaking change in the next beta release.
3. As @alerque said, the longer you wait, the more of an impact the change will bring.
4. It will be a bit strange if someone would explicitly set "Linux Libertine" in a `set` rule while **not having** the set font installed locally **and** while the set font is the default one anyway ([doc says about default font](https://typst.app/docs/reference/text/text/#parameters-font)).

<details><summary>P.S.</summary>

It wasn't easy finding "Free alternative fonts to Times New Roman" because all the answers were a list of completely different free fonts (maybe not even free). So eventually I found Liberation font family which is kinda similar but has rough serifs instead of round ones. And only recently I found out that the default Typst font, which actually has much more similarities to the "infamous" Times New Roman. But now I discovered that there is actually an updated version of it.

The point is that I thought of "Why not Liberation Serif?", and now I know why.

And as a side note, I'm a bit disappointed that Linux Libertine/Libertinus Serif has digits that are noticeably smaller/shorter/lower than in Times New Roman or Liberation Serif. If only digits were of the same height as letters, then this would be the ultimate free alternative.

</details>

**Comment by alerque** [comment]
> And as a side note, I'm a bit disappointed that Linux Libertine/Libertinus Serif has digits that are noticeably smaller/shorter/lower than in Times New Roman or Liberation Serif. If only digits were of the same height as letters, then this would be the ultimate free alternative.

The Libertinus project has an explicit goal of following the design (and where possible, metrics) of the defunct Linux Libertine project while fixing bugs and adding features like new character ranges. The design choice for digits to follow the font height instead of ascender height is not one we'll be changing by default (some fonts do it one way, some another), but there are unused style-sets and even number related options like lnum that could be used to provide an alternative set of glyphs at a different height. The project is open source and although I've been a bit intermittent with attention it is open to contributions if you wanted to contribute something like that.

**Comment by Andrew15-5** [comment]
<details><summary>re P.S.</summary>

Oh yeah, there is a `text(number-type: "lining")` which enables `lnum` font feature that does (should do) exactly what I want. But in order to contribute, I need to learn much more about fonts and how to make them, for which I just don't have time. But maybe in the future, if no one will make it (`lnum`) by then.

</details>

**Comment by Andrew15-5** [comment]
So, can we expect a new default font in the v0.9?

**Comment by laurmaedje** [comment]
@alerque Is there also a TTF version of Libertinus Serif rather than an OTF? I'm asking for two reasons: 
1. Typst subsets those better. It's maybe not that big of a deal, but a bit unfortunate that the size of a hello world PDF grows from 11KB to 64KB.
2. We've had some issues with wrong printing in the past, which happened mostly (maybe even exclusively) with OTF fonts rather than TTF ones. That's of course our and not the font's fault, but I'm still careful to make an OTF font the default before I'm sure those are resolved.

**Comment by Andrew15-5** [comment]
> 11KB to 64KB.

[kB*](https://en.wikipedia.org/wiki/Kilobyte)

**Comment by laurmaedje** [comment]
It doesn't stack, I am referring to the subsetting. The primary file is often smaller with the OTF, but the subsetting process is way more complex.

OTF and CFF are the same in this context. OTF is the file ending of a CFF font in an OpenType container, while TTF is the file ending of a TrueType font in an OpenType container.

**Comment by Andrew15-5** [comment]
> OTF and CFF are the same in this context. OTF is the file ending of a CFF font in an OpenType container, while TTF is the file ending of a TrueType font in an OpenType container.

Ok, I'm washing my hands out of this one. This sounds very complicated because of the many variable parts (how can you keep track of all these naming shenanigans??). It's like Unicode and UTF-8 but on a whole another level. Thanks for clarifying.

**Comment by Enivex** [comment]
Another reason for updating to Libertinus Serif:

![image](https://github.com/typst/typst/assets/2191754/3afbd0d4-4dce-4b88-bf4f-6602cac59ea8)

![image](https://github.com/typst/typst/assets/2191754/e5ec0668-01f9-44e8-9450-f29c73ba3aaf)

**Comment by laurmaedje** [comment]
The printer issues should be resolved. I do plan to switch to Libertinus before the next release, hence the urgent label.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/4969
