### ISSUE TITLE
Cannot index query array, but I can repr it and iterate over it

### ISSUE THREAD

**Issue by Dragonink** [typst/typst#1314]
### Description

I am trying to print a partial outline.

I use the `query` function to find the next higher-level headings.
It returns a correct result: I can `repr` it and iterate over it, its `len` is also correct.
But when I try to index the array using `at` or `first` for example, the error `array index out of bounds (index: 0, len: 0)...` shows up!

Here is a minified version of my code:
```typst
#let format(i) = {
	[== Message #i]

	locate(loc => {
		let q = query(heading.where(level: 2).or(heading.where(level: 1)).after(loc), loc)
		repr(q) // WORKS AS EXPECTED
		repr(q.len()) // IS CORRECT
		repr(q.at(0)) // THROWS array index out of bounds

		outline(
			title: none,
			target: selector(heading).after(loc)/*.before(
				query(heading.where(level: 2).or(heading.where(level: 1)).after(loc), loc)
					.first() // THROWS array is empty
					.location()
			)*/,
		)
	})


	[=== Header]
	[=== Subframe 1]
	[=== Subframe 2]
}

= Category 1
#format(1)
= Category 2
#format(2)
= Category 3
#format(3)
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
First and foremost, this is because of how introspection (and thus `query`, `locate` etc) works in Typst: your code is run multiple times, so that Typst can be aware of things further away in the document while running your code. Therefore, on the first time you run your code, `query` doesn't return anything because your document wasn't redrawn yet (so it has no info on what's in the document yet), and then you try to access its returned array and it errors.

Still, it's not 100% ideal for it to give up immediately. I think this issue is tightly related to https://github.com/typst/typst/issues/785. Delayed errors were proposed as a solution, but not sure if they're actually possible in this particular case.

**Comment by Dragonink** [comment]
> A solution in your case is to only proceed if the array `len()` is `>= 1`.

Indeed, thank you.

> `query` doesn't return anything because your document wasn't redrawn yet

So there are some cases where Typst waits for the value to be resolved (`repr`, for loops, `len`,...)
and some where it does not (`first`, `at`)?
There is a discrepancy between the behaviours of different functions on the *same* value?

This is a huge problem.

**Comment by laurmaedje** [comment]
The functions behave the same way. It's just that `repr` and for loops do not fail when the array is empty, but `first` and `at` do. And the output you're seeing from `repr` is the one from the _final_ run (where it isn't empty), but `first` and `at` fail on an earlier run. If you hover over the variables in the web app, you can also see the intermediate values.

**Comment by Dragonink** [comment]
Of course for loops do not fail, but `repr` only prints the value from the final run, and not the intermediate ones?

My point is that I understand now that the behaviour I saw is to be expected given the inner workings of Typst.
But I still think it is awkward to call `repr` a debugging function when it only prints the value of the final run and this behaviour is not documented.
It is really confusing for a user to find out that `q.at(0)` throws an "array is empty" error when the previous line is `repr(q)` and prints an array with 4 items.

**Comment by laurmaedje** [comment]
The document by definition only displays things from the final run and putting things into the document with `repr` therefore has the same behaviour. I get that this is confusing, but it is not really `repr`'s fault, it's more the problem of debugging by putting things into the document. 

For IDEs, hover tooltips are an alternative, but for CLI users sadly there is no other alternative currently. Exposing the functionality of the hover tooltips via a `debug` function that prints to the terminal would be possible and perhaps useful.

Aside from that, we might be able to fix this class of errors by implementing some smart mechanism that delays/ignores errors due to introspection, as proposed in #785.

**Comment by laurmaedje** [comment]
Delayed errors have been implemented a while ago.
