### ISSUE TITLE
Use exact default margins

### ISSUE THREAD

**Issue by edhebi** [typst/typst#1319]
### Description

Currently the ``auto`` margins are computed as a factor of the page width. On A4 papers that factor happens to be `0.1190`. This is, I suspect, a rounding of `2.5/21 = 119047619047619`.

What that means in practice is that A4 default margins aren't 2.5cm but 2.499cm instead, due du to the rounding. I think it would be nicer if margins actually had their intended size, which in practice would require defining them by that actual size directly, rather than a ratio of the page width.

### Use Case

Let's be honest, the difference between 2.5cm margins, and 2.499cm margins is incredibly negligible, and it's also trivially solvable by the user by just using explicit margins. That being said, I think it would be nice to not rely on magic numbers and floating point round trips. That would also make the default margins more standard among other documents.

**Comment by laurmaedje** [comment]
I would be fine with changing the ratio from `0.1190` to `2.5/21.0`, but otherwise the current behaviour is intentional because this way we also have reasonable default margins for smaller page sizes like A6. This ratio is of course not perfect for every paper size, but much better than if the default is always `2.5cm` on each side.

**Comment by Enivex** [comment]
Whatever the solution, I think the mechanism that is used to determine the margins should be exposed in the documentation. Right now you have to dig into the source to find the number 0.119
