### ISSUE TITLE
Color mixing

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1326]
### Description

In the xcolor package for LaTeX (see https://ctan.uib.no/macros/latex/contrib/xcolor/xcolor.pdf) there is a mechanism for mixing colors.

![image](https://github.com/typst/typst/assets/2191754/d66e9bf1-6b06-4dd0-b8d6-2295ee0620d4)

(See section 6 in the pdf)

It would be great if typst could adopt something similar.

### Use Case

This is a convenient way of specifying colors in a more human readable way, and generating new colors from existing ones.

**Comment by leo848** [comment]
I believe the syntax looks absolutely horrible, but I am all for new methods on color regarding complement and mix.

**Comment by Enivex** [comment]
> I believe the syntax looks absolutely horrible, but I am all for new methods on color regarding complement and mix. 

Complement already exists as negate I think?

**Comment by leo848** [comment]
There already is a [`negate`](https://typst.app/docs/reference/types/color/#methods-negate) method for colors that creates the additive complement. For `mix`, I would suggest a new free function in the `color` namespace, making your example look like this:

```
let a = color.mix(
   (green, 0.4),
   (yellow, 0.6),
)

let b = a.negate()

let c = color.mix(
   (b, 3),
   (b.negate(), 2),
   (red, 1),
)
```

And I personally really like this syntax. An possibly better alternative name could be `blend` since mixing usually means combining colors subtractively.

In addition, I would suggest adding a shortcut to infer a value of 1 if none is given, so that one could just write `color.mix(red, green)` instead of `color.mix((red, 1), (green, 1))` for simple mixing. The value should of course be normalized by dividing each by the sum of all.

**Comment by Enivex** [comment]
Coincidentally (?) that aligns with https://developer.chrome.com/blog/css-color-mix/

**Comment by leo848** [comment]
> Coincidentally (?) that aligns with https://developer.chrome.com/blog/css-color-mix/

Wow, this was a really interesting read (and yes, I didn't align the syntax on purpose). It seems that it would definitely be necessary to add the supplemental color space argument to the mix function, of course depending on the amount of work it would take to implement these (and potentially increased compilation complexity). The LaTeX package also seems to cover most of these, yet the newer ones (like oklab) do not seem to be implemented yet, although they look the most interesting to me when taking a quick glance on the page you provided.

**Comment by owiecc** [comment]
Why not overload standard operators `0.4*green + 0.6*yellow`?

**Comment by Enivex** [comment]
> Why not overload standard operators `0.4*green + 0.6*yellow`? 

It's not an associative operation, and also depends on the color space.

**Comment by leo848** [comment]
> Why not overload standard operators `0.4*green + 0.6*yellow`?

1. There isn't one way to mix colors (as I just learned as well). There are a multitude of color spaces that all have advantages and disadvantages.
2. What should `0.4*green`, individually, return?
Should it be a color as well, but with transparency? This would, even if it hypothetically worked out (I'm not that well-versed in color theory, but I think adding two transparent colors will not return a fully opaque one, making this impossible), be very unergonomic as you could not specify e.g. `1*red + 2*green + 3*yellow`.
If it was a new type (to-be-mixed or similar), this would also not work as it couldn't be commutative (which is to be expected for color mixing) - color * scalar would be mixed, mixed + mixed and mixed + color would have to be color, thus `2 * green + 3 * white + 1 * red` would depend on mixed + color, i.e. effectively giving the last color 5 instead of 1 units because a color cannot store the mixing state (it boils down to lightgreen + mixed(1, red), considering both equally). If one really wanted to pursue this idea they could suggest a new type coercion / implicit narrowing from mixed to color types – in my eyes again a very bad idea as everyone would be confused just to save a few symbols.
3. It isn't always associative, especially when considering cylindrical color spaces if I understood correctly. 

All in all, I think the free-standing function solution in the color module would be optimal and overloading would not just not work at all, but also be counterintuitive und against readability, explicit- and expressiveness just to reduce keystrokes. The same reasoning applies against adding it as a method on color instances: this could potentially lead to very counterintuitive behavior where `red.mix(green).mix(yellow).mix(white)` would be 4 parts white, 2 parts yellow, 1 part green and 1 part red.
