### ISSUE TITLE
Faux dictionary expressions without values are parsed as destructurings

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#1342]
### Description

The following code does not render anything and gives no error.
```typ
#(: foo, bar)
```

The corresponding syntax tree:
```
Markup: 14 [
    Hashtag: "#",
    Destructuring: 12 [
        LeftParen: "(",
        Colon: ":",
        Space: " ",
        Ident: "foo",
        Comma: ",",
        Space: " ",
        Ident: "bar",
        RightParen: ")",
    ],
    Space: "\n",
]
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
I thought dictionary destructuring needs a let binding, e.g.
```
#let books = (
  Shakespeare: "Hamlet",
  Homer: "The Odyssey",
)
#let (Homer: h) = books
Homer wrote #h.  // Homler wrote The Odyssey
```
(https://typst.app/docs/reference/scripting/)

Though this issue points to another bug IMO, because `#(: foo, bar)` doesn't make sense and it should cause an error.

**Comment by laurmaedje** [comment]
> I thought dictionary destructuring needs a let binding, e.g.

It should, that's why it's a bug. ;)

**Comment by Leedehai** [comment]
> > I thought dictionary destructuring needs a let binding, e.g.

> It should, that's why it's a bug. ;)

Indeed, as mentioned earlier it is a bug, but not as what the name implies -- "Dictionary destructurings can be created without them destructuring anything", because `#(: foo, bar)` isn't a dictionary destructuring at all (it is not an array destructing, either. It is a "not even wrong" piece of code). This is a separate bug IMHO. 😄 

"Dictionary destructurings can be created without them destructuring anything" is something like `#let (Homer: h)` (without a following assignment) and that is correctly caught by the compiler.

**Comment by laurmaedje** [comment]
Fair
