### ISSUE TITLE
weak pagebreak after page counter update always adds pagebreak

### ISSUE THREAD

**Issue by azerupi** [typst/typst#1346]
### Description

When adding a `pagebreak(weak: true)` after an update of the page counter the pagebreak will always be inserted even if the page is empty.

**To reproduce:**
```
#counter(page).update(1)

#pagebreak(weak: true)
= Page 1

#pagebreak(weak: true)
= Page 2
```

I would expect no pagebreak to be inserted as there is no visible content on the page before the pagebreak.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by maxcrees** [comment]
I think the issue is that updating the counter (or any state for that matter) returns a piece of content - this is so the compiler is able to order the various updates with respect to layout order. This piece of content is typically not visible, but results in corner cases like this.

Because that content is inserted, pagebreak no longer believes the current page is entirely blank (although it appears to be), and thus weakness does not apply.

I agree that this would be useful to support, but I'm not sure how complex it would be to do so.
