### ISSUE TITLE
Linebreak between ) and [ causes error (in #footnote)

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#1359]
### Description

I have a footnote which looks like

```typc
#footnote[#text(weight: "black", fill: red)[Note:] This is important!]
```

If the editor wrapping the line makes it 

```typc
#footnote[#text(weight: "black", fill: red)
[Note:] This is important!]
```

which can happen inadvertedly, it causes an error.

same for something like

```typc
this is a test #align(left, text(size: 12pt)
[text])
```

I don't know how much work this would be nor whether this has been reported before but I think it should be fixed.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is working as intended. Trailing content blocks after function calls must follow immediately without whitespace. Otherwise, there would be too much ambiguity.

**Comment by Enivex** [comment]
> If the editor wrapping the line makes it
> 
> ```
> #footnote[#text(weight: "black", fill: red)
> [Note:] This is important!]
> ```
> 
> which can happen inadvertedly, it causes an error.

Soft wrapping doesn't actually introduce linebreaks in the source, and would not cause a compiler error here. If you want to add actual linebreaks for readability, you just have to make sure that the trailing content block starts on the previous line, i.e. for instance
```
#footnote[
    #text(weight: "black", fill: red)[
        Note:
    ]
    This is important!
]
```

**Comment by ondohotola** [comment]
Hard wrapping does, and “working as intended” is not necessarily the same as “working in the real world”.

I am not sure that “must follow immediately or immediately after a line break” is ambiguous.

With the utmost of respect.


el

--

**Comment by laurmaedje** [comment]
Hard wrap will also cause other problems, like `-` or `+` suddenly being at the start of a line. 

Typst is not designed to be arbitrarily hard wrapped. Trailing content must immediately follow the call, both in markup and code, because unclear situations arise otherwise:
The following two examples show it would be problematic in code.
```
#{
  text(weight: "black")
  [Note] // are these two expressions or one?
}

#for x in foo() [ // does this iterate over foo() or call foo()[..]
  ..
]
```

In markup, it is a general rule that a `#` expression ends at whitespace or newlines because otherwise you can never be sure that the following text doesn't accidentally continue your expression.
