### ISSUE TITLE
Compiler crash by looping through unicode

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1373]
### Description

So, as one does, I wanted to test out the limits of this https://github.com/typst/typst/commit/b805c5f10080912cbfb1fd2fd2733c48a92ce4f9

Turns out it's very easy to make the compiler crash

For instance
```
#{
    for i in range(1518){
        str.from-unicode(i)
        sym.zws
    }
}
```
will crash (1517 does not) with the error
```
thread 'main' panicked at 'byte index 18446744073709551613 is out of bounds of `֖​֗​֘​֙​֚​֛​֜​֝​֞​֟​֠​֡​֢​֣​֤​֥​֦​֧​֨​֩​֪​֫​֬​֭​֮​֯​ְ​ֱ​ֲ​ֳ​ִ​ֵ​ֶ​ַ​ָ​ֹ​ֺ​ֻ​ּ​ֽ​־​ֿ​׀​ׁ​ׂ​׃​ׄ​ׅ​׆​ׇ​׈​`[...]', library\src\text\shaping.rs:285:23
```
Note that it's not simply \u{5ed} (5ed_16=1517_10) that is problematic, as
```
#{
    for i in range(1518){
        box(str.from-unicode(i))
    }
}
```
works just fine.

Another fun error is from
```
#{
    for i in range(6981){
        box(str.from-unicode(i))
    }
}
```
which results in
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 2', C:\Users\redacted\.cargo\registry\src\github.com-1ecc6299db9ec823\rustybuzz-0.7.0\src\complex\universal_machine.rs:370:47
```
(6980 will not)

This last error even occurs if I call \u{1b44} (which is a valid unicode character https://www.compart.com/en/unicode/U+1B44 )

Now, I realize that some of these errors likely stem from invalid symbols or invalid combinations of symbols (the "breakpoint" in the first example above can change depending on where the range starts), but I'd hope to see a slightly more graceful error message.

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
This bug seems to be caused by one of the glyphs in a `ShapedText` having a `range` value whose start goes below the shaped text’s `base` value. In this case, this is the ZWS at byte index 7074, right before the instance of U+05A1. This, in turn, probably arises because `ShapedText::find_safe_to_break` (used by `ShapedText::reshape`) assumes that the `.range.start` value of the glyphs are monotonic, while certain shaped texts do not fulfill this condition. Here’s a smaller working example:

```typst
#"\u{590}\u{200b}\u{591}\u{200b}\u{592}\u{200b}\u{593}\u{200b}\u{594}\u{200b}\u{595}\u{200b}\u{596}\u{200b}"
```

**Comment by Enivex** [comment]
@bluebear94 can this be closed?

**Comment by bluebear94** [comment]
I think so.
