### ISSUE TITLE
Page numbering seems to have an impact on `location.page()`

### ISSUE THREAD

**Issue by giltho** [typst/typst#1391]
### Description

It seems like the location used in the callback of the `locate` function is sensitive to page numbering, although the documentation explicitly says:

> Note that this does not return the value of the [page counter](https://typst.app/docs/reference/meta/counter/) at this location, but the true page number (starting from one).

Looking at the reproduction url, it seems like the behaviour of `cleardoublepage()` on line 83 is affected by the `set page(numbering: "1")` on line 82, where `cleardoublepage` is defined as follow

```typst
#let cleardoublepage() = {
  locate(loc => {
      pagebreak()
      if calc.odd(loc.page()) {
        pagebreak()
      }
    }
  )
}
```

The goal is to create a function that has a similar behaviour to [latex's `\cleardoublepage`](http://www.emerson.emory.edu/services/latex/latex_103.html)

### Reproduction URL

https://typst.app/project/rfyWudk35uU1UI864l71AR

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by zach-capalbo** [comment]
For what it's worth, I'm running into the same issue without even using `set page(numbering: ...)`

It seems like if the content returned by `locate` conditionally includes a `pagebreak`, or even enough content to push it to a new page (like `v(100%)`), then `loc.page()` is _sometimes_ incorrect.

I've added another demo showing this issue here. Seems to work fine until about page 15 (where `locate` says it's page 16):

https://typst.app/project/rTlA3vEa52cByEa6gH_WNn

**Comment by laurmaedje** [comment]
> For what it's worth, I'm running into the same issue without even using set page(numbering: ...)

It's a different problem. Inserting pagebreaks like this results it a non-convering layout because Typst relayouts the document again and again to resolve the counters and every time it shifts, rippling through.

However, you can just use `pagebreak(to: "odd")` or `pagebreak(to: "even")` today.

As for the original bug: The share link doesn't work anymore, but I suspect it is a similar case as https://github.com/typst/typst/issues/1886 and https://github.com/typst/typst/issues/2987, so I'll close this one.
