### ISSUE TITLE
Image rotation is totally broken

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1404]
### Description

Try to rotate any image and it will collapse the pixel counts down to just one once you hit 90 degs.

For example:
```
#rotate(90deg, image("Screenshot from 2023-06-03 22-10-27.png"))
```

On this image:
![Screenshot from 2023-06-03 22-10-27](https://github.com/typst/typst/assets/9490724/e9953162-3599-4b57-b3c7-09cf27f4af2b)

Produces the following result:

![image](https://github.com/typst/typst/assets/9490724/fe5d6107-a901-4d1a-973f-5f787d9dc5c8)

Honestly kinda funny lol. We can have some fun with say 85 degrees:

![image](https://github.com/typst/typst/assets/9490724/1417a307-a85f-49aa-9f38-de715f0293d9)

### Typst version

- [ ] I am using the latest version of Typst

**Comment by TomBinford** [comment]
This is a bug with PNG rendering (in the web app and from CLI), rotation looks fine in PDF output.

**Comment by TomBinford** [comment]
I believe the issue is how Typst handles transforms in `render_image`: https://github.com/typst/typst/blob/6c542ea1a4a0ee85069dad6974ff331851eff406/src/export/render.rs#L481
`render_image` resizes the image with `scaled_texture(image, w, h)` where `w` and `h` are calculated based on `scale = ts.sx.max(ts.sy)`.
This is a bug because rotation by `angle` gives `sx = sy = angle.cos()`. At 90 degrees $\text{sx}, \text{sy} \approx 10^{-16}$ making `scale` << 1 and w = h = 1. We are scaling the image down to 1 pixel and then back up to normal size.

I have two fixes to find `scale` more accurately:
1. take the determinant `ts.sx.abs() * ts.sy.abs() - ts.kx * ts.ky` (the area scaling factor) and sqrt it (for the side-length scaling factor, correct when x and y are scaled equally and approximately correct when they aren't)
2. solve the system
$$\text{sx} = \text{scale}\_\text{x} \cdot \cos \theta$$ $$\text{kx} = -\text{scale}\_\text{x} \cdot \sin \theta$$ for $\theta = \text{atan2(-kx, sx)}$ and then for $\text{scale}\_\text{x}$ as either $\frac{\text{sx}}{\cos \theta}$ or $\frac{-\text{kx}}{\sin \theta}$ depending on whether $\cos \theta$ or $\sin \theta$ is further from 0. This assumes that skew is only introduced through rotation, which is true in current Typst.

I prefer (2) because the output is less crunchy for e.g. `#rotate(0deg, scale(x: 200%)[#image("screenshot-of-text.png")])` because the painting step introduces fewer artifacts when the image is scaled correctly beforehand.

**Comment by laurmaedje** [comment]
The `scaled_texture` thing exists for two reasons if I remember correctly: Because the image crate's interpolation looks better than tiny-skia's and because rendering with tiny-skia at full resolution was relatively slow and can't be memoized.

I don't know how other rendering engines do it, maybe we could take some inspiration. But scaling to something that has about the correct size seems sensible and if your solution does that, I'm all for it.

**Comment by TomBinford** [comment]
That reasoning makes sense, I agree `scaled_texture` looks better than letting tiny-skia handle everything.
I will PR option 2 within a couple days.
