### ISSUE TITLE
Paragraph indentation is reset after list

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1410]
### Description

```
#set par(justify: true, first-line-indent: 1em)

Test

Paragraph

- Test list

Paragraph
```

![image](https://github.com/typst/typst/assets/9490724/48d9f93a-8d58-4fe6-a6f6-d94a7280f074)

I'm not sure if this should be how the feature works. I feel like a list is just another paragraph.

At the very least, this makes the IEEE template create inconsistent `===` headers when they are placed after a list because they don't get indented like the others.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Copying from #1600: 

The idea of the current implementation is to only indent consecutive paragraphs. This makes sense because spacing and indent shouldn't be mixed: Indent to separate paragraphs and spacing to separate paragraphs from other blocks. Unfortunately, the current implementation is broken because many things, like headings, are treated as paragraphs while they shouldn't be.

The other reasonable option is to indent every paragraph. This isn't currently possible, see #311. But once it's possible to implement I want to have an option for this.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/311
