### ISSUE TITLE
Publish at flathub as flatpak

### ISSUE THREAD

**Issue by lumingzh** [typst/typst#1414]
### Description

It will be great to publish the app and runtime/compiler as flatpak at flathub.

### Use Case

All linux users can easily install and auto update the app, thank you.

**Comment by alerque** [comment]
As far as I know the *app* end of Typst is not open source and only deployed on their proprietary domain. One cannot even run it locally from public sources. Only the compiler itself is open source.

As for the compiler, I don't think it makes any sense at all to wrap in in a Flatpak because all it is is a single statically linked binary anyway.

**Comment by lumingzh** [comment]
> As far as I know the _app_ end of Typst is not open source and only deployed on their proprietary domain. One cannot even run it locally from public sources. Only the compiler itself is open source.
> 
> As for the compiler, I don't think it makes any sense at all to wrap in in a Flatpak because all it is is a single statically linked binary anyway.

Well, flathub and flatpak don't care the app is open source or not. For the compiler I think can make it as extension of freedesktop runtime just like texlive. 

Or maybe I should looking for third typst application?

**Comment by laurmaedje** [comment]
There is no official local app yet, so there is nothing to publish.
