### ISSUE TITLE
Clickable footnotes

### ISSUE THREAD

**Issue by FriederHannenheim** [typst/typst#1476]
### Description

Footnotes should be clickable in the PDF to get to the bottom of the page, also there should be a link back to the number so you can jump back to the content you where reading easily.

### Use Case

When I'm reading a document and I see a footnote I can click it to go read the footnote and then click an arrow to get back to what I was reading.

**Comment by Enivex** [comment]
> also there should be a link back to the number so you can jump back to the content you where reading easily

Most pdf readers have a shortcut that returns you to the place you came from

**Comment by laurmaedje** [comment]
This is already implemented 🤔

The small number on the page is clickable to jump to the bottom and the small number at the bottom is clickable to jump back to the top. 

Only the number is the link as the footnote might also contain other links and it might clash, otherwise. It also depends on your viewer how exactly they scroll a link destination into view (although the file also has a say in this).

**Comment by laurmaedje** [comment]
Closing this as it's already implemented. If you meant something else, please comment and we can reopen.
