### ISSUE TITLE
LaTeX export

### ISSUE THREAD

**Issue by pbsds** [typst/typst#149]
Can i use this to publish to journals / conferences that require the latex source?
Let's face it, the publishing world moves at a snails pace.

**Comment by SaadiSave** [comment]
No, it is not currently possible to convert a typst file to LaTeX, and it will perhaps never be, because typst is fundamentally different.

> Let's face it, the publishing world moves at a snails pace.

However, with the backing of the Technical university of Berlin, it will move faster this time.

**Comment by Enivex** [comment]
https://github.com/jgm/pandoc/issues/8713

Relevant

**Comment by phiresky** [comment]
I created a draft PR which (indirectly) adds latex output: https://github.com/typst/typst/pull/461

**Comment by reknih** [comment]
We will not directly support LaTeX export as Typst is just too different to provide a satisfactory high-quality conversion. However, the Pandoc project might work on adding a reader for Typst files (https://github.com/jgm/pandoc/issues/8740) that will allow medium-fidelity conversion to LaTeX. Alternatively, an approach could be to directly convert the eventual HTML output (#114).

**Comment by RaulDurand** [comment]
> No, it is not currently possible to convert a typst file to LaTeX, and it will perhaps never be, because typst is fundamentally different.
> 
> > Let's face it, the publishing world moves at a snails pace.
> 
> However, with the backing of the Technical university of Berlin, it will move faster this time.

Is there any ongoing initiative or concerted effort to encourage academic journals to adopt Typst as an alternative manuscript format? 
Additionally, what actions can current users take to support this adoption?

**Comment by Enivex** [comment]
> Is there any ongoing initiative or concerted effort to encourage academic journals to adopt Typst as an alternative manuscript format?

No, because typst has to reach stable before that's even an option.

**Comment by nullst** [comment]
Since this issue is still the top google result for "convert typst to LaTeX" despite more than a year since the last post, it's probably worth mentioning here that as of 2024 the [Pandoc project](https://pandoc.org/) has a working "typst reader", which means that it can be used to convert typst code to LaTeX (as well as to HTML, Markdown, and many other formats).

#### Converting typst markup to LaTeX using pandoc
Running 
```
pandoc --from typst --to latex -
```
with a recent pandoc version and entering
```
Text _formatting_, and math $x in union.sq_(i in ZZ_(gt.eq 0)) U_i$ formulas as well
````
results in
```
Text \emph{formatting}, and math
\(x \in \sqcup_{i \in {\mathbb{Z}}_{\geq 0}}U_{i}\) formulas as well
```
There is an [online](https://pandoc.org/try/) version as well.

#### Note on usage

In my experience even moderately complicated documents (no manual scripting, but using packages such as [ctheorems](https://typst.app/universe/package/ctheorems/), with many formulas) usually cause parsing issues in pandoc's typst reader, so I had to write a script that performs a bunch of regular expression substitutions to simplify my typst code in order to make it compatible with pandoc.
