### ISSUE TITLE
Add functions for exporting data

### ISSUE THREAD

**Issue by nineff** [typst/typst#1512]
### Description

Just like there's data loading functions (a generic one as well as some special formats like CSV and JSON), there should be functions to save data to the disk and not just rendering it to the PDF.
The most basic option would be to simply save a String as is to a file, more advanced versions could serialize Typst dictionaries and arrays to JSON etc.

### Use Case

- provides two-way "communication" with external tools
- ability to save intermediate results
- functional completeness
- debuging

**Comment by SliceOfArdath** [comment]
Hi! I'm currently working to implement this! check out [my fork](https://github.com/SliceOfArdath/typst) if you want, but beware! it's not quite done yet

**Comment by laurmaedje** [comment]
This is indeed not something that we plan to support. With `typst query` there is a good tool for most tasks now. For debugging, I _do_ plan to add a simple logging facility (https://github.com/typst/typst/issues/1669). Just the file writing part itself not because of its security and UX implications (as written in the responses on the other issues).
