### ISSUE TITLE
Cycle bulleted list marker by default

### ISSUE THREAD

**Issue by KronosTheLate** [typst/typst#1520]
### Description

It seems weird to me to reuse the same marker for any level of list nesting. Should a default not be provided with 3 or 4 levels? My first approximation has been to add
```
#set list(marker: ([•], [◦], [-], sym.bullet))
```
To all my documents, and I think I will add it in my templates.

### Use Case

Everyone who makes nested lists, and wants to be able to visually distinguish nesting levels more easily.

**Comment by Enivex** [comment]
• is the same as sym.bullet by the way

**Comment by Enivex** [comment]
That's just the font there being weird. They're both U+2022

**Comment by augustebaum** [comment]
Looking into this for fun, here's what I've found!

[This](https://github.com/typst/typst/blob/265b37d12d8a800227f5731cf9310955f8486abf/crates/typst-library/src/layout/list.rs#L197) is where the logic of reusing the last list item when there are no more is defined.

On the other hand, in the codebase's current state, the desired cycling behaviour can be obtained with this bit of Typst code:
```typst
#let cycle_markers(markers) = {
  let marker_fn(markers, depth) = {
    let index = calc.rem(depth, markers.len())
    markers.at(index)
  }
  depth => marker_fn(markers, depth)
}

#set list(
  marker: cycle_markers(([•], [◦], [-], [+]))
)
```

**Comment by emmett-rayes** [comment]
The current default list markers are defined [here](https://github.com/typst/typst/blob/265b37d12d8a800227f5731cf9310955f8486abf/crates/typst-library/src/layout/list.rs#L80).

I think extending the list with more symbols would provide a good default, e.g.

```rust
#[borrowed]
#[default(ListMarker::Content(
    vec![
        TextElem::packed('•'),
        TextElem::packed('◦'),
        TextElem::packed('∗'),
        TextElem::packed('-'),
    ]
))]
pub marker: ListMarker,
```
which results in

<img width="272" alt="Screenshot 2023-11-11 at 00 32 05" src="https://github.com/typst/typst/assets/109030944/284d89ca-2ecd-4945-b05b-2a924ca07172"><br>

However, I don't agree with cycling the markers per default because that would break the current behaviour as defined by the docstrings and it can be achieved [directly](https://github.com/typst/typst/issues/1520#issuecomment-1784208035) in Typst anyway.

**Comment by Leedehai** [comment]
I agree making the list markers different for different levels of indentation makes sense. YMMV, but in my first impression having the same markers for all levels of indentation gave me a feeling that it was a "rough edges" Typst has.

I don't have an opinion of cycling the markers. At Google Doc does it and it seems fine (who on earth would need that many levels of indentation?)

**Comment by KronosTheLate** [comment]
> However, I don't agree with cycling the markers per default because that would break the current behaviour as defined by the docstrings

That is a non-issue - just update the docstring, right? We are pre 1.0, so breakage is to be expected. We can not lug around a bad default that 90% of users would want to change to avoid breakage, and especially not given the state of the project

> and it can be achieved [directly](https://github.com/typst/typst/issues/1520#issuecomment-1784208035) in Typst anyway.

But good defaults, i.e. no need to create a custum template for every user, is an INCREDIBLY important point. I see it again and again - a large fraction of users are not interested in perfecting their template, they want to create a document with minimal work. This means that the default has to be terrible for them to change it, unless that default discurages them from using it in the first place. My point is that "you can do this yourself" is a dangerous way to view things, if widespread adoption is the goal. It is really important to make it easy to get started.

**Comment by KronosTheLate** [comment]
As a sidenote, I can not think of a program that creates documents that did _not_ cycle markers by default:
![image](https://github.com/typst/typst/assets/61620837/8f75ba90-de96-41ed-84ba-d81140d8a0a0)
![image](https://github.com/typst/typst/assets/61620837/0a674ce3-7202-4001-9bce-b47df57978ac)
![image](https://github.com/typst/typst/assets/61620837/345cd5bb-e4b7-431c-b841-fb73c33ad8a0)
![image](https://github.com/typst/typst/assets/61620837/ca395011-0dac-4483-b51f-62d290e45354)

This is the reason why this feels like a "rough edge" as mentioned above, which i 100% agree with. It is just an expected feature from a bullet list in a document.

But looking into what others do happened to reveal a clear majority for the style, which is fantastic news! We can stop [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) on those details, and get it done. I feel like it is clear that we neglect the style of LaTeX (which to me looks the worst, and is almost guaranteed a smaller fraction of users than the other 3 combined), and **adopt the style of the first 3 examples: Cycle 3 different markers, in the order SolidCircle, HollowCicle, SolidSquare.**

**Comment by Leedehai** [comment]
> But looking into what others do happened to reveal a clear majority for the style, which is fantastic news! We can stop [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) on those details, and get it done. I feel like it is clear that we neglect the style of LaTeX (which to me looks the worst, and is almost guaranteed a smaller fraction of users than the other 3 combined), and adopt the style of the first 3 examples: Cycle 3 different markers, in the order SolidCircle, HollowCicle, SolidSquare.

It's not easy to get the markers right. I attempted to use
```
        vec![
            // These need to be of the same size. See the Unicode standard UTR #25:
            // http://www.unicode.org/reports/tr25/tr25-15.pdf table on page 20-21
            TextElem::packed('\u{2022}'),  // "BULLET"
            TextElem::packed('\u{25E6}'),  // "WHITE BULLET"
            TextElem::packed('\u{25AA}'),  // "BLACK SMALL SQUARE"
        ]
```
Link: [UTR#25](http://www.unicode.org/reports/tr25/tr25-15.pdf) pp.20-21

But it turned out the default fonts render the third one (25AA) larger than the previous two, and is off-center.
<img width="203" alt="Screenshot 2023-11-26 at 11 17 02" src="https://github.com/typst/typst/assets/18319900/e1bf0501-482c-4425-8119-97f66b9ed062">

Similar black squares listed in that table are not good either. For instance, `1F78D` puts the square off-center:
<img width="196" alt="Screenshot 2023-11-26 at 11 17 45" src="https://github.com/typst/typst/assets/18319900/362345cb-fe75-4f6a-995c-98e3d89306d3">

**Comment by Enivex** [comment]
I suspect that it's falling back to the math font, and that's why it's inconsistent. Would it make more sense to always render the bullets in the math font, since they typically have more symbols?

**Comment by reknih** [comment]
Moved from PR review comment:

Given the points made in https://github.com/typst/typst/issues/1520#issuecomment-1826826247, I would propose the order `•` (U+2022), `‣` (U+2023), `–` (U+2013). This order circumvents U+25AA which is not centered in the default font. It also arranges the symbols in decreasing order of visual weight. Finally, it does not contain U+25E6 which both @laurmaedje and I strongly dislike.

I do not feel like we have to copy the U+2022, U+25E6, U+25AA order from Word et al. LibreOffice Writer and Google Docs converged on this because they try to be just like Word while we hardly even try to be just like LaTeX. We are free to choose our enum symbols in a way which we believe to be conducive to effective and aesthetic communication.

That being said, if we must use U+25E6 due to a strong consensus by other contributors / users, it would replace the en-dash in my order since it is only an outline instead of a solid shape.

**Comment by Enivex** [comment]
> This order circumvents U+25AA which is not centered in the default font

Have you checked this in the proposed updated default font?

https://github.com/typst/typst/issues/1257

**Comment by KronosTheLate** [comment]
I see the point that we do not have to copy the markers used by word. But given that there is a strong consensus, the alternative proposal should not just be a little better, but significantly better, IMO.

**Comment by laurmaedje** [comment]
Since U+25AA isn't even available in the default font (even in the future one), we _have_ to deviate from what Word et al do. And if you look closely, Word and LibreOffice don't even use the same thing for level 2 (Word's circle is botched and looks like an "O").

@reknih and I think that our proposed order is significantly better than this. I adjusted [the PR](https://github.com/typst/typst/pull/2788) to use this order and merged it.
