### ISSUE TITLE
release tag names

### ISSUE THREAD

**Issue by JonasLoos** [typst/typst#155]
The release tags are something like `22-03-21-2`, which I guess stands for `March 21, 2022 - Version 2`. However, to my knowledge, we already have 2023, so I suggest changing the tag names accordingly.

**Comment by imatpot** [comment]
What about [semantic versioning](https://semver.org/)?

I think it would make sense to introduce this fairly quickly, despite still being in the pre-release phase for the sake of simplicity. Since it's a pre-release you can start with something like 0.1.0 and continue from there, having breaking changes remain in the minor increments for now, whereas everything else goes in the patch).

Once Typst hits its first stable release, we can then move on to 1.0.0 and fully apply semantic versioning.

**Comment by laurmaedje** [comment]
I fixed the tag names.
