### ISSUE TITLE
bibliography does not deal with date entry

### ISSUE THREAD

**Issue by Meistermagier** [typst/typst#1553]
### Description

If you import a .bib file with a date entry. This is not used when referenced. The reference is then still shown as n.d.
![image](https://github.com/typst/typst/assets/25961872/725b9f57-5268-4fa1-b02b-1c9abf5061ac)

### Reproduction URL

https://typst.app/project/r2Aoe8Fl7ybMilBZA9K8cv

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
The date is formatted differently from the date formats accepted by biblatex (see Section 2.3.8 of [this manual](https://ctan.math.illinois.edu/macros/latex/contrib/biblatex/doc/biblatex.pdf) for more). Setting the date field to `2020-09-26` fixes the issue.

**Comment by Meistermagier** [comment]
Ok thank you very much. This seems to be a problem with my citation software (Citavi), which exports in German format. You can close the issue then. My problem then lies somewhere else.

**Comment by toihr** [comment]
@lennart02 sorry for the late reply, I did not use Citavi Web and have since switched to using Zotero. But if my memory serves me right you can in the Windows Version of Citavi adjust the exported Citation format. As described here in the manual, maybe it helps you if you still have this issue. https://www1.citavi.com/sub/manual6/en/index.html?citationstylelistdialogex.html
