### ISSUE TITLE
Mermaid diagramming support?

### ISSUE THREAD

**Issue by adamijak** [typst/typst#161]
Do you plan to support https://mermaid.js.org ? I think it might be great way to generate graphs diagrams in typst.

**Comment by k12ish** [comment]
There's a couple of similar requests which involve supporting some markup language inside of Typst (eg. #184)

I don't think any of these will supported as a primitive in Typst, but rather Typst will allow you to write functions that parse and render your custom Markup language. 

As the language and ecosystem evolve, I think we'll move towards a system where users can import libraries which provide such functions, but we are not there yet.

**Comment by ecstrema** [comment]
A few mermaid rust compilers have been developped lately. 

- https://github.com/cmwright/mermaid-rs
- https://github.com/Latias94/merman

I'd be greatly in favor of reusing mermaid's syntax instead of building something new, if this needs to be integrated into the core.

In general though, it might as well stay as a plugin as it works pretty well... At least for my purpose. Would be curious to hear what others think about it.
