### ISSUE TITLE
Incorrect baseline for integrals with Libertinus Math

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1620]
### Description

Typst:
![image](https://github.com/typst/typst/assets/2191754/dbb48e06-8a8f-4830-93ae-e8bd3d94ce47)

LuaLaTeX:
![image](https://github.com/typst/typst/assets/2191754/b6037f0b-cb93-4bd0-b4f8-b85131f89c42)

(The other symbols are just there for illustration purposes)

Replicated in the web app as well

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment]
Out of curiosity can you post the Typst and LaTeX sources used for this MWE?

(I am the upstream project maintainer for Libertinus fonts.)

**Comment by Enivex** [comment]
> Out of curiosity can you post the Typst and LaTeX sources used for this MWE?
> 
> (I am the upstream project maintainer for Libertinus fonts.)

Like I mentioned, the actual details aren't important, because integrals are consistently displayed like this. Anyway, these work:

LuaLaTeX
```
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Libertinus Math}

\begin{document}
    \[
        \sum_{k=0}^\infty \int_0^\infty e^{-kx^2}\,\mathrm{d}x
    \]
\end{document}
```

Typst
```
#show math.equation: set text(font: "Libertinus Math",fallback: false)

$ sum_(k=0)^oo integral_0^oo e^(-k x^2) dif x $
```

**Comment by alerque** [comment]
Thanks for the code snippets. In may or may not be the font. LaTeX does so much post processing to the layout rather than just using the OpenType MATH data it's always hard to tell. Just because something works in LaTeX doesn't mean the font is correct (and the inverse is true too).

Interestingly, this exact same issue shows up in SILE, which suggests either our math implementations have the same oversight or it might be the font:

```sile
\begin{document}
\use[module=packages.math]
\set[parameter=math.font.family,value=Libertinus Math]

\begin[mode=display]{math}
  \sum_{k=0}^\infty \int_{0}^\infty e^{-kx^2}\,\mo{d}x
\end{math}

\end{document}
```

![20230630_14h46m00s_grim](https://github.com/typst/typst/assets/173595/1a056088-500b-4487-83e7-d5518c651515)

For ease of playing around with comparisons like this I just started a scratch repo with these MWE's and a Makefile to rebuild the PDFs: https://github.com/alerque/typesetter-comparisons
