### ISSUE TITLE
Consider user-level name scope alias?

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#171]
Hi thanks for making this!

One thing that I have been uncomfortable with LaTeX is the lack of user-level namescope aliases: users are at the mercy of the third party module authors, who may or may not reuse an existing name. Problems are:
* symbols from various third party modules could collide with the built-in ones or with each other, and
* it's hard to reason about which symbol is from which module.

Some languages like C++ do have names scopes with `namespace`, but it depends on the module author, not the user, so the problems above still exist to some degree.

I wish Typst could address this pain point from the start 😄  Syntax I have in mind (compatible with the current design) are:
* import some symbols and use them directly in the global scope (current behavior according to https://typst.app/docs/reference/types/module/):
  ```
  #import "somepackage.typ": foo, bar

  #foo #foo.subfoo #bar
  ```

* import all symbols and use them directly in the global scope (current behavior according to https://typst.app/docs/reference/types/module/):
  ```
  #import "somepackage.typ"

  #foo #foo.subfoo #bar
  ```

* import a package and use its symbols under a scope (proposed new behavior):
  ```
  #import "somepackage.typ": "sp" // user-given name alias

  #sp.foo #sp.foo.subfoo #bar
  ```

Of course, the syntax is up to you folks:) I simply wish Typst introduce user-level name scoping to
* avoid symbol name collisions, and
* help users to reason about which symbols come from which third party modules.

Also, I wish Typst could consider a mechanism to differentiate public and private symbols, meaning symbols that are visible/invisible to files that `#import` the file. This will make third party module authoring easier and reduce possibility of name collisions.

Thanks!

**Comment by k12ish** [comment]
Thank you @Leedehai for a well written out issue!

However, the Typst team have already implemented this feature:


> ![image](https://user-images.githubusercontent.com/45272873/227202004-a54f903f-65b1-410f-b8cc-a98023095287.png)


- Source: https://typst.app/docs/reference/scripting/#modules

**Comment by Leedehai** [comment]
Thanks @k12ish! But this is the "current behavior" I was referring to.

However, there's an issue I think: if two third party modules have the same file name, the name scope will collide. After all, there are not user-given alias, but dependent on how the module authors name their files.

```
#import "berlin/mathsymbols.typ"
#import "frankfurt/mathsymbols.typ"

mathsymbols.specialsymbol // which module?
```

**Comment by k12ish** [comment]
Thanks @Leedehai for clarifying there - I've just done a deep dive into import statements in Typst 

Here are a series of import statements and their equivalents in Python:

|Python   | Typst   |
|---|---|
| `import foo`            | `#import "foo.typ"`       |
| `from foo import *`     | `#import "foo.typ": *`    |
| `from foo import Fizz`  | `#import "foo.typ": Fizz` |
| `import foo.bar as bar` | `#import "foo/bar.typ"`   |


Perhaps Typst could handle directories in a similar manner to Python:

|Python   | Typst   | Notes   |
|---|---|---|
| `import foo.bar`        | `#import "foo/bar.typ"`     | Accessible through 'foo.bar' |
| `import foo`            | `#import "foo"`             | Import of directory   |    
| `from foo import bar`   | `#import "foo": bar`        | Import of submodule into namespace  |


Here's how Python handles namespaces, and how it could be handled by Typst:

|Python  | Typst  | Notes  |
|---|---|---|
| `import foo as biz`               | `#import "foo.typ" as biz`          |                                 | 
| `import foo as biz`               | `#import "foo" as biz`              | `foo` is a directory                     | 
| `import foo.bar as biz`           | `#import "foo/bar.typ" as biz`      | Here, `biz` must be a module    |
| `from foo import bar as biz`      | `#import "foo": bar as biz`         | Here, `biz` may or may not be a module |
| `from foo.bar import Buzz as Biz` | `#import "foo/bar.typ": Buzz as Biz` |                                 |

----

Conveying the subtlety between some of these statements is quite difficult. Personally, I think Typst should adopt import syntax and semantics closer to Python, since Python is becoming the defacto language in acedemia.

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/1923
