### ISSUE TITLE
Option to return the separators as well while splitting a string

### ISSUE THREAD

**Issue by Nabav** [typst/typst#1710]
### Description

Currently, the `split` method of string type returns the resulting parts and drops the detected separators.

I would like to ask for an optional boolean argument of this method which also returns the separators.

```typst
"a,b;c".split(regex("[,;]"))
// ("a", "b", "c")
```

Feature request:

```typst
"a,b;c".split(regex("[,;]"), keep-sep: true)
// ("a", ",", "b", ";", "c")
```

### Use Case

This can be useful when a split string is going to be joined with the same separators after doing some processing on individual words.

**Comment by bastienvoirin** [comment]
In JavaScript, the separator can be included in the resulting parts either by capturing it (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#splitting_with_a_regexp_to_include_parts_of_the_separator_in_the_result) as in `([,;])`, or by using look-ahead and look-behind (i.e. look-around) to match separator *boundaries* (zero-width *positions*) instead of the separator itself as in `(?=[,;])|(?<=[,;])`. The latter is not supported by the `regex` crate Typst uses:

> The regex syntax supported by this crate is similar to other regex engines, but it lacks several features that are not known how to implement efficiently. This includes, but is not limited to, look-around and backreferences.
> (https://docs.rs/regex/latest/regex/)

That being said, perhaps your `keep-sep` optional boolean argument would be more intuitive than capturing the separator.

**Comment by laurmaedje** [comment]
I'm not sure this is useful enough to warrant being in the standard library. It is also fairly easy to implement in user code:

```
#let split-with-sep(s, pattern) = {
  let prev = 0
  for m in s.matches(pattern) {
    (s.slice(prev, m.start), m.text)
    prev = m.end
  }
  (s.slice(prev),)
}

#split-with-sep("a,b;c,d", regex("[,;]"))
```

**Comment by laurmaedje** [comment]
There are also different possible interpretations. For instance, Rust has [`str:split_inclusive`](https://doc.rust-lang.org/std/primitive.str.html#method.split_inclusive), but it's actually _different._ It keeps the separators are part of the items before them. These different interpretations could make a `keep-sep` paramter potentially confusing.
