### ISSUE TITLE
Change equal sign attachment to limits

### ISSUE THREAD

**Issue by StrangeGirlMurph** [typst/typst#1720]
### Description

Currently attachments to the equal sign and all the other "equal related" symbols are placed as sub/superscripts. I think they should all instead be rendered as limits. 

### Use Case

I think most people use attachments with equal signs to state why an equality/inequality/thingy holds. Those things usually get written on top of the symbol. For example when you want to denote that you're using the induction hypothesis:

`$ =^"IH", quad limits(=)^"IH" $`
![image](https://github.com/typst/typst/assets/62220780/dc411042-d519-40e7-838e-acb5f67541e4)

 I can't actually think of any usecase where you would want an attachement to be placed as a sub/superscript and writing `limits(=)` so often is exhausting.

**Comment by sitandr** [comment]
Just in case: you can easily achieve this behaviour now using

```
#show math.eq: math.limits
```

But I agree that could make things easier for beginners.

**Comment by lolstork** [comment]
The list of characters which default to displaying as limits in display math mode is [here](https://github.com/typst/typst/blob/9b1a2b41f0bb2d62106e029a5a0174dcf07ae0d2/crates/typst-library/src/math/attach.rs#L238). As long as people agree, it should be as simple as adding the equals sign to this list.

I am personally in favor of the default-limits behavior.

**Comment by laurmaedje** [comment]
I'm all for changing this. Does somebody know of a complete list of symbols that should default to limits? (ideally from Unicode or LaTeX)

**Comment by Enivex** [comment]
> I'm all for changing this. Does somebody know of a complete list of symbols that should default to limits? (ideally from Unicode or LaTeX)

I couldn't find any such list. Equal sign does _not_ default to limits in display math in LaTeX, but this is a place where I think typst can afford to be different.

Another example of places where it would make sense to default to limits in display math is with arrows (especially long ones).

**Comment by Enivex** [comment]
> Would defaulting to limits for all relations go too far?

What do you mean by relations?

**Comment by laurmaedje** [comment]
> The unicode classification?

Yes

**Comment by Enivex** [comment]
Is there a list of all of them anywhere? I suspect there are some where limits is inappropriate behavior

**Comment by laurmaedje** [comment]
Not the most easily digestible list, but here it is: https://github.com/typst/unicode-math-class/blob/main/src/classes.rs

**Comment by damaxwell** [comment]
@laurmaedje had asked if there were a list of symbols that should default to limits.  In TeX, `\limits` can only be applied to a character of math class 1, which corresponds to unicode Math class `Large`.  There are about 70 such unicode characters (product, sum, coproduct, wedges, a host of integrals, circled operators, etc.).  The default value in TeX is `\displaylimits` for all such symbols (limits in display size, scripts elsewhere).  There are some exceptional cases where a large operator is defined, but the main access to it is via a macro that includes `\nolimits`.  For example, `\intop` is a class 1 symbol, and `\int` is defined to be `\intop\nolimits`.  I don't know of a list of all such exceptions.

LaTeX (i.e., not TeX)  provides a separate `\stackrel` for putting things on top of relations.  The proposal here is essentially that attachments to relations, by default, act like `\stackrel`. In my mind, any consistent rule that can be undone and customized seems reasonable.  So long as the default is undoable, applying the proposed rule (attchments to relations are via limits) wholesale to relations rather than having a list of exceptions hardcoded in rust seems like a better strategy to me.  A decision needs to be made on `limits(inline:false)`, or `limits(inline:true)`, however.

BTW: the `amsmath` package expands on `\stackrel` and provides `\underset` and `\overset` which  let you put stuff above/below anything else, and `\sideset`, which allows you to add a script and a limit to the same symbol.  All these features are already accessible in Typst's model via `attach`. Cool.

**Comment by laurmaedje** [comment]
So we want to default to limits for `MathClass::Large` and `MathClass::Relation`? If someone wants to do a PR, that'd be great, otherwise I will try looking into it soon-ish.

**Comment by damaxwell** [comment]
Yes, except that integral sign glyphs (which are `Large`) default to scripts as an exception. I'd be happy to put this PR together.

**Comment by laurmaedje** [comment]
That would be great! :)
