### ISSUE TITLE
Numbering of equations does not work correctly

### ISSUE THREAD

**Issue by ai25395** [typst/typst#1768]
### Description

I want to number my equations begining with the number of this chapter.Like this:
![image](https://github.com/typst/typst/assets/52650634/23f2f093-b4bf-480d-abd3-9c55d7070715)
These two ways have produced same results
![image](https://github.com/typst/typst/assets/52650634/a3f3daa3-a73f-4f7f-aa31-d60f8990fde2)
![image](https://github.com/typst/typst/assets/52650634/a563e8b5-ead7-4dfe-a260-1024f5695ade)
![image](https://github.com/typst/typst/assets/52650634/dba18b7b-b657-41a9-a57a-318f103eeab2)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by antonWetzel** [comment]
Maybe a custom numbering function can create the desired outcome:

## Function

```csharp
#set math.equation(numbering: equation => locate(loc => {
	let chapter = counter(heading).at(loc).at(0)
	[(#numbering("1", chapter)  - #numbering("1", equation))]
}))

#show heading.where(level: 1): it => [
	#counter(math.equation).update(0) #it
]
```

## Result

![image](https://github.com/typst/typst/assets/59712243/85826fe5-138f-461a-90cc-785ab630b5ee)

```csharp
#heading(level: 1, "Custom equation label")

We define:
$ phi.alt := (1 + sqrt(5) / 2) $ <ratio>

With @ratio, we get:
$ F_n = floor(1 / sqrt(5) phi.alt^n) $

#heading(level: 1, "Custom equation label 2")

We define:
$ phi.alt := (1 + sqrt(5) / 2) $ <ratio2>

With @ratio2, we get:
$ F_n = floor(1 / sqrt(5) phi.alt^n) $
```

## Explanation

### custom counter
- `set math.equation(numbering: arg => ...)`
  - overwrite the numbering for an equation with a custom function
  - `arg` is the current equation counter as integer
- `locate(loc => ...)`
  - we want the chapter counter at the current position, so query the location
- `let chapter = counter(heading).at(loc).at(0)`
  - get the heading counter at the location and at the first index (offset 0) to get the chapters
- `[(#numbering("1", chapter)  - #numbering("1", equation))]`
  - return content "(", the formatted chapter numbering, " - ", the formatted equation counter and ")"

### reset with new chapter
- `#show heading.where(level: 1): it => [...]`
  - overwrite how a heading where level is 1 is displayed
- `#counter(math.equation).update(0)`
  - reset the equation counter
- `#it`
  - render the original heading
  
## Notes

- if a `#show heaing.where(level: 1): it => ...)` already exists this would overwrite
  - combine both if wanted
- The section is 10 because this is at the end of a test document

**Comment by BeitianMa** [comment]
@antonWetzel There seems to be some problem with references, e.g., when I just change the order of two references:
```typst
#heading(level: 1, "Custom equation label")

We define:
$ phi.alt := (1 + sqrt(5) / 2) $ <ratio>

With @ratio2, we get:
$ F_n = floor(1 / sqrt(5) phi.alt^n) $

#heading(level: 1, "Custom equation label 2")

We define:
$ phi.alt := (1 + sqrt(5) / 2) $ <ratio2>

With @ratio, we get:
$ F_n = floor(1 / sqrt(5) phi.alt^n) $
```

as you see, I just refer `@ratio2` firstly and then `@ratio`, however, the refered formula label does not change accordingly (though clicking will still take you to the correct formula). I think it's probably because the reference label is not just a copy of original numbering, but query current location and count the headings again.

![1706756897633](https://github.com/typst/typst/assets/73782535/fdc8f7df-c249-4d49-bb78-df7b29bd871f)

I have no idea about solving this problem and any help would be welcome~

**Comment by antonWetzel** [comment]
## The Code

```typst
// define how a equation label should look
#let equation-label(heading, equation) = [(#heading - #equation)]

// define the numbering for an equation
// first locate, where we are in the document
#set math.equation(numbering: equation => locate(loc => {
	// get the heading index at the location at offset 0 for heading level 1
	let heading-index = counter(heading).at(loc).at(0)
	// create the label
	equation-label(heading-index, equation)
}))

// overwrite, how a reference is displayed
#show ref: it => {
	// skip if the label has no corresponding element to point at
	if it.element == none {
		return it
	}
	// get the type of the thing the ref points at
	let f = it.element.func()
	if f == math.equation {
		// for an equation do this block

		// a locate is required for a query
		locate(loc => {
			// query the location of the equation the reference points at
			let equation-location = query(it.target, loc).first().location()
			// get the index of the heading at the location of the equation
			let heading-index = counter(heading).at(equation-location).at(0)
			// get the index of the equation
			let equation-index = counter(math.equation).at(equation-location).at(0)
			// create the label with the supplement and the custom look
			it.element.supplement + [ ] + equation-label(heading-index, equation-index)
		})
	} else {
		// for anything else use the default
		it
	}
}

// only works if headings a numbered
#set heading(numbering: "1.")

// reset the equation counter with a new chapter
#show heading.where(level: 1): it => {
	// reset the counter
	counter(math.equation).update(0)
	// display the heading without changes
	it
}

// example code

#heading(level: 1, "Custom equation label")

We define: $ phi.alt := (1 + sqrt(5) / 2) $ <ratio>

With @ratio2, we get: $ F_n = floor(1 / sqrt(5) phi.alt^n) $

#heading(level: 1, "Custom equation label 2")

We define: $ phi.alt := (1 + sqrt(5) / 2) $ <ratio2>

With @ratio, we get: $ F_n = floor(1 / sqrt(5) phi.alt^n) $

```

## Result
![image](https://github.com/typst/typst/assets/59712243/27ccbca9-cc37-4c00-b7ad-976850fe89a4)

## Why this is required

The custom numbering for an equation uses locate to get the current heading. This is fine for the equation, but wrong for a reference, which can be anywhere.

**Comment by YDX-2147483647** [comment]
Sorry to bother you, but this issue is ranked high by search engines, and I hope the following may help others. Really sorry…

---

According to [laurmaedje's answer on Discord](https://discord.com/channels/1054443721975922748/1054443722592497796/1088839394665955378), it can be much simpler.

```typ
#let equation-numbering-rules(body) = {
  show heading: it => it + counter(math.equation).update(())
  set math.equation(numbering: (..nums) => {
    let h = counter(heading).display("1") // Remove the trailing dot
    let eq = nums.pos().map(str).join(".")
    
    [(#h#sym.dash.en#eq)]
  })
   
  body
}
```

![](https://github.com/typst/typst/assets/73375426/15ea521c-6557-4676-8d97-2bc4fec86e75)

```typ
#show: equation-numbering-rules

// Only works if headings are numbered.
#set heading(numbering: "1.")

#set page(width: auto, height: auto)

$ sin x $ <eq:sin>

@eq:sin is the sine function.

= Chapter

$ cos x $

@eq:sin is still the sine function.
```

Update on 2025-07-17: It's now wrapped into the package https://typst.app/universe/package/headcount.
However, `ref` reconstructed by `show ref: it => ….` may not work as expected. See https://github.com/jbirnick/typst-headcount/issues/1, [How to `counter.display_at_loc(…)` or get remote context? - Questions - Typst Forum](https://forum.typst.app/t/how-to-counter-display-at-loc-or-get-remote-context/5096).

Relates-to: #1896, #2652

Other alternatives: https://gist.github.com/YDX-2147483647/4196137b5eaa7779d8ddd114ec5f70fb
