### ISSUE TITLE
Problems of vertical spacing

### ISSUE THREAD

**Issue by ai25395** [typst/typst#1776]
### Description

There are three problems that I have met when I try to write a template.I am using Typst LSP 0.7.1 in vscode.
1：Spacing gets bigger by calling #show() continuously.Is it stateful?
![image](https://github.com/typst/typst/assets/52650634/c9ea18e5-e27e-4231-8d76-7602672776d4)
![image](https://github.com/typst/typst/assets/52650634/e4dde98c-322f-4c02-979b-91b7cd89af89)

2：The codes below generate slightly different spaings,I don't know if it's normal.
![image](https://github.com/typst/typst/assets/52650634/3b49c51f-a197-40b8-8d95-2045e932cb56)
![image](https://github.com/typst/typst/assets/52650634/c566e2c2-2bfd-46c6-a1d7-250909e72c2c)
![image](https://github.com/typst/typst/assets/52650634/e766fbff-69df-41d5-a675-3b7998195b55)

3：Is there a way to control the spaing after a image?The spacing won't change even for different size of images resulting in a bad appearance.I have tried to use #set par(leading: ...) to change it but useless.
![image](https://github.com/typst/typst/assets/52650634/0807396a-c102-49f7-bae7-6683a912c284)
![image](https://github.com/typst/typst/assets/52650634/b12e7848-5493-4512-a6c7-8ab780c1f6c7)

If anyone could provide some suggestions?Thanks.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Julian-Wassmann** [comment]
Hi!

All three points are expected behavior and not bugs.

> 1：Spacing gets bigger by calling #show() continuously.

This is expected because the show rules are applied in a row and respect the previous show rules. If you want the same spacing for all headings, only apply one show rule in the beginning.
However, if you want different spacings after a heading throughout the document, at the moment, you can not reset previous show rules (see: #420). Instead, the best way is to use the vertical spacing function and undo the previous spacing.
```
#show heading.where(level: 1): h => [
  #h
  #v(1em) // let's increase the vertical spacing by 1em
]
= ABSTRACT_1
#lorem(20)

#show heading.where(level: 1): h => [
  #h
  #v(-1em) // undo the previous vertical spacing
  #v(0.5em) // this heading has now the correct vertical spacing
]
= ABSTRACT_2
#lorem(20)
```

> 2：The codes below generate slightly different spacings.

Inside the show rule, you're using the font size of the heading, which is bigger than the normal font size. This is why the vertical spacing is bigger in this case.

> 3：Is there a way to control the spaing after a image?

You can just use a vertical spacing after the image:
```
#show image: i => [
  #i
  #v(1em)
]
```
It doesn't have anything to to with the width parameter. `#set par(leading: ...)` changes the spacing between the lines, which is not useful here.

P.S.: Next time, please provide your code as code blocks, not as screenshots, or provide a Reproduction URL. This makes reproducing the problems faster.

**Comment by ai25395** [comment]
yes,I understand it now .Thank you for the solutions from which I've learned a lot.
