### ISSUE TITLE
Footnotes are not shown when placed in the header

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#1853]
### Description

When `#footnote()` is called from the header of a page, the footnote number appears, but not the footnote itself. It sort of makes sense that footnotes can not be put in the footer (which, in the same style, does not work) but at least for headers it would be good, I think. 

Minimal example:
```typ
#page(header: [Text#footnote[footnotetext]], [])
```

Use case:
With [polylux](https://github.com/andreasKroepelin/polylux), slides titles are shown in the page header. 

### Typst version

- [X] I am using the latest version of Typst

**Comment by KDr2** [comment]
Footnotes in `place` aren't shown either, see:

```
#place(dx:1pt, dy: 1pt, block(inset: 1em)[
  A block in `Place` #footnote[Where am I?].
])
```

**Comment by laurmaedje** [comment]
Footnotes in `place` are shown since #5017.

Footnotes in header/footer are seriously cursed and I'm considering to turn them into a hard error. Fundamentally, footnotes are laid out as part of the inner flow contents and have intricate behaviour to keep things together on the same page. Headers/footers are just very far removed from that. I'm not aware of other software supporting this either.

**Comment by Mc-Zen** [comment]
Yes, I guess that is okay and we can close this issue as not planned. 

I just wanted to add a footnote to a section title and this only became a problem since polylux (or at least the theme I used) puts the section title into the header instead of the main text. There are probably other and better ways to solve the problem.
