### ISSUE TITLE
Primes in sub- and superscript are too eager.

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#1908]
### Description

The following markup `$a_(1)'$` produces the very unexpected result of keeping both the parentheses and the prime inside the subscript, rather than what I would've expected which would be placing the prime outside the subscript.
Current behaviour:
![letter 'a' with a subscript containing both the number one in parentheses and a 'prime' symbol](https://github.com/typst/typst/assets/40892795/c4fa7b5e-6acb-4dbc-879c-6ca735060db4)
There is definitely a discussion to be had regarding whether the prime should be connected to the `a`, or be 'floating', placed horizontally after the subscript; we already have syntax to achieve either with `a'_1` or `a_1 '`, respectively.

A slightly different, but related issue is `a_'`, producing the rather curious output of:
![letter 'a' with both a regular prime symbol and a prime symbol of normal proportions; except it appears in the position of a subscript, rather than the usual superscript](https://github.com/typst/typst/assets/40892795/ad421565-f43a-4e83-b827-4e48cc9b50e9)
I don't know what this should result in, perhaps even a syntax error.

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by sitandr** [comment]
We had that discussion in my PR (https://github.com/typst/typst/pull/1614), it wasn't an easy one. After all, we decided to deviate from LaTeX behaviour to make the writing *more compact*. So the order you write things now matters. To attach prime to the main part, you _have to_ write it near it. That makes souce code to be easier to read and closer to the output.

Primes don't remove brackets, because if you want to write something complex without them, you can use $a_(something strange')$ that will wield the same result. Usually if you write these parentheses, you _want_ them, so Typst doesn't remove them.

And $a_'$ is definitely a bug to be fixed, thanks. Currently you can bypass it using $a_(')$.
