### ISSUE TITLE
Aligning superscript and subscript

### ISSUE THREAD

**Issue by awav** [typst/typst#1925]
### Description

Hello,

It appears that there is an issue with how subscripts and superscripts are aligned when using alias commands. In my case, I created an alias `inverse` to represent `^(-1)`. When I apply this alias directly to a subscripted element, it seems to disrupt the alignment of the superscripts and subscripts in a manner that was not expected.

Using this alias `inverse` in conjunction with subscripts results in Equation 1 in the attached screenshot, which is inconsistent with how I would expect the rendered notation to appear. The expected outcome is depicted as Equation 2 in the screenshot, the superscript should be neatly aligned above the subscript.

<img width="90" alt="Screenshot 2023-08-13 at 11 04 25" src="https://github.com/typst/typst/assets/24483645/c4a61af6-b62a-4112-aead-a66ebe24ff91">

### Reproduction URL

https://typst.app/project/r2Pkv_mQK1y1jlIEK22I_o

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is not a bug. This is the difference between a^b_c and (a^b)_c. You'll have to apply the subscript inside the function, ie `inverse(a_c)` and handle the case where the input already has attachments there.

**Comment by sitandr** [comment]
To be able to attach both sub- and super- scripts without extra spaces, one has to add them simultaneously, in the same element. Otherwise, like in your example, inner will be turned into `Frame` and outer will be attached to the whole frame.

There are certain hacks that can allow you to achieve this effect, like using place, measuring and `h`, but they are quite dirty. Currently this is a limitation of the math layouting system.

I'm not sure this is a real issue. After all, you can add argument for the superscripts in your function as well.

**Comment by awav** [comment]
@Enivex, @sitandr Thanks! Can you give a recipe for handling this situation? I.e. I have aliases like:

```
#let Kxx = $upright(K)_(x x)$
#let inv(x) = $#x^(-1)$
```

How would I implement the alignment. In LaTeX this is no brainer.

**Comment by Enivex** [comment]
> @Enivex, @sitandr Thanks! Can you give a recipe for handling this situation? I.e. I have aliases like:
> 
> ```
> #let Kxx = $upright(K)_(x x)$
> #let inv(x) = $#x^(-1)$
> ```
> 
> How would I implement the alignment. In LaTeX this is no brainer. 

I suggest you ask in the Discord. They're usually quite helpful 🙂
