### ISSUE TITLE
Rendering of R source code block

### ISSUE THREAD

**Issue by aksigkvgithub** [typst/typst#1978]
### Description

At present Typst provides markdown type source code block.

So, I put some R codes for computation, and for creating a plot, in such as source block such as,

```r 
{R codes}
```
First I rendered typst file into "knitr" package  of R, then compiled that file into Typst.

I found that the ultimate rendered file by Typst contained the numerical computation rendered by R well formatted,, but it did not fetch the plot rendered by R created by it in a subdirectory. That is, despite the plot being in the /figure subdirectory Typst did not fetch the plot into the pdf during compilation.

Therefore, I request that this feature be added, so that R users can use Typst like they use Rmarkdown.

Thanks and regards,

Dr. A.K. Singh

### Use Case

R users can use Typst like they use Rmarkdown for their reproducible research and documentation.

**Comment by laurmaedje** [comment]
I am not familiar with R, but adding another syntax for source blocks is not something I'd like to do, in particular if the syntax is `{R code}` because it is very close to Typst code blocks.

**Comment by aksigkvgithub** [comment]
No. No. There is some misunderstanding.. What I meant by {R codes} is to say the sets R codes, and nothing else. It is not any R syntax.

Even in the present format of a Typst file, the R codes within the following block,

```r

```

is being rendered by R's knitr package within the same block and also generates a Markdown like reference for the figures created by R in the subdirectory /figure, with respect to the current working directory.

Afterwards, when this R's rendered typst file is compiled by 'typst compile ' command, all typst contents as well as R's generated computations and data come out well formatted in pdf export.

The only missing thing is that, the plot that was required to be fetched based on the Markdown type reference link, created by knitr package of R. That is the plot is not being fetched into pdf during Typst compilation, despite that the figure is present in the /figure subdirectory. 

So, what is only required by Typst compiler is to fetch the plot into pdf at the location of Markdown type link already created by R's knitr package.

That's all to be done by Typst. That is, to recognise the Markdown type reference link created within the block, and based on that fetch the plot there into the pdf during Typst file compilation.

And this will be useful to all R users.

**Comment by aksigkvgithub** [comment]
No. No. There is some misunderstanding.. What I meant by {R codes} is to say the sets R codes, and nothing else. It is not any R syntax.

Even in the present format of a Typst file, the R codes within the following block,

```r
some R code 
```

is being rendered by R's knitr package within the same block and also generates a Markdown like reference for the figures created by R in the subdirectory /figure, with respect to the current working directory.

Afterwards, when this R's rendered typst file is compiled by 'typst compile ' command, all typst contents as well as R's generated computations and data come out well formatted in pdf export.

The only missing thing is that, the plot that was required to be fetched based on the Markdown type reference link, created by knitr package of R. That is the plot is not being fetched into pdf during Typst compilation, despite that the figure is present in the /figure subdirectory.

So, what is only required by Typst compiler is to fetch the plot into pdf at the location of Markdown type link already created by R's knitr package.

That's all to be done by Typst. That is, to recognise the Markdown type reference link created within the block, and based on that fetch the plot there into the pdf during Typst file compilation.

And this will be useful to all R users.



Leave a comment

**Comment by ondohotola** [comment]
/figure would be in the root directory.

For the ones not using `R` much, `knitr` allows to put _chunks_ of `R` code into (for example) LaTeX code and then if `shell escape` is enabled a LaTeX run would run `R` on those code _chunks_ putting their output into the generated PDF. This is very powerful

Running `knitr` with `typst` is unnecessarily complicated because you can write a `Makefile` with corresponding dependencies, running the `R` scripts generating the images in the working directory.

But I would love to see a (small) example of this with a workflow.

**Comment by aksigkvgithub** [comment]
Ok. I will create a short workflow example and paste here. 

Thanks for considering.

Regards

Dr. A. K. Singh

**Comment by aksigkvgithub** [comment]
This post in response to the developer [ondohotola](https://github.com/ondohotola). I am trying to depict the workflow with few pics that would follow in sequence below:

1. First I created a typst file named "2. ANCOVA in CRD.r.typ" and included into it some R codes in RMarkdown block. Its screenshot from Sublime Text Editor is given below:

![1  typst-with-r-codes](https://github.com/typst/typst/assets/34943246/83ca7ef1-fe44-42a2-9a27-2465de32ad2f)

2. At second stage, I rendered this file at R console, whose screenshot is given below:

![2  typst-with-r-codes-being-rendered-on-R-console](https://github.com/typst/typst/assets/34943246/82ca22c2-9603-45ef-a641-59392b940520)

3. This is how the typst file look after R codes are rendered:

![3  typst-file-look-after-r-codes-rendered](https://github.com/typst/typst/assets/34943246/24dbc8bc-1fd9-4088-87a6-c7c2a5fc0eaa)

4. This screenshot shows how I compiled the typst file after rendering in R was completed, and new file created by name "2. ANCOVA in CRD.typ" . Note that the new file does not have ".r." in it:

![4  typst-file-with-r-codes-rendered-being-compiled-in-typst](https://github.com/typst/typst/assets/34943246/bad6edd9-ea66-4a9c-bfb0-503b8c4a66a8)


5. Note that in the 4th step a new /figure subdirectory was created by R, into which the file "unnamed-chunk-1-1.png"  has also been created by R and its reference "![plot of chunk unnamed-chunk-1](figure/unnamed-chunk-1-1.png)" is given in the R-rendered file "2. ANCOVA in CRD.typ". Following screenshot is of the plot created by R in /figure subdirectory:

![5  R-created-plot-in-figure](https://github.com/typst/typst/assets/34943246/0165ec5f-a376-463d-92d7-2e8be8b009c8)

6. Following screen shot is the screenshot of pdf file created by typst after compiling the R rendered file "2. ANCOVA in CRD.typ".

![6  Final pdf- typst compiled file with R-output-missing-plot](https://github.com/typst/typst/assets/34943246/3d89cbd2-697a-4d7f-9059-23f7da23736e)

7. You can see that everything is done except that the plot is not being fetched into pdf, which I requested that to be fetched by typst. That is all my request is.

Thanks and regards.

Dr. A.K. Singh

**Comment by laurmaedje** [comment]
Ok so, looks like RMarkdown generates Markdown-compatible output with `![...](...)` image syntax and that syntax is not support by Typst because the way to do it is the `image` function. You'd have instruct RMarkdown to generate a call to the `image` function.

**Comment by laurmaedje** [comment]
Note that Typst is not a superset of Markdown, so it's more of a coincidence that it almost works.

**Comment by ondohotola** [comment]
screenshots don't help, as one can't copy & paste which makes it next to impossible to reproduce.

**Comment by ondohotola** [comment]
pasting screenshots is not helpful at all as it is almost impossible to reproduce.

**Comment by aksigkvgithub** [comment]
Ok. I shall submit below the  files created and obtained in the process, sequentially to make workflow clrear:

1. Please create a folder, say, named  as "Analysis of Covariance".

2. Within this folder, please keep the following file, after donloading:

[2. ANCOVA in CRD.r.txt](https://github.com/typst/typst/files/12430296/2.ANCOVA.in.CRD.r.txt)

3. After downloading this .txt file, please rename it to .typ format, to make it a typst file. This file contains a small typst document with some R codes in a Rmarkdown block format. And this code block uses following data file. Please downlaod that file too:

[Leprosy.txt](https://github.com/typst/typst/files/12430329/Leprosy.txt)

4. After downloading this data file, please rename this .txt file to .csv format, as it comtains comma separated data, which the R codes from within its block, will read. And please keep this data file too in the same "Analysis of Covariance" folder, after renaming to .csv format.

5. Then open R console, of course, that will require installation of R for sometime, which is open source and can be downloaded from CRAN repository. And on the R console, please make it sure to install "knitr" package, which may require installation of some other dependable packages, which generally R installs automatically mostly. But sometimes, when it cannot, then it indicates in its messages to install them first, then "knitr" will be installed.

6. After successful intallation of "knitr" package, please run the following command, which will verify whether "knitr" has been successfully installed or not:

              library(knitr)

7. If package "knitr" is successfully installed, it will simply load that library and show the R prompt. Otherwise it will throw some error message.

9.  Now, on the R console, please run the following command, which uses "knitr" package:

       knitr::knit("2. ANCOVA in CRD.r.typ","2. ANCOVA in CRD.typ")

10. Then R will read the data from "leprosy.csv" file and create some output within Markdown type of blocks format as per the instructions of R codes present in the file "2. ANCOVA in CRD.r.typ" and finally create another typst file "2. ANCOVA in CRD.typ" as per instruction given on R console. I am giving that file below, which was created by R in the .txt format as follows:

[2. ANCOVA in CRD.txt](https://github.com/typst/typst/files/12430461/2.ANCOVA.in.CRD.txt)

11. Please download this file and rename it from .txt format to .typ format to make it typst file too.

12. Finally, please compile this file named file "2. ANCOVA in CRD.typ" into typst.

13. The pdf file that is exported by typst is as follows:

[2. ANCOVA in CRD.pdf](https://github.com/typst/typst/files/12430484/2.ANCOVA.in.CRD.pdf)

14. In this file all the R output come out in a clean format. But, the plot is missing despite the plot reference,
      ![plot of chunk unnamed-chunk-1](figure/unnamed-chunk-1-1.png)
is present in the "2. ANCOVA in CRD.typ" file. The plot is created by R in the /figure subdirectory, and at the same time it creates the reference as indicated above. The plot which is created in the subdirectory is as follows:

![unnamed-chunk-1-1](https://github.com/typst/typst/assets/34943246/04fc0214-213c-4967-adea-bbd40a3b9d20)

15. My request is that everything is already supported by typst, except that it is to be made to enable the feature of fetching the plot too, that are being referenced by R in the Markdown type of image referencing syntax. If this referencing feature is enabled in the typst, then this will be sufficient for the R users. Rest of the things would be handled by "knitr" package.

16. In the comments above somebody indicated to use Rmarkdown package. I will say No to it, because Rmarkdown reads R codes as well as Markdown syntaxes, whereas here, we have typst file format. So, such kind of task can be handled through "knitr" package.

17. One of the other developer indicated the use of LATEX features in between the workflow process. For that I cannot say much, except that I know that LATEX workflow is a reality. But, I do not know its details.

For any other queries please ask me further. So, again I request you to consider this small thing, which will enable the reach of typst to R users too.


Thanks and regards,

Dr. A.K. Singh

**Comment by laurmaedje** [comment]
I do not want to add support for Markdown image syntax to Typst. Typst intentionally reduces the set of things done with markup as opposed to functions. It also don't think Markdown's image syntax fits well with Typst's general syntax. The fact that images are sometimes, but not always, figures further reduces the usefulness of such a syntax.

If you can't configure the output of knitr, maybe you could write a simple regex-based script that you run after knitr, which transforms Markdown-style images into Typst-style images. In any case, the solution is to change some step of your conversion step rather than changing Typst.

**Comment by aksigkvgithub** [comment]
Very disappointing. on your statement, "I do not **want** to add support for Markdown image syntax". You have taken Markdown syntax for your source code block. But, you will not support its image referencing.

You have taken Asciidoc syntax for heading and have put behind it your heading function. There are so many instances.

Since you don't want, it can't be done at all. If somebody doesn't want, it can't be forced upon. It seems that you are the final decision maker, and not the team.

Your one of the developers wanted to see the workflow. I took twice the pains to create the workflow. But, when I did that, you have taken a stand that you don't want.

It means that everything in typst is not on the merits of the feature request, but on your wishes.

I can't do anything but to leave typst. But, I am one of those R users who at least tried typst. Not many users experiment so much,

You are not rejecting my request, but rejecting a whole lot of R users, who are quite a lot too many. You are are rejecting them at the initial stage of typst.

If such wishes are dominant on this forum, it is destined to die it's own death. There are so many other markup languages who died in their scope, because they don't have users.

And you are rejecting users of such a popular language as R having a very large user base.

Good luck. Quitting typst.


Thanks and regards,

Dr. A. K. Singh

**Comment by frozolotl** [comment]
As I understand it, you, @aksigkvgithub, want to use knitr to run R code embedded in typst source files and then generate a document with the results.
Your workflow appears to rely on the fact that code blocks especially have similar syntax to RMarkdown.
As such, knitr reads a file, thinking it is a Markdown file, and then generates Markdown code.
Some aspects of that only work out of mere chance.

Typst does not try to replicate the syntax from any other markup or programming language. It is its own thing.
The fact that raw blocks in typst use a similar (but not the same!) syntax as in Markdown is not a decision driven by increasing compatibility between tools.
The decision was taken because that syntax is familiar, and most importantly, good syntax.

In my opinion, Markdown's syntax for including links and embed images is hard to remember and not that readable. I have forgotten the order of brackets and parentheses in the past, multiple times.
The syntax does not easily integrate itself into typst's way of creating figures.

The decision to not support Markdown's image inclusion syntax was not taken in a whim.
Neither was it taken to annoy current R users.
It is simply not a good fit for typst itself.

There could be alternative solutions that fit better into the typst ecosystem, however:
+ Knitr supports typst input and output. This should work decently enough for simple documents. Your workflow would stay largely the same.
  A problem with that approach might be that typst's scripting support would not be compatible with that.

+ Using the recently added WASM plugin support, someone develops a plugin that looks for R expressions, runs them and returns the results.
  This would have two major benefits:
  - Typst's scripting language would be well-integrated. This could have some major benefits for layouting the evaluation results.
  - The workflow would be your typical typst workflow as it is right now. The document could be compiled simply by running `typst compile`. And you could also write the document and evaluate the R results in the web application.
  Sadly, it does have its drawbacks:
  - R code would be sandboxed, as typst code is right now.
  - For `typst watch` and typst's live preview, long-term (meaning, between runs) caching might be required. Otherwise, long-running R programs might decrease the editing experience a lot.
  - It is probably quite a bit of work to write a WASM plugin that integrates knitr and R.

+ The last solution I have would be to not use R within typst. Ideally, typst's scripting language should support the things you would embed R code for.
  This solution would require people to rebuild R packages in typst, and it would require you to change your workflow in some ways.

I have described some problems with the approach you have suggested so far and proposed alternative ways of solving the issue.

I don't like to end this comment this way, but I think it has to be said.
In my opinion, your comment was harsher than it deserved to be.
@laurmaedje stated some of his reasoning behind closing the issue in a comment. I believe he was respectful in his writing. He also suggested an alternative solution.
If you disagree with that decision, constructively write _why_ you do so. Do not make the comment personal and do not invoke inflammatory language.
Only that will incite support for the feature change.

**Comment by aksigkvgithub** [comment]
Thanks for your kind words, @frozolotl. Frankly speaking, I was hurt by the declaration of @laurmaedje, that he does not "want". I got disappointed that if a large chunk of users cannot be given importance for such a small feature that I requested on behalf of R users, what is the use of being here.

Still you have spoken very kind words. I am thankful for that, and feel sorry for whatever followed. and express the same to you, to @laurmaedje and to anybody else on Typst who didn't feel good for all this.

Now, back on the topic. You have suggested various workaround solutions. But, none of them works for me, because it is beyond my capacity to create a WASM plugin of R to be used in Typst. And if it is already present, I could not find it on net, nor do I know how to use it, if it is available somewhere. Moreover, you have yourself expressed its limitations that it sandboxes the codes. Moreover, it is not possible to ask knitr developer to include Typst type of image referencing. I had tried that in case of Asciidoctor type of source code block support. They said if R users would largely ask for that they would that. But, then Asciidoctor obliged.

I am a simple Professor of Statistics, and teach my students the same using R codes. I have written 2 books on Statistical aspects using R. One in Rmarkdown, which ultimately I disliked because of the difficulties I faced in formatting the book. 

The second I wrote in Asciidoctor. There also I found a similar problem as in Typst. Then I had raised that issue there. And they had very kindly created a separate kind of R code blocks in Asciidoc and they were already supporting Markdown type of image referencing behind the curtain, although they had their different image referencing syntax. I rendered my book in HTML and Docbook but could not do the same in pdf, because they have some serious drawback issues with pdf rendering, especially with respect to math codes. It was Docbook because of which my book could be published, with some difficulty.

The third book I have started with Lyx. By this time I came to know about Typst. I tried to write an article in Typst. I liked its pdf rendering, and also that it already had Markdown type of source code block type. So I wrote some of my R codes into it and rendered the same with the workflow I have described above. Everything worked well, except its image rendering. Then I was disappointed with Typst, and kept away from it for a few months.

Then, suddenly one day, an idea dawned on me that the help pages of Typst say that they have some of their markup syntax, which are very familiar, but have kept the respective Typst functions behind such markups. So, I thought that if that is so, a small feature of supporting from behind, not popularizing, the markdown type of image referencing would not be a big deal for Typst, **although they may keep their image referencing function behind that**, as it already supports the markdown type of source code blocks, may that be by chance.

Thinking these, I raised my feature request. At present it is my request. But, in future, it would ultimately affect a large R user group as and when they start coming to know about it. They generally follow two workflows. One is Rmarkdown, which I think is the worst in most of its advanced syntax. So, it is not good for books and large articles. The other is LATEX one, which is very good but difficult.

Thus, not to repeat what followed so far. I again express my "sorry" to anybody who did not feel good about everything.

And if Typst could fulfill the feature request raised on behalf of R users, I would come back to Typst, and tell about it to my students too. Otherwise with no other option for R users on Typst, I would have to fallback on Lyx.

Thanks and regards,

Dr. A.K. Singh

**Comment by frozolotl** [comment]
> Moreover, it is not possible to ask knitr developer to include Typst type of image referencing. I had tried that in case of Asciidoctor type of source code block support. They said if R users would largely ask for that they would that. But, then Asciidoctor obliged.

Even so, would suggest creating an issue on knitr's repository. It might be that the maintainer would see it differently for typst.
If they are not willing to do that, such an issue could at least give the community a place to express support for such a feature. It might also increase the chances that someone implements the feature after coming across the request.

**Comment by sitandr** [comment]
I'm sure there is a way to fix yours workflow, and that wouldn't be that hard. Of course, it would be more convenient if it would "just work" without additional steps, but there are real reasons to avoid that `![name](path)` syntax. And to add that support specially for post-processing `R` code... Isn't a good way either. Typst tries to have a very thoughtful design, and it has quite different purposes. It currently has tons of vital things to make working (like better citations, HTML export and so on). I hope for your understanding.

Now, returning to possible changes to yours workflow. I'm not an expert, but I think that may be helpful for you.

1. If figures are the only your current concern, you can add extra step in building of replacing that `![name](path)` with Typst's `#figure(caption: "name", image("path"))`. The simplest way to do is using _regular expressions_ (that was a way @laurmaedje initially suggested). This is just a string that describes what pattern you want to find and how to use it's parts for replacement. I'm not familiar with R ecosystem, however, I'm sure there should be a built-in R way. Anyway, there is plenty of tools to do that from command line (and it looks that you can call it from `.R`). It should be as something like `!\[(.*)\]\((.*)\)` for pattern, `#figure(caption: "$1", image("$2"))` for replacement, and some R command to apply them to your file. If you need help there, feel free to ask, I'm sure the community will help, it isn't hard (but better on Discord, if it is possible for you, Github is more for actual issues).
2. _ In future_, it will likely become possible to _add custom syntaxes_ using Typst's `show` rules and same regular expressions. Currently they are limited, as using special symbols and replacement groups is a bit problematic, but that will be eventually fixed! So you will be able to add some `show` rule at start of your file and all of this will "just work" without any additional steps. Unfortunately, I can't give any time estimates for that, but it shouldn't take long.
3. If just replacing figures isn't enough for you, you can use a wonderful library `pandoc` that can export in almost any needed format, including Typst (as I know, **R** often uses it for exporting and has native support for it). The tricky thing there will be to get all R blocks from Typst (using new Typst command for extraction called `query`, you can read more in docs), evaluate their output with Knitr, then convert evaluated markdown with Pandoc to Typst, and, finally, insert it back to Typst. Of course, it will be a bit tricky, but it will be much more _universal, cleaner and easier way_, than adding that syntax to Typst itself. Again, community can help you there, if you are sure you need it. Otherwise, the aforementioned ways will be much easier. 

_P.S._ Just to be cleaner: the only true developer there is @laurmaedje . He is the person who developed Typst compiler almost all by himself. All others there are just part of Typst community. We just made tiny contributions to Typst to help it develop as an open-source project. All the changes were thoroughly checked by @laurmaedje . When he says he doesn't "want" it, he means he currently doesn't see the real reasons to work on that feature now. It is kind of common open-source slang, so everyone was a bit upset when you was offended that much. Of course, laurmaedje would properly consider that feature, if the community would disagree with his decision, but in this case it is really not a good way for language to go. Again, I hope for your understanding.

**Comment by laurmaedje** [comment]
Many good points have already been made by now. I just wanted to add that I should have phrased things differently. The reason for closing this feature request was not that I don't _want_ this feature personally, but that I do not think it is changing Typst for the better if we adopt Markdown's image syntax. It is true that I picked aspects of Markdown and AsciiDoc for Typst, but only those that I believe fit well together. The image syntax does not fit well, in my opinion, for the reasons stated earlier.

With this decision, I meant absolutely no disrespect to you or the R community. I just think that in this particular case, it is best to adapt the workflow rather than changing Typst. There are multiple options (converting Markdown-like images to Typst figures via regular expressions, adding Typst support to knitr, etc.) that have kindly been explained by @frozolotl and @sitandr. As others have already said, we, as a community, are happy to help with setting up a good workflow.

**Comment by aksigkvgithub** [comment]
> In future, it will likely become possible to add custom syntaxes using Typst's show rules and same regular expressions. Currently they are limited, as using special symbols and replacement groups is a bit problematic, but that will be eventually fixed! So you will be able to add some show rule at start of your file and all of this will "just work" without any additional steps. Unfortunately, I can't give any time estimates for that, but it shouldn't take long.

Ok. I shall wait for such a show rules. Then I will ask you, how to do that. Other workflows suggested above do not seem to be clean enough to me as per the experience I have so far, although I will try them.

Thanks and regards,

Dr. A. K. Singh

**Comment by ondohotola** [comment]
My 2 cents, this could be an opportunity to bring `typst` near to a large user base, using `R` who are like Dr Singh and myself fed up with the speed (lack thereof) and complexity of `LaTeX` but current lack of viable alternatives within the `R` environment.

If someone could come up with a `show` rule  to make `knitr` happen, I for one would probably stop using `LaTeX` for some (recurring) reports I generate.

**Comment by aksigkvgithub** [comment]
> My 2 cents, this could be an opportunity to bring typst near to a large user base, using R who are like Dr Singh and myself fed up with the speed (lack thereof) and complexity of LaTeX but current lack of viable alternatives within the R environment.

If someone could come up with a show rule to make knitr happen, I for one would probably stop using LaTeX for some (recurring) reports I generate. Currently I use Makefiles which become needlessly complex.

May your message go home to Typst developers.

With regards,

Dr. A. K. Singh

**Comment by aksigkvgithub** [comment]
> My 2 cents, this could be an opportunity to bring typst near to a large user base, using R who are like Dr Singh and myself fed up with the speed (lack thereof) and complexity of LaTeX but current lack of viable alternatives within the R environment.

> If someone could come up with a show rule to make knitr happen, I for one would probably stop using LaTeX for some (recurring) reports I generate. Currently I use Makefiles which become needlessly complex.

Above message was a mistake. Please read as follows:


May your message go home to Typst developers.

With regards,

Dr. A. K. Singh

**Comment by ondohotola** [comment]
much more helpful would be, to try, until the show rule is developed, to
make the knitr chunks now producing graphics ONLY write to SVG images
but NOT produce anthing into the typst document (something like

	echo=FALSE, message=FALSE, results="hide"

comes to mind), and put corresponding #image commands into the typst
file.

Haven't tried it, but that should work.

**Comment by aksigkvgithub** [comment]
> echo=FALSE, message=FALSE, results="hide"

I got your point. I have not tried this. But, assuming that `knitr` creates the graph in /figure subdirectory with this option. In that case we would have to pick and choose manualy each graph in place by #image function of Typst. For one image it may be ok. But for lots R figures it is not practical.

On the other hand if `knitr` does not render the graphs at all within the R code chunk due to results="hide" option, it would be even more fruitless.

So, the only idea, I think, that is workable, is either typst supports Markdown type image referencing for R code chunks I particular, apart from keeping their image referencing as usual,  just like Asciidocdor does.

Or,

`knitr` provides Typst type image referencing.

By the way I have raised an issue to this effect at knitr GitHub too. But so far no outcome to be reported. But at least they have not closed the issue like here 

With regards ,.

Dr. A. K. Singh

**Comment by ondohotola** [comment]
Actually,

since yoy to write and include the chunks already, it’ll only a little more work.

**Comment by aksigkvgithub** [comment]
Agreed. But that would be awfully frustrating. For example  the following code chunk 

```r
ex.lm=lm(y ~ x, data=data)
plot (ex.plot)
```
creates 4 plots together automatically. `knitr` manages them to be on same page or different pages, depending on more options of `knitr`

So, an R user who writes extensive articles using R codes can not handle it if plots are NOT automatically supported to be picked up by `knitr`. Otherwise, manually it is frustrating, and in that case, better to leave Typst at all.

With regards,

Dr. A. K. Singh

**Comment by aksigkvgithub** [comment]
> You are starting to become annoying.

I am sorry if you felt like that. But, I didn't mean that. 

I was trying to explain the possibility with `knitr`, because in an article or book, `knitr` is the only way to add R codes into a document for a reproducible research article etc.

Even if you use tidyverse and create plots first and then pick and choose each one of them from typst syntax, this is the point where I meant that it will increase our time for each code chunk frustratingly very much. Hence, I meant that it is not practical.

If other than this, you have something else in your mind, please let me know the workflow, so that I understand what have you in mind.

With regards,

Dr. A. K. Singh

**Comment by ondohotola** [comment]
No, it doesn't.

You have to write the chunks (one per plot) anyway, so adding a line or
two for each plot to the typst document (after each plot chunk) does not
increase the workload.  At least not mine.

But I think we should not continue this particular debate, until someone
has written the show rule :-)-O
