### ISSUE TITLE
Add `datetime.now`

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#1988]
### Description

Would work as `datetime.today`, but also adding the local OS time at time of compilation.

### Use Case

My specific use case is really that I want my documents to render in dark mode if I'm editing them at night, but really this should be added for consistency and extensibility; I don't see a reason why this shouldn't be part of Typst besides "bloat". But it's not something a package can add by itself, so I think this change *is* worth it.

Also at the very least `hour:minute` could be desirable in a letter etc.

**Comment by emilyyyylime** [comment]
Also [Good first issue](https://github.com/typst/typst/labels/good%20first%20issue)

**Comment by LaurenzV** [comment]
This feature has already been suggested a couple of times, but it probably won't happen, see [here](https://github.com/typst/typst/pull/1843#issuecomment-1660692106) for more information.

**Comment by MrPixelized** [comment]
Having the build time of the document available might somehow feel problematic for live preview, but there are plenty of use cases. Here's some that I've encountered personally:

- I generate a document based on RSS feeds and weather data regularly. A timestamp for these documents would be helpful, as well as the ability to position the sun in the overview based on the current time using CeTZ.
- I have a typst document I'm working on in Git. On push, it gets built. Including the timestamp for those builds would be nice.
- An organization I'm involved with sends people automatically-generated old-school letters that would benefit from a rough timestamp.
- I use typst to generate figures based on data that changes over time. Having a "status of the information at [timestamp]" line would be nice.
- There is a LaTeX template at my university which includes the compilation time on the front page. Using typst to submit homework would be allowed only if the template can be faithfully recreated.

All of these can be achieved in other ways, such as changing the data that comes in, manually editing things, or asking people to check out metadata instead of document content. Nevertheless, a `datetime.build_time()` or `datetime.now()` object would be very helpful for these and plenty of other use cases.

**Comment by laurmaedje** [comment]
I feel like it is okay if there's some friction in getting the current time. Otherwise, people will start abusing it for things like randomness and it will hurt compilation. If you're generating RSS feeds, you're likely in the CLI and it's quite easy to just provide an `--input` then than you can consume via `sys.inputs`.

**Comment by MrPixelized** [comment]
A student who wants a "finished the assignment at: {}" line defaulting to the last time the document was compiled can't always be expected to be messing around with command line arguments right? What about the web editor?

**Comment by jgclark** [comment]
> I feel like it is okay if there's some friction in getting the current time. Otherwise, people will start abusing it for things like randomness and it will hurt compilation. If you're generating RSS feeds, you're likely in the CLI and it's quite easy to just provide an `--input` then than you can consume via `sys.inputs`.

Your 'easy' isn't the same for all users.  It would be helpful to spell this out in the manual as a workaround.

**Comment by woerndl** [comment]
I just want to add that I ended up in this issue for the exact same reason as OP. To be honest when I was looking for the feature I just tried .now() with datetime by intuition and then wanted to check how it is really done, not expecting it isn't possible at all.

I wanted to switch my generated PDF to a dark mode after 8pm because it is highly distracting when you have a big white area on the screen when everything else is dark. And I use versioning so manually switching a variable creates additional hassle.

I think the feature would also be useful for time calculations up until now. And of course time stamps/versioning of the compiled endresults be it ePUBs in the future or PDFs now. Not only for coursework etc. but also if one wants to create stamped PDFs for individual users or similar cases where on-the-fly document generation happens. Think electronic invoices… ZUGFeRDs standard has time stamps in jjjj-mm-ttThh:mm:ss format. Of course you could set it to 00:00:00, but there certainly are real world use cases.

The corresponding tex [question on stackexchange has 83k](https://tex.stackexchange.com/questions/994/how-can-i-typeset-the-date-time-at-compile-time) views and +100 upvotes. So this is certainly a thing for a significant chunk of people.

**Comment by mkpoli** [comment]
For those who want to know how exactly to print current time in Typst (0.12.0) by using `sys.inputs`:

Write and save the following code with the name of `time.typ` or anything you like.
```typst filename="time.typ"
#let get-now() = {
  let now-str = if "now" in sys.inputs {
    sys.inputs.now
  } else {
    datetime.today().display("[year] [month] [day]") + " 00 00 00"
  }
  let (year, month, day, hour, minute, second) = now-str.split(" ").map(int)
  datetime(year: year, month: month, day: day, hour: hour, minute: minute, second: second)
}

#get-now()
```

The above code, in preview mode will yield placeholder time without erroring:
```typst
datetime(
    year: 2024,
    month: 11,
    day: 10,
    hour: 0,
    minute: 0,
    seconds: 0
)
```

When compiled with `typst compile time.typ --font-path fonts/ --input "now=$(date '+%Y %m %d %H %M %S')"` in a Unix shell, such as bash, zsh or fish, it will yield the following time of compilation

```typst
datetime(
    year: 2024,
    month: 11,
    day: 10,
    hour: 16,
    minute: 20,
    seconds: 20
)
```

**Comment by woerndl** [comment]
Thanks for sharing this. While implementing a less elegant, similar solution, I noticed some downsides of the CLI approach that remain:

- This works well for `compile`, but not for `watch`, as input remains on what it was set on call of the command. So now doesn't remain now in this case
- Can't be used in any environment where you don't use CLI (think web app for example)
- It doesn't work with Tinymist as the is currently no way to set sys.input programatically, just as a global setting. And even if there was a way, it would likely lead to the same problem that `watch` has

So I get the "this should be hard" in part as it could affect rendering times and is not as trivial as it might seem at first thought, but I think it would be worth staying on the map in the long run.

PS: Your work around is very well implemented; I just wanted to add my experiences with it. So again: Thanks for sharing, it helped me to optimize my own take on it 😊

**Comment by drnw** [comment]
I read with interest this issue and find it disappointing that the feature is being tagged as "not planned".

For context, I came to Typst via Jupyter Books which I stumbled upon four days ago. I had hacked away at a LaTeX template and was glad to include the build date and time in the PDF output using `\DTMnow` from the `datetime2` package.

I then had the bright idea of trying out Typst. After all it was created because LaTeX was a hassle to use. 

The porting of the template went OK in the first hour. I was 95% complete then I discovered that `datetime.today()` only returns the current date :-( It was even more disappointing to learn that `datetime.now()` is "being left out on purpose" !

Unfortunately, it seems to me that the `sys.inputs` workaround above won't cut it in Jupyter Books. Therefore, after many hours of reading forums, issue trackers, documentation and code, I have an inelegant solution:

1) Create `datetime.mjs`, a JavaScript plugin for MyST which provides a role `dt` that takes a Moment format string as input and gives the current date time back in that format. Add the plugin to `myst.yml`
2) Insert an instance of the role into a fenced off `footer` part in `document.md` e.g. ``{dt}`Do MMMM YYYY, h:mm:ss` ``
3) Declare arguments in the Typst files `main.typ` and `template.typ` for grabbing the part.
4) Typeset the part. In my case, I put it into the page footer.

Is there a better way ?

**Comment by andy-preston** [comment]
I'm just evaluating Typst as a Latex replacement... it's a bit sad that I'm only on the second line of my document and Typst has already "failed" and I'm already abandoning it to go back to Latex.

**Comment by jgclark** [comment]
>
> I'm just evaluating Typst as a Latex replacement... it's a bit sad that
> I'm only on the second line of my document and Typst has already "failed"
> and I'm already abandoning it to go back to Latex.
>
Sad indeed Andy, but thanks for taking the time to give this feedback.
Hopefully you can try again in a year and find this support has been added.

**Comment by laurmaedje** [comment]
In the discussion so far, I've seen a few recurring use cases mentioned:

- Embedding the timestamp as text
- Having a seed for randomness or basing some computation on the time
- Implementing automatic dark mode at night

To summarize my thoughts about these in inverse order:

**Dark mode:** In my opinion, dark mode should be a feature of the PDF viewer rather than the PDF. It's easier to toggle, can respect system preferences, and I don't have to rebuild the document to light mode before sending it to someone else.

**Seed for randomness:** I think when working on a document with some desired randomness, being able to reproduce a specific seed for testing is very valuable. Moreover, in many cases a single seed per watch session suffices. This makes, in my opinion, `sys.inputs` better suited for this purpose than the current time.

**Embedding the timestamp as text:** I agree that this is a valid use case. The question is whether it is worth the tradeoffs. Typst already embeds the exact build time as PDF metadata, so it's there in a machine-readable format. Of course, there are use cases where that doesn't help, but I think it's important to mention. 

The question arises whether `datetime.now()` within `typst watch` would update on each compilation or retain the time when the watch session was initialized. The latter would alleviate incremental compilation issues, but I don't have the impression this is what people want. I think someone would very quickly open a bug report about that because it is not the naturally expected behaviour.

Meanwhile, updating on each compilation is a pretty big footgun. Just writing `set document(date: datetime.now())` would effectively disable incremental compilation. Worst of all, knowing _which usage patterns_ mess with incremental compilation requires a fair bit of knowledge about compiler internals. It's a central goal of Typst to ensure incremental compilation is effective. (From the design principles in the README: "All Typst language features must accommodate for incremental compilation.")

On top of that, it _is_ already possible with `sys.inputs`. I acknowledge that using shell commands for this is not trivial and doesn't work in the web app. However, the motivating scenarios I've seen so far fall into roughly two camps:

- Someones wants auto-generate some report or something. If one is automatically generating reports, they are very likely already in a scripting environment where adding an input via shell is not that much to ask on top.

- Someone wants to embed the time in a hand-written document (e.g. a student with their last export time as mentioned above). If it's just about being able to _know_ that time: It's already there in the PDF metadata (that metadata can be inspected in every good PDF viewer) and file creation date. Is also having it as text in the document really such a big win that it justifies the downsides of this feature?

**Comment by mxmerz** [comment]
@laurmaedje I feel a bit "guilty" about having re-opened this issue last May, so I wanted to give you a brief update on my thoughts :) (My use-case was and is the first of the three that mentioned yesterday: Showing the timestamp as text in the document.)

- I very much agree with you that this is not a very important feature - that's part of the reason I didn't reply over the last few months ;)
- I don't know much about Typst's internals, but I agree that if `set document(date: datetime.build_time())` effectively disables incremental compilation, then that is a pretty big footgun.
- Working under the assumption that just putting the build time in the footer, for example, would _not_ mess with incremental compilation that much (?), I still believe that a function like `datetime.build_time()` would be worth the tradeoff _if_ it was provided with aggressive documentation along the lines of "everything using this function must be re-layouted on each build, effectively disabling incremental compilation for these layout items; use accordingly".

However, as I already said, it's not an important feature. I will continue to use and recommend Typst even if I never get a `datetime.build_time()`. It _is_ a tradeoff, and I respect your (the maintainers) decision on it and I think you're doing a good job :)

**Comment by MrPixelized** [comment]
I think this is an obstacle to adoption for some users. Overleaf is very convenient and can spit out documents with timestamps no problem. Note also that this is **super duper common**. A university course looking to migrate to typst (including the web editor) won't like the fact that they just can't achieve the same thing, while it is standard and default in tonnes of latex templates.

Could tinymist and the web editor provide a highlight and warning on hover for use of this function? e.g. "Warning, when using real-time compilation, this value only updates about every half an hour. You can get around this by exporting the document manually".

I also wonder if this should really be such a hit to performance. In most cases a short string will change, which should generally lead to no or minor variation elsewhere in the document. I don't know about typst internals, but I feel like the locality of this effect *should* lead to a small amount of processing in typst, precisely because of incremental compilation. If anything, the ability to do this and do it well seems like it would be a showcase of the best possible implementation of incremental compilation.

**Comment by laurmaedje** [comment]
> I also wonder if this should really be such a hit to performance. In most cases a short string will change, which should generally lead to no or minor variation elsewhere in the document. I don't know about typst internals, but I feel like the locality of this effect should lead to a small amount of processing in typst, precisely because of incremental compilation. If anything, the ability to do this and do it well seems like it would be a showcase of the best possible implementation of incremental compilation.

If the datetime is used as text on e.g. a title page, the hit won't be huge as it will only invalidate the local layout (like normal typing there). Though that still potentially duplicates the amount of work per keystroke.

If, however, the datetime is used in `set document(date: ..)`, the whole document is invalidated because `context document.date` is accessible anywhere and the flow of such accesses is not explicitly tracked. Instead all styles are assumed to may have an effect. Making this more fine-grained is difficult and I expect that it would have quite a bit of overhead.

 If it's used directly a header or footer (e.g. `set page(header: [Time: #datetime.now()])`, that again affects the document styles as the header & footer content changes every time, again defeating incremental compilation. If it's used within a context block within a header or footer (e.g. `set page(header: [Time: #context datetime.now()])`), things are a bit less bad since it doesn't become part of the content itself, instead being accessed lazily during header layout. However, the page contents would still be relayouted shallowly (nested blocks would be memoized) because page content is not currently memoized separately from header & footer (since the two rarely changes and every additional level of memoization has overhead).

As you see, it's quite intricate and I myself had to look into the code right now to check what really happens in which scenario.

**Comment by drnw** [comment]
It is clear that making the proposed change is "quite intricate". I see this as a side effect of the [Design Principle](https://github.com/typst/typst?tab=readme-ov-file#design-principles) "All Typst language features must accommodate for incremental compilation". This makes sense for Typst GmbH, its shareholders and the users of the Typst.app

However, there are use cases for the Typst compiler outside the Typst.app. For example, you can use Typst instead of Latex in a MyST pipeline or Typst in place of Weasyprint in applications and websites. However, if the design principles have led to the implementation of the compiler being as intricate as noted above, this could well be a barrier to adoption of the Typst compiler in the wider community.

I note that the Typst CLI has `compile` and `watch` commands. Does incremental compilation matter when using `compile`? Can Typst have language features which only work when the command is `compile` i.e. they are ignored when the command is `watch`?

**Comment by laurmaedje** [comment]
Bringing statements like "what does the Product Manager at Typst make of this conversation"[^1] and "makes sense for Typst GmbH, its shareholders" into a discussion that is led on technical merits is not constructive.

The web application isn't even the main problem here as it could feasible force a timestamp at export time and export is always well-separated from preview. With `typst watch` that is not the case. People will frequently just take the last compiled PDF coming out of watch mode, which is why I'm not prepared to have the output of `typst compile` and `typst watch` differ.

I'll keep this issue in mind and _might_ reconsider in the future, but I feel like the discussion here is going nowhere. The substantial arguments have been made, so there's not much of a point to continue going in circles here.

[^1]: Depending on your defintion of Product Manager either we have none or it's me for the language and compiler.
