### ISSUE TITLE
SVGs with text are not rendered at all with New Computer Modern

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#2051]
### Description

Consider the following SVG:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="262pt"
   height="188pt"
   viewBox="0.00 0.00 262.25 188.00"
   version="1.1"
   id="svg70"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <g
     id="graph0"
     class="graph"
     transform="scale(1 1) rotate(0) translate(4 184)">
    <!-- RAL -->
    <g
       id="node1"
       class="node">
      <polygon
         fill="none"
         stroke="black"
         points="169.25,-108 115.25,-108 115.25,-72 169.25,-72 169.25,-108"
         id="polygon8" />
      <text
         text-anchor="middle"
         x="142.25"
         y="-86.3"
         font-family="Times,serif"
         font-size="14.00"
         id="text10">TEST</text>
    </g>
  </g>
</svg>
```

If it is just included like that in the web app, it is rendered correctly:

Input:
```
#image("test.svg")
```

Output:
![image](https://github.com/typst/typst/assets/47084093/628c4a93-8511-47bf-95c2-274ff88e3377)

However, if the input is like this, the text disappears:
```
#set text(font: "New Computer Modern")
#image("test.svg")
```
Output:
![image](https://github.com/typst/typst/assets/47084093/e0cb3c5f-4662-4ed2-9782-8c17d1e35f94)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
The problem seems to be that typst changes the font family from `NewComputerModern10` to `New Computer Modern`[^1]. When the font family in the SVG file is `New Computer Modern`, typst assumes that font exists under that name and that `svg2pdf`, `usvg` and `fontdb` are aware of it. However, they only know the font as `NewComputerModern10` and thus the fallback font `Times New Roman` is loaded[^2], which also does not exist within the typst world. This leads to no font being loaded at all and thus no glyphs being rendered.

Trying to fix this, one might think that changing the font family in the SVG file or in typst itself to `NewComputerModern10` would solve the problem. However, typst then does not recognize the font, and replaces it with its fallback `Linux Libertine`[^3].

When running `svg2pdf` to convert the SVG to a PDF file without typst, the font is indeed correctly rendered when using the `NewComputerModern10` font family _(see example)_.

<details>
<summary>Example</summary>

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="30.357 20.119 465.0116 197.665" width="465.0116" height="197.665" xmlns="http://www.w3.org/2000/svg">
  <text font-family="Arial" font-size="16.7px;" x="30.357" y="35.119">Hello World (Arial)</text>
  <text font-family="New Computer Modern" font-size="16.7" x="30.739" y="70.029">Hello World (New Computer Modern)</text>
  <text font-family="Open Sans" font-size="16.7" x="30.836" y="108.784">Hello World (Open Sans)</text>
  <text font-family="NewCM10" font-size="16.7" x="30.836" y="143.784">Hello World (NewCM10)</text>
  <text font-family="NewComputerModern10" font-size="16.7" x="30.836" y="178.784">Hello World (NewComputerModern10)</text>
  <text font-family="serif" font-size="16.7" x="30.836" y="213.784">Hello World (serif)</text>
</svg>
```

(The default fallback of `usvg`[^4] has been disabled for this example.)

![image](https://github.com/typst/typst/assets/7191192/27fd0476-5cb2-4367-92f1-84c450126261)
</details>

[^1]: https://github.com/typst/typst/blob/65aeea31423ec9ea872c52f41469ad6adbeded17/crates/typst/src/font/book.rs#L397-L410
[^2]: https://github.com/RazrFalcon/fontdb/blob/c07be3aa11d4efc957cd5fb6560da4f54c3fea6f/src/lib.rs#L180
[^3]: https://github.com/typst/typst/blob/65aeea31423ec9ea872c52f41469ad6adbeded17/crates/typst/src/image.rs#L349-L352
[^4]: https://github.com/RazrFalcon/resvg/blob/e128224d9873722b88207dc25a9e20014ac8997d/crates/usvg-text-layout/src/lib.rs#L617-L618

**Comment by laurmaedje** [comment]
I see, that makes total sense. I knew it would come back to bite us to fix these ugly names at some point. :/ I wish fonts just had consistent and good names.

**Comment by laurmaedje** [comment]
One solution could be to only expose the "fixed" names as (preferred) aliases and stay compatible with the real names.

**Comment by LaurenzV** [comment]
A temporary workaround is to add something like `#show image: set text(font: "Linux Libertine")` at the start of the file.

**Comment by laurmaedje** [comment]
Part of changing that could also be to allow PostScript names to select font variants.

**Comment by laurmaedje** [comment]
I pushed a fix which sets the correct fallback font name for usvg. Making Typst itself a little more lenient (i.e. making the trimmed version an alias, but also supporting the untrimmed font name) is probably worthwhile, but a separate topic.

**Comment by laurmaedje** [comment]
I opened an issue for this here: https://github.com/typst/typst/issues/2098
