### ISSUE TITLE
Different behaviour for logically same code.

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2053]
### Description

I am using Version ca1096de

Given two counters: pause_counter and  repetitions and a handy helper function:
```
#let register_repetition(amount) = repetitions.update(rep => calc.max(rep, amount));
```

Now I do such update (somewhat nested in locates). Confusing to me is that the following configurations do not have the same effect:
```
    // only calling this one results in warning: layout did not converge within 5 attempts
    register_repetition(pause_counter.at(loc).first() + 1)

    // only calling this one results in no warning 
    repetitions.update(rep => calc.max(rep, pause_counter.at(loc).first() + 1))
```

Do I miss something? Those two should be identical, right? It's just an indirection that should have no influence in internal iteration...?

More unusual: When calling both variants after each other, no warning appears.
```
    // only both results in no warning 
    register_repetition(pause_counter.at(loc).first() + 1)
    repetitions.update(rep => calc.max(rep, pause_counter.at(loc).first() + 1))


    // only both results in no warning 
    repetitions.update(rep => calc.max(rep, pause_counter.at(loc).first() + 1))
    register_repetition(pause_counter.at(loc).first() + 1)
```

Even using a variable to save the value results in the problem:
```
	let pause_nr = pause_counter.at(loc).first() + 1;
        repetitions.update(rep => calc.max(rep, pause_nr))
```

What is happening here?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Beiri22** [comment]
I tried to condense my example to the minimum possible: https://typst.app/project/rwjvPI8JWWEt2lAAdE16Um

**Comment by laurmaedje** [comment]
I _think_ by having `pause_counter.at(loc).first() + 1` within the update, it being evaluated is deferred to a different introspection iteration, which uses an introspector with different data, yielding different results. 

In that sense, any introspection within a counter and state update might yield unexpected results. Moreover, it seems to be generally quite broken because this example overflows the stack:
```
#let c = counter("c")
#locate(loc => c.update(_ => c.final(loc).first()))
#c.display()
```

The crash is certainly a bug and the logical difference could for sure also be considered a bug (even though I have no idea how to fix it). That being said, I wonder whether what you want to achieve can't be expressed in a simpler way. Creating counter/state updates within locate is a bad idea most of the time because it's inefficient (forces many iterations). The `show text: paused-content` rule will also heavily slow down Typst in larger documents because every single text node becomes a locate element.

**Comment by Beiri22** [comment]
As far as see, there should not be any circular dependency between pause_counter and repetitions, so that the system uses just 2 iterations. Would it be easier for typst, if all values (slide, subslide, pause_counter, repetitons) were inside one state, so that only one update happens? (But this update may also be in nested locate()...) Or any better solutions?

The two bugs seem tricky. But I think we should not ignore them; since they make the language in some way unsound.

**Comment by laurmaedje** [comment]
Introspection within counter and state updates is not allowed anymore:
```typ
#let c = counter("c")
#context c.update(_ => c.final().first())
//                     ^^^^^^^^^
// error: can only be used when context is known
#context c.display()
```
And there is also no crash anymore. So I'll close this.
