### ISSUE TITLE
`box` breaks smart quotes

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2154]
### Description

Because of the #1716 I had to make a `ubox` (https://github.com/typst/typst/issues/1716#issuecomment-1690842054). But when I try to use smart quotes which are near the `box` they break:

```typ
#let underline-thickness = 0.5pt
#let underline-offset = 1pt

// underline box (can't use #underline(h(1fr)) in v0.8)
#let ubox(..box-args) = box(
  width: 1fr,
  stroke: (bottom: underline-thickness), // Same as underline
  outset: (bottom: underline-offset), // Same as underline
  ..box-args,
)
#set underline(stroke: underline-thickness, offset: underline-offset)

#let text = [ "this" ]
#let text = [ "this"]
#let text = ["this"]

#{
  ubox(width: 1em)
  underline(emph(text))
  ubox(width: 1em)
}
```

![image](https://github.com/typst/typst/assets/37143421/9007e1fd-6705-4b13-b4d1-1e30456b80cc)

```typ
#let text = [ "text" ]
// #let text = [ "text"]
// #let text = ["text"]
```

![image](https://github.com/typst/typst/assets/37143421/f570039f-ecfe-4880-aaf4-8e4fc871e80b)

Adding a pair of whitespaces is an easy workaround, but they do widen the overall length, which is very bad, if precision is the key. Thankfully, I didn't have (yet) cases where the precision (of underline length) is mission-critical.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
This is happening because boxes with non-`fr` widths are being treated as containing only an object replacement character (U+FFFC) in the `typst::library::par::collect` function, which handles smart quotes. Perhaps we could try inspecting the contents of the box for the purposes of the smart quote algorithm; any thoughts about this?

For some reason, boxes with `fr` widths are [treated as whitespace](https://github.com/typst/typst/blob/72f4c543cced0741f3349896cc96bda90a0c69ac/crates/typst-library/src/layout/par.rs#L629) when processing the last seen character but [as an object replacement character](https://github.com/typst/typst/blob/72f4c543cced0741f3349896cc96bda90a0c69ac/crates/typst-library/src/layout/par.rs#L615) for peeking.

**Comment by Andrew15-5** [comment]
This is now fixed! I tried compiling with the new version and without the "workaround spaces" after reading the new changelog:

> Implemented a new smart quote algorithm, fixing various bugs where smart quotes weren't all that smart
