### ISSUE TITLE
Empty figure.caption causes the compiler to panic

### ISSUE THREAD

**Issue by Cubxity** [typst/typst#2165]
### Description

**Error:**
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/git/checkouts/typst-6808799b0d8fdaa9/360cc9b/crates/typst-library/src/meta/figure.rs:515:19
```

**Reproduction code:**
```typst
#figure.caption[]
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by SekoiaTree** [comment]
This isn't actually related to being empty. Whenever you call figure.caption on its own, `supplement` isn't set, so it fails. But you can't pass `supplement` as a parameter. One possible way to fix this would be to make it impossible to call `figure.caption` manually, since it's really only there for show/set rules.

**Comment by tingerrr** [comment]
I'll look into this and other possible occurrences in sub-elements.
