### ISSUE TITLE
unexpected behaviour parsing parenthesis in math mode

### ISSUE THREAD

**Issue by Moertel113** [typst/typst#217]
The math expression 
`$ 1/(2 (x) $`
with a  `)`  _missing_ at the end compiles without errors and generates 

$$ \frac{1}{(x)}$$

I would expect either an error while compiling or 

$$ \frac{1}{2(x)} \qquad\text{or}\qquad \frac{1}{2(x}$$

as the result.

**Comment by laurmaedje** [comment]
Seems to be a parser bug.

**Comment by rpitasky** [comment]
Does typst have any notion of warnings? This seems like a solid candidate for a non-fatal error. 

Otherwise, I think using the first match after the `/` is a reasonable solution, at least, more reasonable than what exists now.

**Comment by AndyBarcia** [comment]
Sadly, Typst doesn't appear to have anything like warnings. The source file is either parsed correctly, or syntaxNodes of type "error" are generated.  

Anyway, I think that arguments can be made to either generate an error or parse it as it is. On one hand "$ 1 ( 2 $" generates the following without errors

   $1 ( 2$

And usually, typst doesn't really care about parenthesis. But fractions are a special case, because they show an error when malformed, like with "$ 1 /  $" 

```
error: expected expression
  ┌─ main.typ:1:5
  │
1 │ $ 1 /  $
  │      ^
```

And they also remove unnecessary sets of parenthesis. Like with "$ 1 / (2+2) $", that generates

  $\dfrac{1}{2+2}$

So "$ 1/(2 (x) $" maybe should throw an error like the following, to keep consistency:

```
error: expected closing parenthesis
  ┌─ main.typ:1:5
  │
1 │ $ 1/(2 (x) $
  │           ^
```

**Comment by laurmaedje** [comment]
[Fixed here.](https://github.com/typst/typst/commit/c5fb34123cad86294887defe9571cd773e9ace99) I settled on the behaviour where the fraction just displays everything that was written. The first parenthesis isn't removed, because it doesn't have a matching one, but there is also no error because unbalanced parenthesis in math aren't really an error. This might be a good candidate for a warning once there is such a thing.
