### ISSUE TITLE
newlines in let expressions break code parsing

### ISSUE THREAD

**Issue by f3rn0s** [typst/typst#2178]
### Description

Using a newline in a let expression has broken in-between versions 0.7.0 and 0.8.0, now it does not parse correctly:

```
#let value = (1, 1, 1)

#let x = value
  .map((x) => {x + 2})

#{
  value
    .map((x) => {x + 2})
}
```

![image](https://github.com/typst/typst/assets/1351279/93b95e96-8aae-4f80-8bf0-305a3baec9ef)

Ideally, the old behaviour should be returned, or a note in the changelog should be added to mention the breaking change.

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
The old parsing behavior was a bug, which was recently fixed. Usually this wouldn't end up on the web app without patch notes, but there was a hotfix for an unrelated issue

https://github.com/typst/typst/commit/e39be71a54a4264032115ab3b31bdd86845a966b

You can still use multiple lines, but you need to use ( ) or {  }

**Comment by laurmaedje** [comment]
It was actually fixed before the release and is mentioned in the changelog under "Miscellaneous Improvements". I agree that this might be something I should've labelled "Breaking Change" since even though it's a bug fix from my perspective, from a user perspective it wasn't clear that this was unintended.
