### ISSUE TITLE
Turning content into string: `str(content)`

### ISSUE THREAD

**Issue by zouharvi** [typst/typst#2196]
### Description

The `str()` function could accept content out of which it would extract the textual parts. For example: `str([Hello _there_])` would be `"Hello there"`.

### Use Case

In a few projects I want to set the document (PDF) title but also display the title in the doc itself. However, the title might be _content_ and not a string. That means that it needs to be duplicated:

```
set document(title: "This cool project")

align(center)[
  #set text(size: 1.5em)
  This _*cool*_ project
]
```

This is not a big deal but leads to these kinds of templates which feel weird because of the duplicity:

```
#show: project.with(
  codename: "This cool project",
  title: [This _*cool*_ project],
)
```

Ideally, one would be able to write the following, with conversion from content to string inside of the template.
```
#show: project.with(
  title: [This _*cool*_ project],
)
```

I acknowledge that there are many vague cases and lots of complexity -- I'm just putting this out. Maybe there's also an existing solution to this which I overlooked, such as iterating the children of the content and only collecting the textual yield.

**Comment by EpicEricEE** [comment]
You can indeed iterate over the children and collect the text recursively. It's probably not perfect, but it works for you case:
```typ
#let to-string(content) = {
  if content.has("text") {
    content.text
  } else if content.has("children") {
    content.children.map(to-string).join("")
  } else if content.has("body") {
    to-string(content.body)
  } else if content == [ ] {
    " "
  }
}

#to-string[This _*cool*_ project] // => "This cool project"
```

**Comment by zouharvi** [comment]
Thanks @EpicEricEE. That feels like should be the implementation of `str(content)` so I'll leave the issue open to keep this under consideration but anyone else feel free to close it.

**Comment by laurmaedje** [comment]
Internally, there is already a plain text functionality (via the `PlainText` trait), which is used for instance for the PDF outline. 

Since the issue mostly comes up with `set document(title: _)`, I'm considering to just allow content there and do the plain-text conversion internally. 

Long-term, with get rules, this would also mean that more "standard" metadata like title, author, etc. could be specified with document set rules instead of on the template and templates could read that. For that, the title would also need to be content.

**Comment by laurmaedje** [comment]
I have pushed [a commit](https://github.com/typst/typst/commit/c1bc529986f723f8bb06feedfbdc98520763ceb9) that allows arbitrary content as the document title. It will then be turned into a string internally. This should cover your use case. I will also update the web app templates to default to a content block instead of a string with the next release.

I'm not comfortable with exposing the internal plain-text functionality at the moment because it's very lossy for more complex content.

**Comment by zouharvi** [comment]
Thank you for resolving this!

**Comment by emilyyyylime** [comment]
@laurmaedje would it be possible to apply the same change for document author?

**Comment by laurmaedje** [comment]
Does it really make sense for an author name to have markup?

**Comment by emilyyyylime** [comment]
in Hebrew for example, I might write `'` and use a show rule to turn it into a Geresh `׳`, or someone might want smart quotes when entering their Name "nickname" Surname. It's mostly about simple conversions like that and about being able to reuse the same variable later in like the title page.

**Comment by laurmaedje** [comment]
Unfortunately the plain text conversion employed to convert the title to a string is very naive, so it wouldn't be able to handle show rules. I think it also doesn't properly handle smartquotes, but that would be fixable.

**Comment by gasche** [comment]
I looked for this feature to have a convenient shortcut for inline code. I'm writing content with a lot of inline OCaml code, and instead of writing

```
 ... ```ocaml Foo``` ...
```

I would like to be able to write `#code[Foo]` or even `#c[Foo]`. This suggests the definition

```
#let code(s) = raw(s, lang: "ocaml")
```

but this does not work because `s` is content in `#code[Foo]`, but `raw` expects a `string` argument. The current solutions are to call this like `#c("Foo")`, which is conceptually cleaner but also noticeably less convenient to type, or to assume that the caller will only pass string-like content (no nested structure) and call `s.text`:

```
#let code(s) = raw(s.text, lang: "ocaml")
```

**Comment by goyalyashpal** [comment]
most of the time, i need this kind of functionality as the string concatenation with `. + " " + .` becomes VERY ugly, very fast.

i don't need to use content in place of strings, or even perform any conversion per say, but i just need some easy way to join strings.

think: the new f-strings in python, vs. doing via `+` strcat operator in olden times.


context:

```typ
let filecontents = if prependName == true {

    if type(comment) == str {
      comment + " " + filename + "\n" + read(file)

    } else if type(comment) == array [
      #comment.at(0) #filename #comment.at(1)
      #read(file)
    ]  // <~~~~ Intended easy way to concatenate strings.

  } else {
    read(file)
  }
```

focussing in on the intended part:

* some string templating construct akin to `typ` marking content:
    ```typ
    [
      #comment.at(0) #filename #comment.at(1)
      #read(file)
    ] 
    ```

* versus current way to fight with `typc`

    ```typc
    {
      comment.at(0) + " " + filename + " " + comment.at(1) + "\n" + read(file)
    }
	```
