### ISSUE TITLE
Export source file of the project or export project to github

### ISSUE THREAD

**Issue by xsro** [typst/typst#2206]
### Description

1. download all files in a project with a zip format
2. sync with github

### Use Case

- for users like me who has terrible network connection, I want to download my project to compile them in my machine
- Some users like me want the source file under my control
- Some users need to backup source file with tools like git

**Comment by xkevio** [comment]
These are two different and orthogonal requests, where one of which is already possible. The `Backup` button already exports your project as a ZIP archive.

Independently of that, git integration is planned at some point.

**Comment by laurmaedje** [comment]
Git integration is tracked here: https://github.com/typst/typst/issues/982

**Comment by stellarpower** [comment]
I don't see any backup button myself in the web app; there is a download button next to the project, but this renders the PDF and presents this to my browser. From a UX perspective, I would expect the download button to zip up the whole project, and a button with a PDf document on it would be most logical for just getting a copy of the rendered document.

**Comment by laurmaedje** [comment]
> From a UX perspective, I would expect the download button to zip up the whole project, and a button with a PDF document on it would be most logical for just getting a copy of the rendered document. I also think it is more intuitive ot be able to download the project here than it is to open it in the editor first.

Fair enough.

> When the project is open in the editor, an entry in the menu bar was where I was looking ,and failing to find it.

It's both on the right _and_ in Typst > Export ZIP. Maybe it would be more discoverable in the File menu.

**Comment by stellarpower** [comment]
Hmm, guess I was looking for "backup" by the time I re-opened the project, so missed that. If the two are one and the same, I think it confuses things a bit giving them separate names. I guess it's discoverable where it is, but would be good to have an extra copy in the projects page, if that's more like a file manager type of interface.

From an icons perspective, I think something like this seems clearer to me:
![image](https://github.com/typst/typst/assets/5004545/9e3c5826-cd5b-4562-8721-dd1a849afc1c)
It makes it easy to scan and to see - I think the rendering of the PDF is the main part of the process, rather than the fact you can download it, if you see what I mean. A zip folder for "export as zip"/"backup" would also make sense.
