### ISSUE TITLE
Cant use *bold* syntax without space after - how to make single letter bold?

### ISSUE THREAD

**Issue by laundmo** [typst/typst#2241]
### Description

Sometimes i want to make only part of a word bold, for example to highlight abbreviations.

But `*G*nu *N*ot *U*nix` doesn't work - typst doesn't recognise `*` as bold when within a word - i have to put spaces around it.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is intentional for both `*` and `_` because you wouldn't want `hello_world` to create an error. In German, the star also appears often in Words to include all genders (i.e. `Entwickler*innen`).

To emboled part of a word, you can use the underlying `strong` function for which the stars are syntax sugar: `#strong[G]nu`

**Comment by laundmo** [comment]
thanks, I'd searched for a #bold function and couldn't find anything...

**Comment by lettuceDestroyer** [comment]
@laurmaedje Couldn't we avoid the case with for example `Entwickler*innen` with an escape character. Currently if I want to use the `#` in a text I have to use a backslash (`\`) as escape sequence. This would also be possible with the markdown star (`*`) for bold or underscore (`_`) for italic.

So `Entwickler*innen` would be written as `Entwickler\*innen`.

**Comment by laurmaedje** [comment]
It would be possible, but I think it's more common for `*` or `_` to be part of a word than for a user to want to embolden part of a word.
