### ISSUE TITLE
Multipage code listings are cut off inside figures

### ISSUE THREAD

**Issue by natrow** [typst/typst#2327]
### Description

Multi-page code listings typically roll onto the next page as expected. However, when placed inside a figure they go off the page and are cut off.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment]
There's likely an implicit unbreakable block inside of a figure (don't remember 100%), try : 
```typ
set figure: it => {
  set block(breakable: true)
  it
}
```

**Comment by laurmaedje** [comment]
Small correction: The figure needs show, not set. So, written a bit more compactly with show-set, it would be `#show figure: set block(breakable: true)`.

Figures not being breakable by default was an explicit design decision since in most cases it is not desirable. That's why it is opt-in.

Since this behaviour is also documented with the figure function, I would go ahead and close this.

**Comment by natrow** [comment]
Ah, I see that part of the documentation now. Perhaps this should be the default behavior when using the standard template? Thanks!
