### ISSUE TITLE
Typst Silently Generates Bibliography Empty

### ISSUE THREAD

**Issue by stellarpower** [typst/typst#2336]
### Description

I was trying to get to grip with citations, so, I found an example bibtex file [here]( https://tex.stackexchange.com/questions/141957/the-most-basic-biblatex-example )

If I insert a citation, and add the bibliography in I get no errors form the compiler, but it silently generates an empty bibliography in the document.

I then go to [this linter]( https://flamingtempura.github.io/bibtex-tidy ) online to check if the input file was okay (in either case, an error ought to bubble up from Hayagriva if the file is non-conformant), and find that if I use the linter version instead, all works okay.

I've shared as a web-app document, so please see there for details and MRE.

If the root cause of this is in Hayagriva, I think an issue still needs to be present on Typst, because I'm gonna take a gamble and say I can't think of any circumstances where it shouldn't be a bug for it to be spitting out an empty bibliography that has been cited in the document, whilst producing no error messages.

Thanks! Looking forward to future progress on this project.

Version: 0.8.0 (360cc9b9)

### Reproduction URL

https://typst.app/project/rtx7yXp4PfOSSvBcP--j7b

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Even more minimal example:

https://typst.app/project/rdQubGBYS3JXgcciYT-5_E

Seems like hayagriva doesn't recognize non-lowercase entries properly, possibly due to the usage of serde (although I'd expect the library to automatically lowercase the keys along the way).

https://github.com/typst/hayagriva/blob/4d25d9face1cd994dcc8a0241edfe8d801223e71/src/types.rs#L38-L41

Should definitely throw an error at least.

Perhaps this deserves an issue at the [hayagriva repo](https://github.com/typst/hayagriva) as well.

**Comment by reknih** [comment]
BibLaTeX parsing is now case-insensitive.
