### ISSUE TITLE
Path markers are not rendered correctly

### ISSUE THREAD

**Issue by schmidma** [typst/typst#2359]
### Description

When rendering an SVG graphic using the `image` function, marker elements on paths are not rendered correctly.

I generated the following simple graphic of a red arrow in inkscape:
![arrow](https://github.com/typst/typst/assets/7946935/7892a5f3-6947-4216-a9a3-a8969a92d9af)

After including it in my document with
```typst
#image("arrow.svg")
```
it is diplayed as
![image](https://github.com/typst/typst/assets/7946935/f0a394ec-f008-4d9c-9e44-c7c947a5f1de)

The arrow heads are both not respecting the color, nor the alignment with the path.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Okay, unfortunately Inkscape uses an SVG2 feature which is not currently supported by us for the color. As a workaround:

Open Inkscape Settings -> Input/Output -> SVG export and then check the following items:
<img width="346" alt="image" src="https://github.com/typst/typst/assets/47084093/69f895f5-e8a6-42e6-8b64-81c9f5ffcac2">

Then, when saving your file, press "Save as" and make sure to enable the following option:
<img width="315" alt="image" src="https://github.com/typst/typst/assets/47084093/048c13d9-464f-4776-8559-a4698ce52fcb">

This should at least temporarily fix the color problem. For the arrow orientation, you will have to wait for a fix from our side I'm afraid, but it should be fixed by the next release.

**Comment by LaurenzV** [comment]
Current status is that arrow orientation should be fixed by now, but making the colors match still requires changing Inkscape settings.

**Comment by LaurenzV** [comment]
This has been implemented upstream, so it should be fixed once we update the dependency in Typst.

**Comment by LaurenzV** [comment]
Fix is now on main.
