### ISSUE TITLE
Block quote syntax

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#2362]
#### Proposal
Add syntax sugar that allows writing block quotes similar to how they are defined in markdown.

#### Tasks
- [x] #2252
- [ ] Discuss the semantics of possible syntaxes (#2361)
- [ ] Implement block quote syntax

### Use Case

Typst has syntax adjacent to markdown, supporting block quotes will close the gab between those, providing a familiar syntax for a common use case and help typst's adoption.

```md
> This is a quote
> > This is a nested quote in case you need that
```
becomes:
> This is a quote
> > This is a nested quote in case you need that
in markdown.

**Comment by laurmaedje** [comment]
Copying my response from the discussion:

One thing I'm missing in it is motivation. I feel like multiple things are at play here:

- In Markdown, _everything_ needs to be syntax. In Typst, we can always have a function, so only the most often used things need syntax.
- Markdown is used often used in forums and conversations where quoting is very common. Meanwhile, Typst's main use case is writing documents, where block quotes are needed far less I think. It's not too bad to just write `#quote[...]`.
- It's very hard to have good syntax for attributions. Since none of the proposed syntaxes for attribution have any precedent (afaik), this would likely be a piece of syntax very few people are aware of. 

Overall, we already have a _lot_ of syntax and adding new syntax has a complexity high cost in my opinion. I specifically like about Typst in comparison to Markdown or AsciiDoc (which has tons of syntax), that we _don't_ need syntax for everything because we have a more general mechanism.

**Comment by tingerrr** [comment]
> It's very hard to have good syntax for attributions. Since none of the proposed syntaxes for attribution have any precedent (afaik), this would likely be a piece of syntax very few people are aware of.

As seen in the discussion, this part is likely the hardest to get right. And I think we can close this as not planned, I don't really have the time nor any arguments for doing this at this point in time.

If someone has a good argument for this, feel free to reopen this issue.

**Comment by thjbdvlt** [comment]
@tingerrr @laurmaedje 

Hi, i would like to add an argument to reconsider the reopening of this feature request.

As a student in humanities (literary studies), the lack of a blockquote syntax is an absolute no-go. I was considering switching from pandoc-markdown to Typst (for my master thesis) because i really like everything about it, but i just cannot imagine writing `#quote(block: true)` for every block quote (it _is_ way too bad).
In literary studies (but i think it's true for many social sciences as well), block quotes are __VERY__ frequent.
I have at least 4-5 more block quotes that headings (1/2 per page is a common thing), and many more than raw code, math things or bold text (i just don't use math things and use bold only for headings, so the `*` syntax in my writing practice is useless).

I think it would be an error not to target humanities / literary studies / social sciences editing, because [digital humanists](https://en.wikipedia.org/wiki/Digital_humanities) really care about things like pandoc and markdown.
As they are concerned about _writing_ (and, for some of them, _study_ the writing processes), they do think a lot about digital writing tools (like pandoc, markdown, latex, ms-word...) -- Typst really _could_ be a thing for them.

As an example, I just googled a random research article about some french poet i'm currently studying, you can look there about the number of blockquotes: https://books.openedition.org/quodlibet/619?lang=fr

Thank's in advance for reconsidering this feature request!

**Comment by PgBiel** [comment]
@thjbdvlt perhaps something like this could work for your needs?

```typ
#let q(body, attribution, ..args) = quote(body, attribution: attribution, block: true, ..args)

#q[
  Abc
][Plato]
```

I do agree the current way is a bit convoluted though due to the attribution being a named parameter. The block parameter is fine as you can just create an alias as shown (or use set rules).

**Comment by thjbdvlt** [comment]
@PgBiel yes it does simplify, but it's still a lot more verbose, and i still think there should be a syntax for that (as raw could be aliased as `#let r(lang, content)`.

**Comment by laurmaedje** [comment]
> yes it does simplify, but it's still a lot more verbose

Is it it really "a lot"? Considering you don't want an attribution, it's two extra letters:
```typ
#q[Abc]
```
vs:
```md
> Abc
```

Moreover, the function call syntax is (in my opinion) actually _simpler_ to deal with when there are multiple paragraphs. At least if we would follow Markdown and not make `>` indent-sensitive across paragraph breaks, you'd need to manage the `>` signs for each paragraph individually.
```typ
#q[
  Hi

  There
]
```
vs
```md
> Hi

> There
```

> raw could also be aliased as #let r(lang, content) = ...

I think the comparison with strong/emph is somewhat fair (though I think the differentiating factor is how common they are across all use cases). Raw, however, is rather different because it enters a completely new syntactical mode that properly supports frequent special characters that Typst would otherwise interpret and multi-line text without indent quirks. Writing code with normal strings would be very painful.

**Comment by thjbdvlt** [comment]
I would say that it is! That is 4 letters instead of 2. And these 2 additional letters, on standard keyboards, represent something like 6 additional key events:

For `> ` syntax:

1. maj
2. `>`
3. release maj
4. space (...)

For `#q[]`:

1. alt
2. `#`
3. release alt
4. `q`
5. alt
6. `[`
7. release alt (...)
8. alt
9. `]`
10. release alt

It's possible omit the newlines (that the `> ` syntax requires), but it would make the document unreadable so I doubt people will.

Plus, it requires to define the function. In could be in a template, of course, but it's still something that people have to do. And it seems strange to me to have to define such a common function (and known markdown syntax), as if it was an idiosyncratic operation. That said, I understand that Typst actually focus on technical papers (and that's why term lists have a syntax and blockquotes don't). 

Thank's for you response.

(Your point on multi paragraph is true!)

**Comment by laurmaedje** [comment]
Fwiw, various people have voiced that they consider the term list syntax unnecessary and that it should be removed. So this one is sort of an edge case. It has existed for a long time, so I'm kinda attached to it (and I like the `-`, `+`, `/` list trinity 😄), but if it didn't exist and someone would propose it now, I would probably reject it.

I guess it's true that `#q[..]` is a _bit_ harder to type than `>`, but then again `]` is typically auto-closed (in a decent editor), so 8-10 could be removed from your list.

> That said, I understand that Typst actually focus on technical papers (and that's why term lists have a syntax and blockquotes don't), so i'm probably not a targeted user.

I wouldn't say that! We think that Typst can be useful beyond technical papers and also want to cater to those audiences.

It's true that the function needs to be defined, but it's common that users need to do a _bit_ of set up. If you're writing non-English, you need to set the language. If you're writing scientific things, you need to set up your citation style. Writing many block quotes feels like a similar case to me.

**Comment by thjbdvlt** [comment]
Thank you for these additional precisions (about term list), and for the discussion :–)

Now I have a question (wondering, not a feature request): as syntax for raw/heading/... are kind of shortcuts for functions; would it be implementable to let the user define not only functions but also these syntax shortcuts (like when we define operators in a postegresql database mixed with the `show "Text": ...` thing in Typst)? i don't know Rust so i can't read Typst source code and i didnt found something about that in documentation.

**Comment by laurmaedje** [comment]
While possible, I think this would be a net negative because it results in inconsistency across the ecosystem, where everybody writes their own dialect. It makes it hard to read other's markup if you can't have any expectations about how things behave. 

So it's less of an implementation thing and more of a design choice to not support such a thing. Text show rules already kinda allow this (and they are also a bit controversial!), but at least they don't modify existing syntax.
