### ISSUE TITLE
Stop when pdf is closed

### ISSUE THREAD

**Issue by Eloitor** [typst/typst#2383]
### Description

When running

```
typst watch test.typ --open $READER
```

If I close the pdf, typst continues running.
I would like an option to get the compiler to stop if the reader is closed.

### Use Case

It would allow to run something like

```
nohup typst watch test.typ --open $READER > /dev/null 2>/dev/null &
```

without having to worry about killing the right typst process after we are done.

**Comment by laurmaedje** [comment]
I'm not sure whether this would really be the expected behaviour.

**Comment by Eloitor** [comment]
Maybe it is not the expected default behaviour, but it would be nice to have an option that works with --open that stops typst when the pdf is closed.

**Comment by TheJosefOlsson** [comment]
In testing this issue I have yet to find a reader that, using `watch` and `--open`, will automatically update when a new version has been generated. There might exist some reader that does update automatically, but since there is already a sort of disconnect between the typst process updating the file and the reader (since it might not be displaying the latest version), I don't think that this is a problem that necessarily needs a solution.

**Comment by Eloitor** [comment]
This works in Zathura works for me

**Comment by Enivex** [comment]
> In testing this issue I have yet to find a reader that, using `watch` and `--open`, will automatically update when a new version has been generated. There might exist some reader that does update automatically, but since there is already a sort of disconnect between the typst process updating the file and the reader (since it might not be displaying the latest version), I don't think that this is a problem that necessarily needs a solution. 

Sumatrapdf works on windows

**Comment by laurmaedje** [comment]
I'm not sure this is actually possible. But even if, it still feels a bit too niche to carry its weight as a feature. I think the real solution is using an integrated environment like VS Code or the web app.
