### ISSUE TITLE
Emoji where unicode has a variation selector does not render

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2448]
### Description

This character: `🌶️` for some reason has a variation selector and Typst refuse to render it. It's not the same as `🌶`.

> It may render the same or differently, it depends on what's rendering it. For example, Discord and the Github editor (not the issue itself) show's them the same, at least in Windows. But at least renders something.

```typ
variable: #emoji.pepper.hot  \
good unicode: 🌶  \
bad unicode: 🌶️
```
And renders (same result in PNG and PDF):
![image](https://github.com/typst/typst/assets/38019254/2bfd0ce6-a48c-4d68-b902-f7432f8da2d2)

The first character is the one producing the error.
![image](https://github.com/typst/typst/assets/38019254/281b9bbe-6cad-4701-955b-33e7e4a77abc)

This odd unicode pepper came from the Windows emoji selector, which opens with Windows+`.`. So it's a common way of an user to input the emoji. The reason I did this and not use `#emoji.pepper.hot` is because I was writting the emoji inside a  `raw` block. I don't know why Windows is adding this extra Unicode codepoint or even if it's valid, but the fact that Typst renders nothing is confusing.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by matthew-e-brown** [comment]
Ahh, U+FE0F and U+FE0E, my two favourite Unicode code-points! (I'm not kidding 😄). That variation selector is there for good reason, and the latter of the two bullets isn't "bad Unicode" at all&mdash;I'd actually argue it's the more correct of the two!

The documentation for the _Variation Selectors_ Unicode block ([PDF](https://unicode.org/charts/PDF/UFE00.pdf), [namelist chart](https://unicode.org/charts/nameslist/n_FE00.html)) has some information, but for this topic specifically you'd probably be more interested in the [Unicode Technical Standard #51, section 1.4.3: Emoji and Text Presentation Sequences](https://unicode.org/reports/tr51/#Emoji_Variation_Sequences).

When appended to a character, the two variation selectors are used to decide which style to render the emoji with:

- `U+____ U+FE0E` → render the character in text form
- `U+____ U+FE0F` → render the character in emoji form

<details><summary>Most software's handling of this is kinda broken, though.</summary>
<p>

`<minor-rant>`

Unicode actually defines which characters are supposed to use text presentation vs. emoji presentation by default; the U+FE0E and U+FE0F are used to select one specifically. _Technically,_ `U+1F336 HOT PEPPER` is supposed to be text by default: your pepper should **always** look like `🌶︎`, unless the U+FE0F is present, at which point it should **always** look like `🌶️`. If you take a look at [`emoji-sequences.txt`](https://www.unicode.org/Public/emoji/15.1/emoji-sequences.txt) (linked in the above Unicode page), you'll see that `⛽️ fuel pump`, for example, has a sequence of `26FD`: getting a fuel pump emoji to render should only take a single U+26FD. However, if you CTRL+F for `1F336`, you'll see that the `hot pepper` _emoji_ is actually _defined_ as `1F336 FE0F`.

Sadly, basically every application I've ever used doesn't handle this perfectly. GitHub[^1] does respect my `🌶️` (with FE0F) peppers inside of backticks, but not the default. A raw `U+1F336`, which should be text, appears as 🌶️ in the rendered preview, but `🌶︎` in the Markdown editor (again, U+1F336 should be text when it appears without a modifier). Even ***worse***, though, is that GitHub actually completely ignores the `U+FE0E` (text) selector. On Windows, this character, 🌶︎, acts exactly like `U+1F336`, despite actually being `U+1F336 U+FE0E`: it's textual in the monospace editor I'm looking at, but emoji in the rendered preview.

Basically, it's part of your emoji picker's job to insert that variation selector when you pick an emoji. Otherwise (according to the Unicode spec), you wouldn't be getting an emoji: you'd get a text glyph instead. Notably, though, like I mentioned in that little rant, some codepoints are emoji-styled by default: those don't need the U+FE0F to appear as emoji. The problem with that is that, like you saw with how GitHub renders them, it's not always consistent. You'll find some emojis that look like emojis as they should in _most_ places, but when you open that file in a different app, suddenly you get the text version, despite the fact that that symbol should only exist as an emoji.

If it were up to me, everything spat out by our devices' emoji pickers would always have the U+FE0F on them. If I'm typing an emoji, I want the colours! I can get the uncoloured ones with U+FE0E or with some ancient ALT-code.

`</minor-rant>`

</p>
</details> 

I'm fairly confident that whether or not these appear properly is basically a matter of whether or not the current font/set of fonts contains the correct glyph. When you see `🌶︎`, that's coming from Segoe UI Symbol (by default, on Windows); but Segoe UI Symbol doesn't have a character for `🌶️`, so that comes from Segoe UI Emoji. If you have don't have Segoe UI Emoji, then you should theoretically see `🌶︎`, but not see `🌶️`&mdash;just like any other time you've seen a character not in your current font.

My best guess for what's happening here is some combination of either:

- The system's font could erroneously have a coloured hot pepper glyph in the spot where the _uncoloured_ pepper glyph is supposed to go, and nothing in the coloured spot.
- Typst could perhaps fail to fall back to a different, colour font when it fails to find `U+1F336 U+FE0F` in the current font (which could either be a bug, or it could be because changing your document's font would remove any fallback that the default font uses?).

But I'm not sure. 🤷🏻‍♂️

I also recall seeing [in several places](https://github.com/typst/pixglyph/blob/c8f3890c9a7b2e8e67b0d213467c8eaa44ff48ba/src/lib.rs#L17-L19) that Typst does not do emojis 100% just yet (which is understandable, Unicode is kind of insane to get all of).

**Disclaimer after all that:** I'm not an expert on this, I'm just insane and have gotten way too into Unicode and Emoji on multiple occasions when trying to print fancy things to my terminal. Specifically, as much as I've done lots of digging with Unicode and Emojis, I have **no idea** how _fonts_ work 😅. I just thought I'd throw in my two cents on the off-chance it provides a starting point... 😁

[^1]: I say "GitHub supports" or "GitHub ignores." Really, it's the whole GitHub/Chromium/Windows stack. Windows has all the fonts it needs to render emojis; GitHub has a `font-family` that specifies both `Segoe UI` and `Segoe UI Emoji`; but _somewhere_ along the line, some little thing isn't implemented quite perfectly.

**Comment by khaledhosny** [comment]
The Emoji variation selectors work basically by switching fonts. If Emoji form is requested then find the first color font that supports the code point and use it, otherwise find the first non-color font that supports it an use it (this assuming the system has automatic font fallback, otherwise it is all moot and the user has to select the right font manually).

**Comment by laurmaedje** [comment]
I can reproduce this with 0.11.1 in the web app, but not with 0.12.0 Testing, so it seems to be fixed.
