### ISSUE TITLE
Alternate LaTeX-style math input

### ISSUE THREAD

**Issue by Enivex** [typst/typst#253]
Disclaimer: I speak as a mathematician, who is also very excited about the idea of Typst as an alternative to TeX for typesetting.

I truly believe that in order for Typst adoption to happen to any measurable extent, specifically in mathematics,  it _must_ be possible to input at least a subset of mathematics with LaTeX-style syntax. Say, a similar subset to that supported by MathJax today. Changing the syntax for math input, especially short-term, will be a really tough sell for most people (possibly even a deal-breaker), when it's been ingrained over decades. It's become the standard even outside of LaTeX.

I don't know enough about how typst works, but surely it must be somewhat realistic to offer an alternate math environment within its constraints. Such an alternative would be a path towards slowly migrating over to Typst-style math, without the abrupt change required currently.

This came up in https://github.com/typst/typst/discussions/252, but I didn't want to go further off-topic there than necessary

**Comment by user202729** [comment]
I think if Typst's scripting language is strong enough it is already possible to use some syntax such as `#math("\sin \theta \times \cos \phi")` then implement the `math` function in Typst's scripting language to do the appropriate replacement.

Of course, the detail is the difficult part.

**Comment by johanvx** [comment]
I think that _migration guides_ and _cheat sheets_ are currently better solutions, since it may be easier for the community to do the `LaTeX -> Typst` translation work than to participate directly in the code development of Typst. As the community grows up, an official, community-driven `LaTeX -> Typst` translation web app can also be built.

As mentioned on the official website, package management for Typst is coming soon. So in my opinion, once it is available, supporting LaTeX-style syntax via package may also be a good solution. Again, it may be easier to write packages than to do code development.

**Comment by user202729** [comment]
For the users yes, for the developers probably not (e.g. users stick to LaTeX style and never switch to Typst style -- after all, LaTeX style is very prevalent in real life despite it making easier for users to have bad typographic convention e.g. `cos` interpreted as `c ⋅ o ⋅ s` instead of the operator by default).

Maybe a better alternative would be to provide LaTeX-named _aliases_ for symbols. Then migration from LaTeX to Typst is simply "do the same thing but add liberal spaces and don't type the `\`"

Still, I predict the system, if successful, will grow in somewhat "LaTeX-style" way:

* user familiar with the scripting language but not with Rust
* write packages to their needs

The thing being done right here is _this_ programming language is a saner language to program in than TeX (and it's not just because this "resembles" a "normal" programming language more, I'm familiar with programming in TeX and know what the bottlenecks are), so *users* won't write *ugly* fragile code that clashes with all other packages.

One problem is that the syntax is not as "customizable" as TeX (`=` always denote heading, etc.), but it might actually be better (usually people don't need very-weird syntaxes anyway) and with custom handling of triple-quoted code block it may not be too bad.

Speaking of which, some of my thoughts... implicit global state (e.g. `\escapechar`) causes a lot of fragile code in TeX. Here we don't have implicit global state apart from `#set` directive, not sure how bad it will be.

**Comment by Dreamingnoisy** [comment]
I support this opinion as well. Typing math equations in LaTeX style is quite easy once you get familiar with it and I personally do not want to learn another style.  Even TeXmacs, which is a great LaTeX alternative, keeps the LaTeX math style. I do not think keeping LaTeX math style would be a disadvantage for Typst.

If we compare these two different math styles, we can find that users can  write some symols with fewer typings in LaTeX than they do in Typst (e.g. $\mathring A$, with LaTeX you only need to type "$\AA$", but we need to type whole "$angstrom$" with Typst. I also notice that Typst has a lot of dot notations to represent symbols, which is a truly consistent way but not concise enough. This is a huge con for Typst at least for me, I definately do not want to bother with those terrible dot notations, users need shorthands to type math efficiently.

Also, I do think we need to distinguish commands and variables in math mode clearly.

**Comment by user202729** [comment]
> Also, I do think we need to distinguish commands and variables in math mode clearly.

Variables and commands is "the same thing", in some sense.

Roughly Typst's language in math mode works like this, in my understanding (unfortunately the documentation is written as a "user guide" for "document writers" instead of "programmers", so programmers are left to figure the working out themselves, in my opinion)

* it's parsed into a "program" with "commands".
* each time a "variable" with type "content" is "executed" in top level, the content is printed on the paper. For example `angstrom` is actually a variable `sym.angstrom` of type `content`.
* similarly, each time a "function" that returns a result of type "content" is "executed", the content is printed on the paper. For example `frac(1, 2)` returns a result of type "content", when it appears in top-level it will be printed on the paper.
* If two objects of type "content" appear "next to each other" the result will be a single object of type "content" consist of these concatenated. Which makes thing like `frac(sin theta, 2)` work -- `sin` and `theta` are both of type `content`, so they're concatenated together and passed to `frac`.

Actually, given rule 4 the whole thing can be simplified to "the whole thing is evaluated to an object of type `content` and printed on the paper.

**Comment by Dreamingnoisy** [comment]
> 

Dear @user202729 ,

Thanks for your explanation.

Yeah, from the persepective of a programmer, these two things can belong to type `content`. However, what I really mean is not about how programming language deals with `content`, but is that using different notations can really improve readability. When you want to go back to check some formulas or equations, some special character like "\\" in LaTeX can make you read the equation codes more easily especailly when there's a long complicated one.  Still, this is only my personal idea.

**Comment by user202729** [comment]
Maybe you can just make your own convention like "prefix all variable names with `_`" or "wrap all variables in `#(...)`"? I think these 2 will work with the current implementation although I haven't tried.

**Comment by Tastaturtaste** [comment]
> Disclaimer: I speak as a mathematician, who is also very excited about the idea of Typst as an alternative to TeX for typesetting.
> 
> I truly believe that in order for Typst adoption to happen to any measurable extent, specifically in mathematics, it _must_ be possible to input at least a subset of mathematics with LaTeX-style syntax. Say, a similar subset to that supported by MathJax today. Changing the syntax for math input, especially short-term, will be a really tough sell for most people (possibly even a deal-breaker), when it's been ingrained over decades. It's become the standard even outside of LaTeX.
> 
> I don't know enough about how typst works, but surely it must be somewhat realistic to offer an alternate math environment within its constraints. Such an alternative would be a path towards slowly migrating over to Typst-style math, without the abrupt change required currently.
> 
> This came up in #252, but I didn't want to go further off-topic there than necessary

I don't think two separate syntax to do the same thing are the way to go. That would only serve to confuse people new to the ecosystem and probably fracture it.   
A in my opinion workable alternative would be a package that defines something similar to a `latex_math` function that takes content with LaTeX math notation and returns the same content with Typst math notation. This would probably lead to worse error messages for the user and make the layout of the equations harder to debug.  
The best way would be a separate application that translates or cross-compiles math from LaTeX -> Typst on a best effort basis. This way the user pastes and sees the Typst code explicitly, which would hopefully translate to better error messages and easier fine tuning of the layout.

**Comment by Enivex** [comment]
I'm not particular about the actual implementation details, I'm just saying there should be _some_ way of entering math with LaTeX syntax. It would make sense for it to be a package.

This would also make migrating a document much easier. For the foreseeable future I can't see journals actually accepting documents typeset with Typst, so anything that will help in the transpilation of Typst -> LaTeX will be very helpful. (Hell, some journals still use _ancient_ dvi based toolchains. Even the preprint server ArXiv was still on the three year old Texlive 2020 last time I checked.)

**Comment by user202729** [comment]
Actually this may already be possible. Just use https://github.com/clarkgrubb/latex-input to enter Unicode characters directly, works for most symbols.

**Comment by Enivex** [comment]
> Actually this may already be possible. Just use https://github.com/clarkgrubb/latex-input to enter Unicode characters directly, works for most symbols.

I fail to see how that would help.

**Comment by user202729** [comment]
Let's say you type `\leftarrow`, then `←` gets typed in your source document `document.typ`, then Typst compiles that into what you want.

If your problem is you don't want to memorize the symbol names of Typst, then it would definitely help.

**Comment by Enivex** [comment]
> Let's say you type `\leftarrow`, then `←` gets typed in your source document `document.typ`, then Typst compiles that into what you want.
> 
> If your problem is you don't want to memorize the symbol names of Typst, then it would definitely help.

That's only a very tiny part of the actual problem. See my last comment.

**Comment by astrale-sharp** [comment]
Hey there everyone,

Here's my two cents on the subject:

- A familiar syntax for everyone.
Typst is less expressive than Latex, it's syntax is more restrictive cause it's not based on macro. I think this is a **good** thing. When you read typst code you know what to expect, always.
Whereas reading Tex you always have to understand what syntax did the author came up with this time. I don't think there should be a core way to do Latex -> Typst in Typst but it could certainly be a library since typst is powerfull enough to do that.

- Typst is powerfull enough to do that already.
A way I would go to write this library (which I won't cause it doesn't interest me, someone else will have to :angel: ).
I'd put block codes like:
````
```LatexMath
$ %whatever you wanna put here 
$
```
````
And use a show rule to match that text, parse it and output a math code block from it. This would mostly boil down to 
- a dictionary translating symbols from latex to typst
- a bit of parsing to understand what your tex/latex output means
which is a lot of work but definitely achievable.

Thoughts?

**Comment by SirNiklax** [comment]
A tool for transpiling from tex to typst is already being developed. See [texmath](https://github.com/jgm/texmath) and [Demo](https://johnmacfarlane.net/texmath.html).
It is not perfect though.
