### ISSUE TITLE
show cite: set text(fill: blue) does not work anymore with the new "Adjacent citations are merged" function

### ISSUE THREAD

**Issue by Fabioni** [typst/typst#2531]
### Description

After updating to the 31.10.2023 version, this problem occurs. The blue text still shows for single citations, just not for the combined ones.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
I believe this is because grouped citations become a new internal element (that isn't `cite`). It'd have to be exposed to be affected by show rules (which sounds reasonable to me, in principle).

Although I wonder if the existing `cite` element could just be adapted to be able to cover both simple citations and grouped citations instead. Maybe not.

**Comment by laurmaedje** [comment]
The reason group is a new element is that instead of the old approach with multiple citation keys is that now every citation can have its own supplement. This wasn't possible before.

**Comment by PgBiel** [comment]
Should we perhaps expose said element then? I'm trying to think of a way around this - some way to preserve `cite` show rules -, but it sounds like we could face way too many bugs in an alternative path...

**Comment by laurmaedje** [comment]
Technically, set rules are supposed to propagate upwards. If all children have a specific style, the parent should, too. This typically works for paragraphs and so on, but it doesn't seem to work with show-set, probably because the comparison that tests this uses pointers for performance and the two show-set styles have different in-memory addresses.

**Comment by Fabioni** [comment]
Any suggestion for a workaround at the moment?

**Comment by Dherse** [comment]
I have managed to determine that the issue resides in `styles.rs`:
![image](https://github.com/typst/typst/assets/9665250/e02d79d4-5b0e-47af-99f8-8462e83745ef)

It appears that, despite the two style chains being identical, it somehow still removes too many elements. Following @laurmaedje's indication that this may be due to unsoundness in the `PartialEq` impl of `StyleChain`, I replaced it with a "native" implementation which did not fix the issue; however it caused a number of issues over quite a few tests, which tells me that there is indeed something wrong with the way style chain equality works.

**Comment by laurmaedje** [comment]
@Dherse did your "native" PartialEq ignore spans?

**Comment by Dherse** [comment]
It did so maybe that's where this issue lies, I don't know :(

**Comment by laurmaedje** [comment]
This was caused by a combination of two things:
- The pointer comparison in the style chain
- `RefElem`s generating metadata that becomes part of the style chain which makes them actually different (this only applies to refs, not direct cites though)

This makes it hard to fix properly. I've pushed a workaround instead for now, where the cite group just uses the styles of the first item instead of using the shared trunk of styles.
