### ISSUE TITLE
Whitespace Between CJK & Latin Not Working Before Line Break

### ISSUE THREAD

**Issue by Verplitic** [typst/typst#2538]
### Description

The feature was added in https://github.com/typst/typst/pull/2334. Normally, it works as intended:

<img width="176" alt="image" src="https://github.com/typst/typst/assets/57583509/0c826c9b-f85c-4d0f-8ab7-d0b541f0396c">

```typ
// src
Typst是一个排版系统
```

However, when there is a line break (`#linebreak()` or `\`), any CJK text immediately before is not spaced. Lines ending with Latin letters are not affected by this glitch:

<img width="270" alt="image" src="https://github.com/typst/typst/assets/57583509/553b46ea-f642-492f-a0a8-c6369c4c9ae5">

```typ
// src
我们能利用Typst做很多事情 \
如plot一些图表 #linebreak()
和管理citation #linebreak()
并produce许多精美的document \
```

Thanks for the attention.

### Operating system

Web app, macOS

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
minimal reproduction:
```
plot一些图表 #linebreak()
```

**Comment by Enter-tainer** [comment]
![image](https://github.com/typst/typst/assets/25521218/5411d545-0707-426b-abda-8e5cc2407a8d)

The space is gone after line_break in L169

**Comment by Enter-tainer** [comment]
The glyph before linebreaking is reshaped in https://github.com/typst/typst/blob/c177a63c9b8b5e57a6ce10f454e809b5474a354b/crates/typst-library/src/layout/par.rs#L1152 and later assigned https://github.com/typst/typst/blob/c177a63c9b8b5e57a6ce10f454e809b5474a354b/crates/typst-library/src/layout/par.rs#L1182 .

When it is reshaped, the x_advance and x_offset is not preserved. So the spacing between latin and cjk is lost. 

It enters this branch because `start + shaped.text.len() > range.end == true`

**Comment by Enter-tainer** [comment]
currently have no idea whether it is desired behavior or not. cc @peng1999 for help :pray:

**Comment by laurmaedje** [comment]
Is the problem essentially this https://github.com/typst/typst/pull/2334#issuecomment-1754801378 even though it shouldn't happen according to this https://github.com/typst/typst/pull/2334#issuecomment-1755029885?

**Comment by peng1999** [comment]
> When it is reshaped, the x_advance and x_offset is not preserved.

The reshape does not make sense. I think `find_safe_to_break` needs to be fixed.

In this part of function:

https://github.com/typst/typst/blob/0f274f8edbbb93d65cb11713f4bdf912b3286800/crates/typst-library/src/text/shaping.rs#L482-L501

When the shaped text contains `"字\n"` (len = 5), and we want to slice the first character `"字"` (range `0..4`), the function fails to handle this situation because
- `range.end != 5`, and
- `\n` produces no glyph, so there is no glyph that starts at index 4.
