### ISSUE TITLE
Uniform Function Call Syntax

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#2558]
### Description

Uniform Function Call Syntax is a feature of many high-level programming languages (notably Nim and ) that simplifies the language for new users by removing the distinction between methods and functions. For example:
```typst
// function(x, y) is not a method--it can be any function!
#x.function(y)  // equals function(x, y)
#method(x) // equals x.method()
```
It fits nicely with the existing dot-syntax for methods, and is especially useful for method discovery thanks to dot-autocomplete.

### Use Case

Besides simplifying syntax, UFCS serves the same role as piping in functional languages (without the downsides mentioned in earlier threads about how `#x |> f` is ambiguous):
```typst
// postfix syntax can be much easier to read
x.f().g() == g(f(x))
```

**Comment by JamesxX** [comment]
I'd absolutely love this, and it would be great for when custom types are implemented, however,

1. What happens when function and x.function both exist, what takes precedence and why?
2. How does this work for dictionary entries that are functions

**Comment by frozolotl** [comment]
<details>
<summary>Terminology</summary>
<p>

- `str.contains` means "a function that takes a value of type `str` as its first parameter"
- a function is free-standing: `func(params)`, while a method is called using dot-notation: `self.method(params)`

</p>
</details>

I think the first point @JamesxX mentioned is really important, but I'd like to give a similar, but still different problem with UFCS in Typst.
Typst is a language that is dynamically typed and where type annotations will likely always be optional, even once they are stabilized. That means, the compiler can't really know which one of two functions with the same name, but different signatures, should be called.

Let's say  `str.contains` is the only method named `contains`. A user could call it like so: `contains(full, sub)` and it would be valid. In the next version, Typst adds `array.contains`. Now, `contains(full, sub)` could call either `str.contains` or `array.contains`. The compiler emits an error because it could not decide which of the two to call. As such, the project no longer compiles.
Backwards compatibility is not a problem while Typst is still in its beta, but it will be an issue sooner or later. I think no longer declaring any methods of the same name, in order not to break this syntax, is not at all feasible.

Possible solutions could be:
- Functions could somehow be designated as being "preferred" or "weak". In the earlier example, `str.contains` could be declared as "preferred", directing all calls to it. In the "weak" case, the opposite would happen and `array.contains` would be declared as "weak" and only be called if no not-weak function existed.
  `array.contains` could now only be called using some disambiguating syntax.
  I think this behavior is awkward, confusing, and error prone and should not be implemented.

- UFCS is only compatible with typed functions. The compiler can easily determine which function to call, based on this information. Any functions where the first parameter is untyped, may not be called as methods.
  In the current proposal, function parameters can be declared to accept multiple different types: `foo(bar: str | content)`. We would have to disallow declaration of all other functions named `foo` that take either a `str` or some subtype of `content` if this one was defined.
  If implemented, generics would also require some consideration.
  I think this can be somewhat confusing to beginners, but should work well enough.

UFCS would also exacerbate another issue that already causes some headaches: conflicting function names. Functions imported from a package would be eligible for being used as methods. For instance, if a user imported a function `contains` from a package, it would override `str.contains` and `array.contains` for virtue of being declared later (or at all).
All method calls on `str` and `array` would direct to that function. Especially if that function took the same types. Users would be fearful about importing functions into module-level scope and library authors would have to take even more care at declaring functions with conflicting names than before.

Let's say the feature is implemented in a way where the standard library's `str.contains` still takes precedence over the user's `contains`. Now, the syntax could no longer be feasibly used to implement extension methods, because any compiler update could just add a method and override the function used by the user. Again, backwards compatibility would be broken.

For these reasons, I don't think UFCS would be a good fit for Typst, even if it might work great for other languages.

**Comment by laurmaedje** [comment]
I fully agree with the points raised by @frozolotl. 

Typst supports UCFS to the extent that it makes sense in a dynamic language (i.e. `"string".contains("val")` is equivalent to `str.contains("string", "val")` and methods are just functions[^1]). The fully-universal alternative seems incompatible with the language.

[^1]: With the exception of mutable methods, which are special.

**Comment by ParadaCarleton** [comment]
> Typst is a language that is dynamically typed and where type annotations will likely always be optional, even once they are stabilized. That means, the compiler can't really know which one of two functions with the same name, but different signatures, should be called.

I'm a bit confused by this; did you mean to say statically-typed? I thought Typst was dynamically-typed, but the problem you're discussing is one for static languages. With a dynamically typed language, if you have two functions with the same name, but different signatures (like `contains(string, object)` and `contains(array, object)`), there's no problem--`contains(x, y)` just calls the right method at runtime by checking whether `x` is a `string` or an `array`. (In a static language, you're not allowed to have an `x` with an unclear type.)

**Comment by ParadaCarleton** [comment]
> Typst supports UCFS to the extent that it makes sense in a dynamic language (i.e. `"string".contains("val")` is equivalent to `str.contains("string", "val")` and methods are just functions[1](#user-content-fn-1-4427a60e2aec4aabd2055cb48e708e0f)).

Right, if that's the case, the only thing missing would be an application to mutable functions. If `x.delete(1)` deletes the first element, `delete(x, 1)` should as well. (If needed, we could require explicit mutability with a syntax like `delete(mut x, 1)` or Julia's `delete!(x, 1)` syntax, although the latter leaves ambiguity about what exactly is mutated in some situations.)

If the problem is that objects can only mutate themselves (to avoid spooky mutation at a distance), it would make sense to require mutating functions to be declared as methods, but still allow users to call them as `delete(mut x, 1)`.

Finally, for addressing ambiguities, I think letting people prepend the type (e.g. `str.contains` vs `array.contains`) to disambiguate between the two is fine. (I'm just a bit confused, because usually the point of dynamic languages is to make disambiguating like this unnecessary; in a dynamic language, the programmer can just write `contains`, and the program will figure out which method needs to be called at runtime.)

**Comment by frozolotl** [comment]
> > Typst is a language that is dynamically typed and where type annotations will likely always be optional, even once they are stabilized. That means, the compiler can't really know which one of two functions with the same name, but different signatures, should be called.
> 
> I'm a bit confused by this; did you mean to say statically-typed? I thought Typst was dynamically-typed, but the problem you're discussing is one for static languages. With a dynamically typed language, if you have two functions with the same name, but different signatures (like `contains(string, object)` and `contains(array, object)`), there's no problem--`contains(x, y)` just calls the right method at runtime by checking whether `x` is a `string` or an `array`. (In a static language, you're not allowed to have an `x` with an unclear type.)

The problem here is twofold:
1. This behavior might work with functions defined by the standard library, because they are actually typed.
  But, a big point in favor of UFCS is that users can define their own extension functions to other types. These functions' parameters might not be typed, however, making this disambiguation impossible.
  See the second point I brought up in my earlier comment as well.

2. What happens if you don't immediately call a function, but pass it around? The compiler/interpreter will only be able to know which function to run once it is called. That means internally, a function value would either be something like a function name, or a list of functions. Not a huge problem per se, but it does seem like it would incur a certain performance slowdown and make the interpreter more complex.

**Comment by ParadaCarleton** [comment]
> 2\. Not a huge problem per se, but it does seem like it would incur a certain performance slowdown and make the interpreter more complex.

Yep, that's what makes dynamic typing slow :sweat_smile: 

The tradeoff is that you get flexibility (sometimes it's just impossible to know the return type of your function without running it) and convenience. In return you give up performance and a good tool for catching bugs.

**Comment by ParadaCarleton** [comment]
Trying to experiment with Typst to figure out what's going on with the typing. From what I can tell, the language is dynamically typed with method-only dispatch. I was confused because I interpreted "methods are functions" as meaning "methods = functions", rather than "methods are a subset of functions." I also think it's a bit of a background thing; my main programming language is Julia, which makes extensive use of multiple dispatch, but the Typst devs come from a Rust background; Rust has method-only dispatch. Let me explain the differences with a few examples.

First, the typing _is_ dynamic:
```typst
#let function(arg) ={
  if arg < 1 {
    return 1
  } else {
    return "hello"
  }
}

#function(2).at(0)
// returns "h"
```

But also, defining a second `function` overrides the first, even if they have different type signatures or numbers of arguments.
```typst

#let function(arg1, arg2) ={
  if arg1 < arg2 {
    return 1
  } else {
    return "hello"
  }
}

#function(2)
// errors, first function is replaced
```
So functions can't do dispatch, unlike methods. Also, you can't have multiple functions with the same name. This means all methods are functions, but not all functions are methods: functions lack some of the features of methods. (Methods are also only kind of functions, because they don't have `method(x)` as syntax--you need to use `str.method(x)`. Namespaced functions, I suppose.) 

This can be fixed by allowing for dispatch via type signatures, like this:
```typst
#let function(arg1, arg2) = {...}
#let function(int arg1, arg2) = {...}
#let function(str arg1, arg2) = {...}
```
Languages with function dispatch use a rule of choosing the most specific method, which lets you avoid having to define the same method several times for different types. So, in this case, the first function gets called whenever `arg1` is not an integer or a string--it's effectively a "default method." Meanwhile, the second and third methods are called whenever `arg1` is an integer or a string, respectively. This behavior is identical to the current behavior; the performance is the same as when you call `arg1.function()`.

Some languages and frameworks (notably Julia and PyTorch) take this a step further, letting you annotate any set of arguments you want. This is great for extensibility; as an example, in Julia, we can add error propagation or units to the language using multiple dispatch:
```julia
function *(x::Float, y::Float)
    # multiplies
function *(x::Float, y::FloatWithErrors)
    FloatWithErrors(x * y.value, x * y.margin_of_error)
```
In cases where you can infer types, this comes at ~no cost.

**Comment by laurmaedje** [comment]
`str.function(x)` isn't different syntax than `function(x)`. The callee just happens to be part of a namespace, in this case the `str` type's namespace. But `str` could just as well be a module and `function` a user-defined function.

The only thing that's special is method syntax which dispatches things to the receiver type's namespace. So `"hello".world()` is roughly equivalent to `type("hello").world("hello")`, because `type("hello") == str`.

**Comment by ParadaCarleton** [comment]
Yep, that's the main difference.

So, my proposal with UFCS is to let `function(x)` dispatch on the type of `x`, by having the user use type annotations. When there aren't any type annotations, the compiler assumes the type can be anything.

**Comment by laurmaedje** [comment]
I'll close this as not planned. Typst already supports the "dumb" form of UFCS (`str.len("hello")` instead of `"hello".len()`) and I just don't see the "smart" form (`len("hello")`) working out nicely in a language as dynamic as Typst.
