### ISSUE TITLE
Array evaluates to empty if not put into content

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#2584]
### Description

I have a hard time describing the issue, when line 4 is commented out the numbering disappears completely:
```typst
#set heading(numbering: (..it) => {
  it = it.pos()
  let vars = if it.len() > 1 {it.slice(1)} else {()}
  [#vars]
  numbering("A.A", ..vars)
})

= Hello
== sub-heading
=== sub-sub-heading
== another
= world
```

![image](https://github.com/typst/typst/assets/137803093/639e12f7-2838-48f8-a6fb-da3cc15e3cc8)
![image](https://github.com/typst/typst/assets/137803093/962d83c8-1c45-4bf4-9b41-a8604835855a)

This happens on 0.6 - 0.9, and possibly earlier, I only tested in the webapp.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
```
#set heading(numbering: (..it) => {
  it = it.pos()
  numbering("A.A",..if it.len() > 1 {it.slice(1)} else {()})
})

= Hello
== sub-heading
=== sub-sub-heading
== another
= world
```
displays as

![image](https://github.com/typst/typst/assets/2191754/b9d8ef83-062d-40c3-a9ac-ef552365eb26)

while

```
#set heading(numbering: (..it) => {
  it = it.pos()
  repr(numbering("A.A",..if it.len() > 1 {it.slice(1)} else {()}))
})

= Hello
== sub-heading
=== sub-sub-heading
== another
= world
```

displays as
![image](https://github.com/typst/typst/assets/2191754/a1762261-fbde-4eb5-a0bc-1704d6456f1d)

**Comment by laurmaedje** [comment]
This is one tricky bug! The problem shows up only because the heading doesn't resolve it's numbering directly (i.e. it does `counter(heading).display(it.numbering)` rather than `numbering(it.numbering, ..counter(heading).at(it.location()))`. I've changed this in https://github.com/typst/typst/pull/3322. However that doesn't fix the underlying problem, it just removes this occurrence.

The root problem can still be observed on this code
```typ
#show heading: it => counter(heading).display(it.numbering)
#set heading(numbering: (..args) => {
  if args.pos().len() > 1 { "_" } else { "" }
})

= A
== B
```
which doesn't converge even though it clearly should. The reason is that the order of the HeadingElem and the counter DisplayElem oscillates. An empty string results in a different metadata order that a non-empty string, yielding different `..args` in the next iteration. This again affects the metadata order and the `..args`, going back and forth.

The fix is to change how query metadata is generated for elements, which I wanted to do anyway for efficiency reasons.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/4212
