### ISSUE TITLE
Typst watch compiles files that are not watched

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2623]
### Discussed in https://github.com/typst/typst/discussions/2622

<div type='discussions-op-text'>

<sup>Originally posted by **mihock** November  8, 2023</sup>
### Description

If  file a.typ is watched and file b.typ in the same directory is changed, file b.typ is compiled to pdf (although this file is not watched). To reproduce:

```sh
echo "This is file a.typ" > a.typ
echo "This is file b.typ" > b.typ
typst watch a.typ
```

Now, if file b.typ is changed, a file b.pdf is produced.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst</div>

**Comment by Enivex** [comment]
I was a bit to quick.....

**Comment by Enivex** [comment]
@alerque @Dherse @mihock

Was this resolved?

**Comment by laurmaedje** [comment]
I'm pretty sure that yes.

**Comment by alerque** [comment]
Yes, this is confirmed resolved. I did some more playing around and am convinced my testing was faulty. That means the entire original issue was caused by an LSP in an IDE, and my "reproduction" of it was a mistake from an over-aggressive shell history completion. I'd done some playing around earlier in the same directory and was `touch b.pdf` was in my history, so it tab completed from `touch b.`<kbd>Tab</kbd>. Of course that *created* the file, and I didn't notice that I'd created it directly, not `typst watch`.
