### ISSUE TITLE
`typst watch` vs. newly creäted and deleted files, causing unresolvable errors and early exits

### ISSUE THREAD

**Issue by SabrinaJewson** [typst/typst#2685]
### Description

1. Create an empty `main.typ` and `typst watch` it
2. Write `#include "somefile.typ"` inside it; `typst watch` will correctly display an error
3. `touch somefile.typ`; `typst watch` will still display the “file not found” error despite this, including if one runs `touch main.typ`
4. Replace `main.typ` with itself, e.g. via the `:w` comand in Neovim; `typst watch` will now permanently display a “cyclic import” error (?), which you cannot get rid of without restarting the command:
	```
	error: cyclic import
	  ┌─ main.typ:1:9
	  │
	1 │ #include "somefile.typ"
	  │          ^^^^^^^^^^^^^^
	```
5. Restart `typst watch`
6. Remove the import from `main.typ`; `typst watch` will correctly not error
7. Delete `somefile.typ`; now `typst watch` will immediately exit with “file not found” error:
	```
	watching main.typ
	writing to main.pdf

	[14:16:49] compiling ...

	error: file not found (searched at /path/to/dir/somefile.typ).
	```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Probably the same as https://github.com/typst/typst/issues/2601

**Comment by laurmaedje** [comment]
I have created https://github.com/typst/typst/pull/2706 as an attempt at fixing #2601. I hope that this would fix the issues where somefile.typ and main.typ are confused by Typst. 

The issue of Typst only picking up `somefile.typ` after an edit in `main.typ` if you imported it before creating it is separate. That's because we can't watch a file that doesn't exist yet, so the creation of `somefile.typ` won't trigger a compilation at all.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/2706 should fix the bug. For the other part, I've opened a new feature request: https://github.com/typst/typst/issues/2714
