### ISSUE TITLE
Extend functionality of `repeat`

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#2713]
### Description

The `repeat` function currently always justifies its content, and does not allow setting a gap between the repeated items. Instead, to add a gap it is necessary to include horizontal spacing inside the repeated item (as in `#repeat[.#h(4mm)]`), which however also includes that spacing in the last element.

I propose the following arguments:

![image](https://github.com/typst/typst/assets/7191192/0f189bb0-df0c-491f-9cfa-21731a245709)

This would also allow integration with `align`. Alternatively, it might be better to get the `justify` property from the current style set for `par`:
```typ
#show repeat: set par(justify: true)
#repeat(gap: 4mm, sym.dot.c)
```

As a workaround, it is relatively easy to write this function in pure typst as I've done [here](https://github.com/EpicEricEE/typst-plugins/blob/b13b0e1bc30beba65ff19d029e2dad61239a2819/outex/src/outex.typ#L1-L27).

### Use Case

Prevent misaligned dots in outline filler:

![image](https://github.com/typst/typst/assets/7191192/5b9aba6f-7d0f-45e1-890b-e5b927677aa3)

**Comment by Dherse** [comment]
I would mention that I am currently working on pattern fills to get closer to closing #2282 and it *may* provide the feature you're looking for in a very efficient way (file size wise) without changing any syntax. I am not saying that I am against this idea, I think it's a good one, but since there's overlap and I feel compelled to mention it.

**Comment by Dherse** [comment]
Now that #2740 is open, I can tell you that it would look like the following:

```ts
#block(
  width: 100%,
  stroke: orange.lighten(90%),
  height: 12pt,
  fill: pattern((12pt, 12pt), spacing: (4mm, 12pt), sym.dot.c)
)
```

And render to the following:

![image](https://github.com/typst/typst/assets/9665250/11eb858c-53cf-49dd-9fd2-5349ed75d8b0)

(the orange outline is just for visualizing where the `block` is)

It's not quite as nice as what you suggested but it will now be possible without requiring any call to `layout` or `style` which *can* slow down document compilation.

**Comment by lkndl** [comment]
I find patterns pretty tricky to get right along both axes; especially because `sym.dot` apparently has an opaque white background. In particular, it would also cut off the repeated element mid-pattern wherever space runs out, so I think it might be worthwile to implement the `par`-dependent `justify` for `repeat` and possibly also `gap`. If this were part of the compiler, would the `layout/style` disadvantage still persist?

Also: sorry for not searching for this issue before opening #2816 :grimacing: !
