### ISSUE TITLE
Italicized letter in qutoes in math mode

### ISSUE THREAD

**Issue by vlmutolo** [typst/typst#2735]
### Description

```
$"P" = "NP"$
```

Produces something like the following:

*P* = NP

Unless there's something I'm missing, I think it should be:

P = NP

### Operating system

Using the web editor.

### Typst version

- [x] I am using the latest version of Typst

**Comment by frozolotl** [comment]
This is sadly a known issue that will be fixed in the future, but there is still some design work to be done.

For now though, you can solve it by typing `$upright(P) = "NP"$` or `$upright(P) = upright(N P)$`.

For more information, see: https://github.com/typst/typst/issues/274 and https://github.com/typst/typst/issues/1125.
