### ISSUE TITLE
Bib parse fails with empty day 

### ISSUE THREAD

**Issue by gaspardbb** [typst/typst#2751]
### Description

When a `.bib` file contains an empty day, parsing fails.
The error is not helpful as the line number corresponding to the problematic entry is not given:
```
failed to parse BibLaTeX file (mybib.bib:0: invalid number)
```

Handling either empty day/month or getting a more helpful error message would be nice. 

```bib
@article{test,
  year        = 2000,
  day         = {},
  month    = {},
}
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by JakobSachs** [comment]
Judging from the code at: 

https://github.com/typst/typst/blob/55799f73952f66b937a75f5e7f99604987238399/crates/typst-library/src/meta/bibliography.rs#L346C47-L346C47

It seems that this is a bug most likely in [`Hayagriva`](https://github.com/typst/hayagriva), since all that typst seems to do is read in the `.bib` file and pass the string to the library. Would probably be best to mark this as an issue over there and not here, if i read the code correctly  (which i might also not be).
