### ISSUE TITLE
Conversion from int to bytes and back

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2868]
### Description

Currently `bytes` can only be constructed from a string or an array of `int` < 256.

For some use cases, especially when interacting with plugins, it would be useful to convert bigger `int` to `bytes` and back (given the length of the `bytes` is correct)

Note that this would require choosing a byte ordering, as to not leave the behavior platform dependent.

### Use Case

Interacting with plugins

**Comment by Dherse** [comment]
I think the primary blocker here is how do we consider endianness? Do we use big endian or little endian?

**Comment by freundTech** [comment]
I think so. 
I would suggest providing an optional argument to switch endianness, but still choosing one as the default.

Web protocols are usually big endian, as they were originally developed on big endian machines, however most modern hardware is little endian.

**Comment by bluebear94** [comment]
Python’s [`to_bytes` and `from_bytes`](https://docs.python.org/3/library/stdtypes.html#int.to_bytes) might be helpful for prior art, though we probably won’t need to support arbitrary lengths since we don’t have bigints.

The other choice would be to have explicit `{to,from}_bytes_<type>` methods, but that might lead to too many different methods.
