### ISSUE TITLE
ballot.x is smaller than ballot

### ISSUE THREAD

**Issue by 1cedsoda** [typst/typst#2879]
https://github.com/typst/typst/blob/9e333e5058f54703fa9be0f34914061be6c8a272/crates/typst/src/symbols/sym.rs#L471
![ballot](https://github.com/typst/typst/assets/29167146/c4dbce9b-8c54-494c-8171-c4f939e796b8)

**Comment by Enivex** [comment]
As I said on Discord, this is because the default math font does not have those symbols. However, I found at least one text font that does ("DejaVu Sans")

![image](https://github.com/typst/typst/assets/2191754/3c63753d-9c33-47a9-8d15-93206274aed6)

Closing this, since it's not really a typst issue.
