### ISSUE TITLE
Add support for djot

### ISSUE THREAD

**Issue by bdarcus** [typst/typst#288]
Perhaps out-of-scope for this project, but thought I'd suggest it.

A stricter, cleaner, more consistent, AND extensible markdown; by the creator of pandoc and commonmark.

https://djot.net

There's even a rust parser.

https://github.com/hellux/jotdown

**Comment by lcnhb** [comment]
It seems both projets have a similar goal, albeit typst has a more thought out extension/math framework. But if both had the same base syntax that would be great!

**Comment by tv42** [comment]
Previously, the argument has been made that Typst is using `= heading` because they wanted to keep `#` as easy-to-type and not very ugly escape into using variables, functions etc in content. Regardless of the specifics (djot or not), I wanted to say this: I think Typst could safely have both `# heading` and `#myvar` simply by saying heading must have a space after `#`. Markdown already allows this, using `#tag` is pretty common in Markdown, and this also seems to be fine with Djot:

> A heading starts with a sequence of one or more # characters, followed by whitespace.

**Comment by laurmaedje** [comment]
We had the at some point and people found it confusing.

**Comment by laurmaedje** [comment]
Not really sure what exactly adding support for djot would mean. Both projects are somewhat similar but in the end separate.

**Comment by bdarcus** [comment]
Just for context:

It would mean being optionally able to use djot files as input; perhaps something vaguely like:

```console
typst --template article.typ test.dj
```

But I posted this issue before https://github.com/typst/typst/pull/461 and https://github.com/jgm/pandoc/issues/8740, which should achieve the same outcome.

Both are still young projects, so admittedly premature.

**Comment by tv42** [comment]
> Not really sure what exactly adding support for djot would mean. Both projects are somewhat similar but in the end separate.

I'd say the biggest benefit to typst would be not maintaining its own markup language, and all the baggage that comes with that (grammar, parser, tests, documentation, users having to know it).

If Djot was expressive enough to cover all of Typsts needs, it would be a larger ecosystem to be part of, instead of forging your own path for everything.

**Comment by mcookly** [comment]
If Djot was used as the markup language of Typst, one could embed Typst code in a [raw block](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#raw-block) to still execute Typst-only commands—while still leaving writers the freedom to jump quickly to other export formats.

**Comment by grantshandy** [comment]
I haven't worked on typst but from what I can tell the devs are trying to express that typst is a project which is specifically a compiler for its own markup language (and a web editor on top of that). Adding support for parsing an entirely different markup language just seems out of scope for the entire project.

Just as a concept, it would make much more sense for you to parse djot into typst's AST and compile it using the library yourself (if you want to create typst-style PDFs/HTML).
