### ISSUE TITLE
[Freature request] SyncTeX but for typst

### ISSUE THREAD

**Issue by SeniorMars** [typst/typst#289]
SyncTeX is an extension for latex engines that allows pdf viewers and tex files to correspond. I would love this feature for the sake of 1) better lsp/editor experience 2) focusing on large files.

Once I finish my neovim extension and treesitter parser, if no one worked on this request, I'll start it myself as I want this feature so baddddlly.

**Comment by reknih** [comment]
The web app actually has this feature! The `ide` module of the compiler exposes the necessary functions a LSP would need to call.

**Comment by Enivex** [comment]
> The web app actually has this feature! The `ide` module of the compiler exposes the necessary functions a LSP would need to call.

I know typing will trigger it, but is there some button I can press to trigger forward search manually?

Also, does it have reverse search?

**Comment by laurmaedje** [comment]
Forward search doesn't exist. We could add a button or menu item for that.

**Comment by Enivex** [comment]
By the way: The automatic forward search seems somewhat inconsistent. If I have my cursor at the end of a line and press enter, then start typing letters, I will have to type two of them before it will react. In some cases it's even three. It happens with enter+f+f+f, so it's possibly connected to ligatures.

Not sure if that's intentional, or if I should create an issue.
