### ISSUE TITLE
Dangerous weak-typing of comparison of types

### ISSUE THREAD

**Issue by user202729** [typst/typst#2920]
### Description

Normally, Typst is strongly-typed, which is good:

```
a: #(1=="1")   // false

b: #(1<"2")   // cannot compare integer and string
```

But not when comparing string and type object:

```
#(type([a])=="content")  // true
```

Even more dangerous, the name of the constant for the type object is not always the same as its string representation:

```
#(type([a])=="content")

#(type("a")=="str")

#(type(1)=="int")

#(type(1.2)=="float")

#(type([a])==content)

#(type("a")==str)

#(type(1)==int)

#(type(1.2)==float)

#content

#str

#int

#float
```

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is temporary behaviour as a grace period for compatibility with earlier Typst versions. It will be removed in a future version. The names are different specifically because that was the old output of the `type` function. See here: https://typst.app/docs/reference/foundations/type/#compatibility
