### ISSUE TITLE
"failed to watch directory"?

### ISSUE THREAD

**Issue by user202729** [typst/typst#300]
I do the following

* create `a.typ` in `/tmp/`
* type `typst --watch a.typ`

then I get the error message.

Side note, it appears that if I do that but from another directory (so `typst --watch ../a.typ`)
it does not give an error but does not watch either.

**Comment by user202729** [comment]
Okay, I realize that the issue is Typst always watch the current working directory (not the directory that contains the file, or the directory specified by `--root`, so if the current working directory is something like `/` (or a symbolic link to `/`) then it will get permission error.)

It would be good if the behavior is configurable, or somehow Typst expose some sort of API into the continuous compiler.

**Comment by FedericoStra** [comment]
I get the same `error: failed to watch directory` even if I run `typest -w main.typ` in the `$HOME` directory.

Unfortunately the pre-built Linux binary does not support `RUST_BACKTRACE=1`, so I cannot (easily) investigate the reason of the failure.

**Comment by laurmaedje** [comment]
I published a new release a few hours ago, which watches the cwd or root instead. Do you have that already?

**Comment by lxndio** [comment]
I have this issue as well. If I supply a root directory via the argument, it works fine. Looking at the code, the problem seems to be that if you don't supply a root directory via the argument and run typst on a file name only as input (e.g. `typst -w main.typ` in any directory), `input` contains only a file name and is not extended to the absolute path of that file because [here](https://github.com/typst/typst/blob/e13fc04c3e973da60d5f4e9cc6fc38105cd2ddf9/cli/src/main.rs#L192) only a parent is returned if it is specified in `input` (e.g. `typst -w ~/typstproject/main.typ`).

Therefore, the watcher fails [here](https://github.com/typst/typst/blob/e13fc04c3e973da60d5f4e9cc6fc38105cd2ddf9/cli/src/main.rs#L218-L220) as `root` is empty. I would propose as a fix that `input` should always be extended to an absolute path if only a relative path was specified. This would cause `root` to be computed correctly and should solve this issue. If you like, I can propose a PR for that.

**Comment by laurmaedje** [comment]
Yes, a PR would be nice

**Comment by femtomc** [comment]
@laurmaedje I'm not sure if a recent commit broke this (I'm on `HEAD`) -- but now watching fails completely, even for single files...

<img width="721" alt="image" src="https://user-images.githubusercontent.com/34410036/228594040-6ef9e4dd-3679-4384-baef-611d27ac8c52.png">

**Comment by user202729** [comment]
@femtomc As explained above now the `--root` is watched instead of the cwd.

[Watch root directory instead of current one · typst/typst@628e589](https://github.com/typst/typst/commit/628e589bcda538f5f5d7666a4c9ba82ce3ee66df)
