### ISSUE TITLE
Boxes in footnotes move the numbering down

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3067]
### Description

The following markup:
```typ
text then a footnote#footnote(box[This is the footnote's content \ it contains two lines])
```
Produces the following output:
![Rendered using Typst-Renderer on the official Typst Discord server. https://discord.com/channels/1054443721975922748/1056574658771681361/1188849114524438660](https://github.com/typst/typst/assets/40892795/b24c53bd-38b5-4b48-a28e-05b8d7c3258d)

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
Actually I figured out a rather robust/compatible fix with
```typ
#show footnote.entry: it => pad(x: 1em,
  counter(footnote).display(num => [
    #let number = super(numbering(it.note.numbering, num), baseline: 0pt)
    #place(top, number)
    #hide(number)
  ]) +
  h(-1.5pt) +
  it.note.body
)
```
But I figure for a real solution we'd have to sort of 'float' the footnote numbering to the top.

**Comment by Leedehai** [comment]
I took a look at the code I think `#footnote(box[This is the footnote's content \ it contains two lines])` puts the number at the intended place, because Typst faithfully executed this piece of code
```rust
        Ok(Content::sequence([
            HElem::new(self.indent(styles).into()).pack(),
            sup,
            HElem::new(number_gap.into()).with_weak(true).pack(),
            note.body_content().unwrap().clone(),
        ]))
```
It's just that the following `box` content is so tall, that the superscript appears to be on the second line while both the number and the box content are in fact on the same line:
```
   +-------+
   |       |
+--+       |
|  |       |
+--+-------+
```
---

Maybe `box` is not suitable to be placed in a footnote content. I think what the users really want (and what you probably tried to get with `box`) is an option to apply the indentation to all lines of the footnote content, not just the first line (status quo):
```typ
footnote#footnote[First line\ second line]
```
<img width="210" src="https://github.com/typst/typst/assets/18319900/3cbb3d33-43a8-4a47-8bdd-c8ecdb06f132">

Desired results (https://tex.stackexchange.com/a/411456):
<img width="500" alt="Screenshot 2024-01-15 at 20 09 37" src="https://github.com/typst/typst/assets/18319900/2c3795b6-ea6b-4f42-99e9-62705b5e3d12">

**Comment by emilyyyylime** [comment]
Of course, I am not claiming this is a code bug; I understand where the issue arises from. That said, I am still pointing it out here as a particular pain point where I would not want the box's excess content to stray above the line.

What you suggested is indeed one important application of boxes in footnotes, though in my case I was actually trying to get the list-like behaviour of constraining the end edge of the container to exactly fit its content. Perhaps I could've tried hacking a list to make this work.

Another remark is that generally 'make x equal to y' is a relationship that is very hard to currently express with Typst—whether it be specific positions or dimensions

**Comment by emilyyyylime** [comment]
Indeed in this case a sufficient solution would be the ability to specify something like `box(baseline: top)`

**Comment by laurmaedje** [comment]
Since this is in principle working correctly and we also have https://github.com/typst/typst/issues/2905 already, I'll close this as a mix of working-as-intended and duplicate.
