### ISSUE TITLE
Implement `calc.approx_eq()` and friends

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3119]
### Description

Hi - I'd like to propose implementing `calc.approx_eq(a, b)`, `calc.approx_ge(a, b)`, and `calc.approx_le(a, b)` where the arguments are `float`s (and it covers `int` as well since it can be converted into `float` implicitly).

Reason: visualization or drawing-related use cases often need to compare `float` with a certain number. The usual `==` may be inaccurate because of floating point imprecisions. These helper functions can help with that. The algorithm can be https://floating-point-gui.de/errors/comparison/. I can help with implementing it.

Of course, this proposal still doesn't address the issue of floating point imprecision accumulated from arithmetics (as mentioned in https://floating-point-gui.de/errors/propagation/), but I think it's a separate issue that can be left to the users and package authors.

Related:
* https://github.com/johannes-wolf/cetz/issues/431
* a question is Discord "In Typst, how to correctly compare floating point values x <= y?"

### Use Case

Help with comparing floating point numbers. This is especially useful in drawing and visualization packages.

**Comment by frozolotl** [comment]
In this comment I will solely focus on implementation details and a bit of API design.

The algorithm used in the article you mentioned does not always perform well. I recommend reading up on that in Comparing Floating Point Numbers[^1].

To my knowledge, there are mainly two crates implementing both relative and ULPs-based floating comparison: `float-cmp`[^2] and `approx`[^3].
I personally prefer `float-cmp` for its a bit nicer API design and better code. From what I can gather, both crates implement the same algorithms, however.
In particular, an implementation should use `float_cmp::ApproxEq`[^4] instead of any particular algorithm for the reasons outlined in the article I mentioned earlier[^1].

It might also be reasonable for `calc.approx-eq` to allow the user to specify the error margin. This is also done in `float_cmp`, where users can provide an epsilon and the number of ULPs[^4][^5].

[^1]: https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
[^2]: https://crates.io/crates/float-cmp
[^3]: https://crates.io/crates/approx
[^4]: https://docs.rs/float-cmp/latest/float_cmp/trait.ApproxEq.html
[^5]: https://docs.rs/float-cmp/latest/float_cmp/struct.F64Margin.html

**Comment by PgBiel** [comment]
Thanks for the first link @frozolotl , I am now fully convinced that floats and chaos are synonyms. 😂

I haven't had time to read it fully yet, but what a ride it is so far...
Maybe there isn't that much we can do about this problem in the end, but we can at least _try_ :P

**Comment by Leedehai** [comment]
Since Typst's `float` is always 64 bit long under the hood, so we can utilize `float-cmp`'s `a.approx_eq(b, F64Margin { ulps: ..., epsilon: ... })` and provide API

```typ
#calc.approx-eq(a, b, ulps: 4, epsilon: /* Rust's f64::EPSILON */)
```
The default values of `ulps` and `epsilon` follow that crate's [`F64Margin::default())`](https://github.com/mikedilger/float-cmp/blob/a2fdd37eebdebf560110978813f31675292c23aa/src/eq.rs#L198).

**Comment by Enivex** [comment]
Comparing floats with equality is just fundamentally problematic. I feel like this is just putting lipstick on a pig

**Comment by laurmaedje** [comment]
I'm not really convinced that this should be in the standard library. There are various ways to approach floating point problems and I don't want to pick and bless one. The operations can be implemented and experimented with in third party library after all.

**Comment by frozolotl** [comment]
I myself am not entirely convinced if this is something the standard library should have either, but I'd still like to bring up a few points.

> Edit: After reading it fully, we should definitely heed its warning:
> 
> > If you are comparing two arbitrary numbers that could be zero or non-zero then you need the kitchen sink. Good luck and God speed.

This is actually what the API @Leedehai and I proposed does. It first performs a normal equality check, if that yields `false`, an "abs-diff" one, and finally if all else fails, a ULPs based one.

> It seems that `float-cmp` has several options in this regard. Perhaps that should be exposed to the end user as suggested, as floats are a complicated thing, but I wonder how much of it should we expose - it should also not be too complicated to use / have good defaults.

So, with the proposed API, a user effectively has four options:
- `calc.approx-eq(a, b)`: uses the default behavior
- `calc.approx-eq(a, b, ulps: 0)`: effectively does not perform the ULPs-based check
- `calc.approx-eq(a, b, epsilon: 0.0)`: effectively does not perform the epsilon-based check
- `calc.approx-eq(a, b, ulps: x, epsilon: y)`: whatever is precisely desired

This does not include a relative epsilon check, but I'm not sure this is useful when we have ULPs.

> The operations can be implemented and experimented with in third party library after all.

That is not actually the case due to the way the ULPs-based comparison works: It functions on the numbers' constituent bits.
To my knowledge, Typst does not feature a `float.to-bits(x)` function yet.
If that one was added—ignoring its limited use in Typst—I would completely agree.

Well, there _is_ one solution to the problem: convert the float to bytes using `cbor` and manually decode the resulting array.
That does seem a bit hacky though.

If we ignore ULPs, users can implement an approximate float equality function without any hacks, though.
ULPs and the relative epsilon approaches behave largely the same with normal floats, which might be all that is necessary, after all.

**Comment by Leedehai** [comment]
> Comparing floats with equality is just fundamentally problematic. I feel like this is just putting lipstick on a pig

But that is indeed necessary in some use cases - there's very hard to avoid the ugly pig, so we have to put lipstick on it..

For instance, given a parameter `t`, sometimes we'd like to know whether it `0 <= t <= l`, where `l` is the length of a curve. In this case, a properly implemented `calc.approx-eq()` is needed, because comparing `0 <= t <= l * 1.0001` has the drawbacks as mentioned in the above articles.

**Comment by laurmaedje** [comment]
> That is not actually the case due to the way the ULPs-based comparison works: It functions on the numbers' constituent bits. To my knowledge, Typst does not feature a `float.to-bits(x)` function yet.

Aside from the complication that Typst doesn't have a 64-bit unsigned integer type, I would prefer that in principle since it's a more primitive and less opinionated operation from which various things could be derived.

**Comment by Leedehai** [comment]
> > ... Typst does not feature a float.to-bits(x) function yet.

> Aside from the complication that Typst doesn't have a 64-bit unsigned integer type, I would prefer that in principle...

If we want to go with the `to-bits(x)` route, how about outputting a string of 64 `0` or `1` characters instead?

**Comment by laurmaedje** [comment]
I think that would result in very inefficient but manipulation code. Maybe we can just convert to a signed integer. The bits are the same after all, it just affects the semantics of some operations.

**Comment by Leedehai** [comment]
Though I implemented `to-bits()` in the PR above, I personally still prefer `approx-eq(epsilon: <default-value>, ulp: <default-value>)`, for it is the most intuitive to users.

Honestly I can't think of a practical case where the epsilon+ULP solution isn't enough. Typst is a typesetting program and not meant to be a Swiss knife for scientific computing, after all, so I believe it makes sense to go along with the most intuitive & widely used method, given that striving to be technically "neutral" leads to a half-baked solution (I doubt people will use `to-bits()` to build their own, better comparator). Moreover, `approx-eq()` in the float-cmp crate already goes beyond naive epsilon-based comparison.

Also, while I agree floating point equality comparison is messy and should be avoided if able to, but in some cases it's just hard to avoid.. like in visualization packages. If Typst doesn't provide a way to compare floating points, they will probably do their own anyway -- and less accurate, e.g. a naive epsilon-based solution, with drawbacks mentioned in the above articles.

That's my case for `approx-eq()` over `to-bits()` 🙂 (or, why not provide both?)

**Comment by laurmaedje** [comment]
After skimming the discussion again, I remain of the opinion that if anything we should expose a lower-level primitive instead of approximate comparisons themselves.
