### ISSUE TITLE
Line `dash` property also affects following SVG image

### ISSUE THREAD

**Issue by Hofer-Julian** [typst/typst#3135]
### Description

The following code behaves different than expected

```typst
#box(
    height: 20pt,
    image("calendar.svg")
)

#line(length: 100%, stroke: (paint:rgb("#cbd5e1"), dash: "dashed"))

#box(
    height: 20pt,
    image("calendar.svg")
)
```

I would expect the SVG to be rendered the same twice, but that is not the case

![grafik](https://github.com/typst/typst/assets/30049909/15c34470-d99a-487d-9ea1-6b039850e59e)

### Reproduction URL

https://github.com/Hofer-Julian/typst_reproducer

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
that's interesting. i will take a look

**Comment by Enter-tainer** [comment]
I just comfirmed this only happens in pdf export. SVG and PNG export are OK. @LaurenzV can you take a look when you have time?

**Comment by LaurenzV** [comment]
I'll try, but might be a while until I get to it. But I'm 90% sure that the problem is that Typst sets the line stroke as "dashed" in the PDF stream and it's not resetted in `svg2pdf` (since by default it assumes that the line stroke is solid), so that's probably why this is happening. But I'll have a look once I find the time.

**Comment by LaurenzV** [comment]
Okay it was just a one-line fix. Will mark this issue resolved once it's been upstreamed.

**Comment by laurmaedje** [comment]
@LaurenzV can this be closed?

**Comment by LaurenzV** [comment]
Yup, just double checked!
