### ISSUE TITLE
`mid(|)^2` is not scaled

### ISSUE THREAD

**Issue by Doublonmousse** [typst/typst#3184]
### Description

The following code

```
// mid(|)^2 is not scaled
$
lr({ integral mid(|)^2})
$
```

produces
![reproduction lr](https://github.com/typst/typst/assets/115779707/758b32d8-6e44-44e3-af05-46351e6b7850)

Where the symbol in the `mid` is not scaled

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
A note on implementation: 

When the `LrElem` is being laid out, the enclosed `mid(|)^2` is an laid-out `AttachElem` already. If at this point we reach inside this `AttachElem` and stretch the vertical bar somehow, the position of the superscripts/subscripts need to be recalculated as well, bascially meaning we must re-layout this `AttachElem`.

`LrElem` is a special math element in that one child element can affect another child element's layout. But it might need a bit more work to fix, since currently all math elements are laid out on their own without considering their siblings.

**Comment by Leedehai** [comment]
A workaround is `$ { lr(integral |)^2 } $`.

Actually, I think this workaround makes sense, because semantically you really want to stretch the vertical bar as high as the integral symbol, instead of stretching the vertical bar as high as the the highest content in the brace -- though in your particular use case these two happen to have the same intended effect, because the integral bar is the highest content in the brace.

**Comment by mkorje** [comment]
I agree that this shouldn't be considered a bug, and `$ { lr(integral |)^2 } $` makes sense.

> Plus, there's an open question that what if, after recalculating the positions of the (super|sub)scripts, the `AttachElem` is higher than the other elements -- should this `LrElem` be stretched even higher? This becomes a positive feedback loop (credit to @EpicEricEE). But if we don't recalculate those positions, the output look is still undesired.

I concur that trying to reach in and scale the `mid(|)` will just cause more problems. Because of the attachment, what the result should be isn't well defined. The workaround @Leedehai gives makes it clear what the result should be.
