### ISSUE TITLE
Math operations on length types

### ISSUE THREAD

**Issue by admercs** [typst/typst#3209]
### Description

I would like to request support for math operations on length types through automatic type conversion of `int` and `str` types to `length` types. Rather than producing an error, the compiler would automatically convert `int` and `str` types in math operations with `length` types to `length` types of the same unit of measure (cm in this case). That is possible by constructing a length type from either.

### Use Case

This would work as follows:

```typst
#let a = 5 - 3cm
#let b = 4cm + "5"
#let c = 5 / 5cm  // already works
#let d = 5cm * 5  // already works
```

This already works for multiplication and division, odd that addition and subtraction are not supported. Hence, this change would improve consistency of unit conversion for mathematical operations.

**Comment by PgBiel** [comment]
I think this wouldn't make much sense, because multiplication and division are fundamentally different (in terms of units) from addition and subtraction.

Multiplying a length by a number makes sense, because you're not changing the unit in any way - you could think of `5 * 5cm` as `5 * 5 * 1cm` for example, whereas `5cm * 5cm` would result in something like 25 cm^2 (an area unit), so that's an error since Typst doesn't have area units. But `5 + 5cm` doesn't make much sense, because `5` doesn't have a defined unit. For instance, `5pt + 5cm` would yield one result entirely different from `5cm + 5cm`. `5 + 5cm` is, therefore, ambiguous at best, invalid at worst.

Regarding `4cm + "5"`, I don't see why adding a length to a string should produce anything meaningful, since strings convey text, not numbers. You can use `4cm + eval("5cm")` if you prefer.

**Comment by andreasKroepelin** [comment]
Note that `3 / 3cm` does not work, but `3cm / 3` does.

I think the way calculating with units currently works is very reasonable and your suggestions, frankly, are not. `2 * 3cm` means "give me twice the length of 3 cm", as if you had two sticks with length 3cm and joined them. Similarly, `6cm / 3` can be thought of "If I split a distance of 6 cm in three equal parts, how long is each part?"
There are no such natural interpretations for something like `3 + 4cm`. It is like - proposing that 3 kilograms plus 4 seconds should equal 7 kilograms. Now, you could argue that your suggestion works with numbers with and without a unit, not with two units. But consider two situations where such a magic conversion would obviously be problematic:

- `1cm + 3 + 4pt`: Now what unit is `3` supposed to have? `cm` or `pt`?
- ```typ
  #let my-length = 4pt
  // lots of code in between ...
  #let other-length = my-length + 2
  ```
  Here, the unit of `2` would depend on some variable defined far away, making the behaviour hard to predict.

Oh and about automatically converting strings... That one is even more problematic. Consider reading code like `"4cm" + 5`. Now, is that supposed to evaluate to `"4cm5"` or `9cm`?

**Comment by admercs** [comment]
Hallo Jena Lichtstadt @andreasKroepelin 

I could not disagree with either of you more 💯 

How does multiplication and division make sense whereas addition and subtraction do not? They are fundamentally the same in terms of parsing logic (i.e., applying mathematical operators to a `length` and an `int`). The behaviour should be consistent and abstracted across any potential operator using Rust traits.

The case that you mention (`1cm + 3 + 4pt`) is also undefined for multiplication and division (`1cm * 3 * 4pt`). So, that argument is a moot point.

Why support one operator but not another? Das macht keinen Sinn.

**Comment by andreasKroepelin** [comment]
@PgBiel I did not realise that you already commented on this, so sorry for basically repeating your points.

 
> How does multiplication and division make sense whereas addition and subtraction do not?

Because they are a different kind of operator, as @PgBiel and I explained. Another way to think about that: Putting a unit on a number is basically multiplying by it. So `3cm == 3 * cm`, in a way. You can therefore argue `2 * 3cm == 2 * (3 * cm) == (2 * 3) * cm == 6 * cm == 6cm`. This is fundamentally different than addition or subtraction.

> They are fundamentally the same in terms of parsing logic (i.e., applying mathematical operators to a `length` and an `int`).

Well, that holds for `3 ^ 2cm` or `3 << 2cm` as well. It's "just" some binary operator. But the syntactical similarity alone does not lead to semantical equivalence.

> The case that you mention (`1cm + 3 + 4pt`) is also undefined for multiplication and division (`1cm * 3 * 4pt`). So, that argument is a moot point.

Well, `1cm * 3 * 4pt` _has_ a mathematical definition. This again comes down to units essentialy being a factor, as explained above. As @PgBiel said, these units of area are just not defined in Typst.

> Why support one operator but not another? Das macht keinen Sinn.

Please stick to English in such public conversations to allow everyone to follow them. (The quoted German sentence means "That doesn't make any sense." for anyone wondering.)

**Comment by PgBiel** [comment]
> The case that you mention (`1cm + 3 + 4pt`) is also undefined for multiplication and division (`1cm * 3 * 4pt`). So, that argument is a moot point.

Adding `1cm + 4pt` works because they are both absolute length units, and `1cm` is converted to `28.35pt` under the hood (write `#1cm` in your document to see), so `1cm + 4pt` is evaluated as `28.35pt + 4pt` which is equal to `32.35pt`. Multiplying 1cm by 3 by 4pt is mathematically defined and would produce the equivalent of `12(pt * cm)`; since `1cm` corresponds to `28.35pt`, you'd get `12 * 28.35 pt^2` aka `340.2 pt^2`, which is an area measurement. Typst does not have support for area units, which is why it errors (it's not undefined, just not supported). This is mostly a mathematical thing, nothing Typst can do (at least, it would be inconsistent).

With that said, you can just write `1cm.cm() + 3 + 4pt.pt()` to remove the units and convert the whole expression to a unitless float, which can be operated on, if you prefer.

> Why support one operator but not another? Das macht keinen Sinn.

This is how calculations with dimensions work, according to mathematicians and physicists (not us, or Typst for that matter); for a reference, you can take a look at https://en.wikipedia.org/wiki/Unit_of_measurement#Dimensional_homogeneity for some initial info (or a book on the subject).

**Comment by PgBiel** [comment]
> @PgBiel I did not realise that you already commented on this, so sorry for basically repeating your points.

Don't worry about it, I think your explanation was pretty good.

**Comment by laurmaedje** [comment]
It's been explain very well why things are the way the are, so I'm going to close this.

**Comment by admercs** [comment]
It seems I've entered into an echo chamber somewhere in Deutschland, vielleicht im Ost. ;)

It is obvious that addition and subtraction work fundamentally the same as multiplication and division in the presented case. Both apply the unit of measure from the `length` value, whether converted or in original form. One multiplies/divides that value, the other adds/subtracts. Hence, _there is no difference for all practical purposes_. It is obvious that `4 * 1cm` means `4cm` while `4 + 1cm` means `5cm`. And yes, you could easily extend this abstraction to other operators that differ in nature. Why not? This is a software engineering matter, not mathematics and/or physics matter. I would not conflate the two.

If the length units are all converted to points under the hood, and that is the real reason for the pushback, then the same conversion can be applied to the value being added/subtracted. This should be easy enough to do using Rust Traits for operator overloading, as shown here: https://doc.rust-lang.org/rust-by-example/trait/ops.html. Perhaps you are not using Traits for this currently, but I would argue that this would allow the Typst language more flexibility in the future.

I love Typst and have been promoting others to try it ever since it was released. This is just one pain point in the language that could be easily resolved.
