### ISSUE TITLE
Confusing error message, expected "a or b, found b".

### ISSUE THREAD

**Issue by MightyHelper** [typst/typst#3232]
### Description

Hi, this is my first report, all suggestions welcome. I looked for other open issues mentioning this and found https://github.com/typst/typst/issues/1231 and https://github.com/typst/typst/issues/3154, but they are for other error messages.

Whatever the problem may be, I don't think this error message is very helpful.

Code:
```typst
Hi
#block(
  outset: (
    before: 0.5em,
    other: 0.2em
  ),
  [Hi]
)
```
Failing in typst web editor
![image](https://github.com/typst/typst/assets/32612290/84932470-cc31-44a4-b290-0860851830b5)

I also get the same error message when running typst locally from the docker image (typst:latest) on Linux.

Bonus: Clicking replace with dictionary changes the code, but the compiler still produces the same error.
![image](https://github.com/typst/typst/assets/32612290/c1cf221b-7a07-4728-98d5-aaa443217b3b)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
That error definitely needs improvement, yeah. I believe the docs for outset[^1] need improvement as well. The problem here appears to be that you are specifying a dictionary with unrecognized keys (`inset` and `outset` only accept certain keys in the dictionary).

In particular, you're probably looking for `(left: 0.5em, rest: 0.2em)`.

[^1]: https://typst.app/docs/reference/layout/box/#parameters-outset

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3247
