### ISSUE TITLE
Indexmap deprecation warning when compiling

### ISSUE THREAD

**Issue by Enivex** [typst/typst#3378]
### Description

![image](https://github.com/typst/typst/assets/2191754/dd92182e-a4ac-4131-8ede-8465cdb1f7d2)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
The original but deprecating `IndexMap.remove()` method swaps the target element with the last element of the map and then pops it off. Its equivalent is the `.swap_remove()` method, so we can just use this to preserve the existing behavior.

However, [dictionary](https://typst.app/docs/reference/foundations/dictionary/)'s `.keys()` and `.values()` are supposed to return the keys/values in the insertion order. But currently it's not the case due to the swap-remove behavior.

So maybe we should use `IndexMap.shift_remove()` instead? But this is an O(n) operation since it shifts the elements.

I guess @laurmaedje 's input is needed.

**Comment by mattfbacon** [comment]
I agree, indexmap is suboptimal for many use cases. Using this in such a core location is a bit problematic. Not sure if there is any ready-made alternative (there is linked-hash-map, but it's full of unnecessary unsafe code and unmaintained), so we might need to do more research and implement something custom.

**Comment by Leedehai** [comment]
I think _for now_ let's use`.shift_remove()`? It keeps the promise of maintaining the insertion order, and I think the O(n) cost isn't that big an issue because Typst is a typesetting tool not a general programming language that could be used for large applications where O(n) vs O(1) can have a difference.

**Comment by laurmaedje** [comment]
Agreed
