### ISSUE TITLE
Grouping of Adjacent Citations not working

### ISSUE THREAD

**Issue by AnsgarLichter** [typst/typst#3483]
### Description

I am writing my thesis with typst. So far I am very satisfied with this project, thanks!

Unfortunately grouping of adjacent citings are not working for me. 
As I have seen in #1606 this should work if the csl requires it.
I am using the default `ieee` citation style and also tried the [ieee.csl](https://github.com/citation-style-language/styles/blob/master/ieee.csl). With both citation styles a grouped citation is rendered like `[1], [2]`. My expected output is `[1, 2]`. As far as I know IEEE it requires to group adjacent citations (at least my professor would like to have this).

Can you please fix this bug or is my syntax wrong?

## Example
```typst
= Grouped Citations

I want to look the citation like [1, 2] but it is being rendered as @Smith.2020@Smith.2020a

#bibliography("file.bib")
```

Results in:
![image](https://github.com/typst/typst/assets/43957906/70beaf28-145d-4cff-aabd-166bde6e2bd3)

### Reproduction URL

https://typst.app/project/rPorvfcEOHdDwSjiKUsFNd

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is intentional, and in accordance with IEEE.

http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf page 4

![Screenshot_20240223_103412_Firefox.jpg](https://github.com/typst/typst/assets/2191754/69e35c12-243e-404d-9aad-ec337393914e)

**Comment by laurmaedje** [comment]
If you really need this, you could look into downloading the IEEE CSL file from [here](https://github.com/citation-style-language/styles/blob/master/ieee.csl) and adjusting it ([CSL spec here](https://docs.citationstyles.org/en/stable/specification.html)). Or maybe you can find a different style that matches more closely what you want.

**Comment by AnsgarLichter** [comment]
@laurmaedje thanks for this tip. If my understanding is correct the following part in the default CSL specifies that the group should be rendered as `[1, 2]`. As the `[` should be a prefix for the group and `]` should be a suffix for the group. Is my understanding valid?

```xml
<!-- Citation -->
  <citation>
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter=", ">
      <group prefix="[" suffix="]" delimiter=", ">
        <text variable="citation-number"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```

**Comment by DaanSchlosser** [comment]
Hey, since this is related and I wanted my citations to look slightly different: If you add another line at the top, subsequent numbers also get collapsed, so that [1, 2, 3, 4, 7] becomes [1-4, 7] instead. 

```
<!-- Citation -->
  <citation collapse="citation-number">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout prefix="[" suffix="]" delimiter=", ">
      <group delimiter=", ">
        <text variable="citation-number"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```

**Comment by andreikee** [comment]
## Working solution via custom CSL (tested with Typst 0.14.2)

For anyone landing here: the root cause is that the **stock `ieee.csl` places `prefix="["` / `suffix="]"` on the inner `<group>` element**, so each citation number gets its own independent brackets even when citations are grouped at one point. Typst's CSL engine *does* implement `collapse="citation-number"`, but only fires when the brackets are on `<layout>` — not on inner elements.

### The fix

Create a local `ieee-grouped.csl` (copy of stock `ieee.csl` with two edits to the `<citation>` block):

```xml
<citation collapse="citation-number">
  <sort>
    <key variable="citation-number"/>
  </sort>
  <layout prefix="[" suffix="]" delimiter=", ">
    <group delimiter=", ">
      <text variable="citation-number"/>
      <text macro="citation-locator"/>
    </group>
  </layout>
</citation>
```

Compared to the stock `ieee.csl`:
1. `collapse="citation-number"` added to `<citation>`.
2. `prefix="["` / `suffix="]"` moved from `<group>` → `<layout>`.

Then reference it in your document:

```typst
bibliography: bibliography("refs.bib", style: "ieee-grouped.csl"),
```

### Results

| Input (adjacent keys, no space) | Before | After |
|---|---|---|
| `@k1@k2@k3` (consecutive) | `[1], [2], [3]` | `[1–3]` ✅ |
| `@k1@k3` (non-consecutive) | `[1], [3]` | `[1, 3]` ✅ |

Multi-citation syntax in Typst: use **adjacent `@key1@key2@key3`** (no spaces between keys). Note that `#cite(<k1>, <k2>)` with multiple positional labels does **not** work in Typst 0.13/0.14 ("unexpected argument" error).

### One-liner to generate the patched file from the canonical source

```sh
curl -s https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl \
| sed 's|<citation>|<citation collapse="citation-number">|' \
| sed 's|<layout delimiter=", ">|<layout prefix="[" suffix="]" delimiter=", ">|' \
| sed 's|<group prefix="\[" suffix="\]" delimiter=", ">|<group delimiter=", ">|' \
> ieee-grouped.csl
```

(Verify the patch with `grep -A10 "<citation" ieee-grouped.csl` after running.)
