### ISSUE TITLE
Inconsistent spacing on footer with par block spacing

### ISSUE THREAD

**Issue by nonrg** [typst/typst#3518]
### Description

Using `#show par: set block(spacing: 0.55em)` make first footer taller:
![typstbug](https://github.com/typst/typst/assets/105008263/940e6195-b560-4931-8b29-637f3871d097)

Code:
```typst
#show par: set block(spacing: 0.55em)

title page

#set page(
  footer: {
    line(length: 100%)
    lorem(5)
  },
)
  
#pagebreak()

#counter(page).update(1)

page 1

#pagebreak()

page 2
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Curiously, if I remove `#counter(page).update(1)` then the issue disappeared.
```typ
#show par: set block(spacing: 0.55em)

title page

#set page(
  footer: [
    #line(length: 100%)
    footer
  ],
  margin: (bottom: 5em),
)

#pagebreak()
#counter(page).update(1) // Remove this line, then the issue disappeared
page 1
#pagebreak()
page 2
```

**Comment by Leedehai** [comment]
I think the issue is not that `#show par: set block(spacing: 0.55em)` made the first following page's footer taller, but rather, it is that the show rule is only applied to the non-first following page's footer.

This can be made evident by `#show par: set block(spacing: 0.1em)`. From logging I observed that when laying out the first footer, there is an 12.0pt absolute spacing inserted before the footer content, and when laying out the second footer, that absolute spacing is reduced to 1.0pt (tests.rs set the text font size to be 10pt, so 1.0pt corresponds to 0.1em).
```
flow.rs layout_item Absolute(12.0pt, true)
flow.rs layout_item Frame { frame: Frame [Text("footer")], ...
...
flow.rs layout_item Absolute(1.0pt, true)
flow.rs layout_item Frame { frame: Frame [Text("footer")], ...
```

**Comment by laurmaedje** [comment]
Doesn't happen anymore with `set par(spacing: ..)`.
