### ISSUE TITLE
Non convergence: place() seems to change here()

### ISSUE THREAD

**Issue by memeplex** [typst/typst#3614]
### Description

This doesn't converge, it keeps pushing the box downwards and abort after 5 iterations. Should the absolute positioned box change the result of here()?

0.11.0:

```typst
#let f() = context {
  place(
    top + right,
    dy: here().position().y,  
    square(width: 10pt),
  )
}

#lorem(50)#f()
```

0.10.0:

```typst
#let f() = locate(loc => {
  place(
    top + right,
    dy: loc.position().y,  
    square(width: 10pt),
  )
})

#lorem(50)#f()
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by AxiomOfChoices** [comment]
I could be wrong but I think this is working as intended, the `here` function grabs the location of the current scope, which in this case surrounds the square. Thus the `here` function will grab the location of the square itself and cause the box to be pushed downwards. 

To circumvent this you need to give the `here` function an _anchor_ to grab onto, so in 0.11 placing an invisible box will do the trick:
```
#let f() = context {
  place(top+left,box())
  let cur_y = here().position().y;
  place(
    top + right,
    dy: cur_y,  
    square(width: 10pt),
  )
}

#lorem(50)#f()
```
![image](https://github.com/typst/typst/assets/14252368/3af9f877-09e5-4754-a151-d33895ff9ca0)

All that being said I feel like this is not ideal behavior, assuming my understanding of the situation is correct, the location of the scope of a context should probably be fixed to the location where it is called.

**Comment by memeplex** [comment]
FYI: https://discord.com/channels/1054443721975922748/1088371867913572452/1216316471584751647

@laurmaedje

**Comment by memeplex** [comment]
> the here function grabs the location of the current scope, which in this case surrounds the square. Thus the here function will grab the location of the square itself and cause the box to be pushed downwards. To circumvent this you need to give the here function an anchor to grab onto, so in 0.11 placing an invisible box will do the trick

I'm trying to wrap my mind around this. Truth is that I'm very new to Typst. In what sense is this invisible box more of an anchor than the content than previously preceded the square? And why the new scope won't be surrounding everything  (invisible box + here + square) now as it supposedly was before?

**Comment by AxiomOfChoices** [comment]
I'd have to wait till I have more free time to play with the source code and see how exactly this works, or see what @laurmaedje has to say, but my understanding is this:
The scope of the context is everything placed inside of the context, so in the original case this is just the square, so the abstract syntax tree looks something like this.
![image](https://github.com/typst/typst/assets/14252368/4b34f113-ce90-48a7-badf-6642f45021d0)
The `here` function grabs the location of closest node of the tree to its left and then above it, so in the original case it grabs the location of the context scope itself. Now the context scope only contains the square so its location after the square is placed is the same as that of the square, it wraps itself around the square. So the `here` ends up getting the location of the square.

On the other hand in the situation with the invisible box the syntax tree looks like this.
![image](https://github.com/typst/typst/assets/14252368/b5e9ea8b-61a5-4899-9b9f-77f8a0a716cf)
Now when the `here` function runs it finds the box first and so it grabs its location instead of that of the context, and that location is fixed so it is independent of the number of iterations.

**Comment by laurmaedje** [comment]
I would classify the current behaviour as wrong. If you use `here` inside of a show rule for an element, it should grab that element's proper location. However, with an explicit context block, it attaching itself to the first contained element rather than being free-standing is more a result of the current implementation than intended behaviour.
