### ISSUE TITLE
(0.11.0-rc1) Polylux slide with `v` and overflowing `box` results in compilation loop and OOM

### ISSUE THREAD

**Issue by fuine** [typst/typst#3641]
### Description

I'm not sure if this is connected to a bug in `polylux`, but the following code compiles using `typst` version 0.10 and results in a seemingly endless loop/recurrence which constantly allocates more memory, ending with OOM on my machine after allocating roughly 60GB using `0.11.0-rc1`.

```typst
#import "@preview/polylux:0.2.0": *
#set page(height: 100mm, width: 100mm, margin: 0mm)

#polylux-slide[
  #v(10mm)
  #box(height: 200mm)
]
```
The issue is present for both `0.2.0` and `0.3.1` versions of `polylux`. Note that if either the `v` or `box` call is commented out the document compiles without issues. It also compiles if the sum of `v` and `box` heights is less than or equal to the size of the page (so that the box isn't overflowing).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Bisected to: https://github.com/typst/typst/commit/ba531c371e61e34607bb1e3aa911e2529dac7b35

**Comment by PgBiel** [comment]
> Bisected to: [ba531c3](https://github.com/typst/typst/commit/ba531c371e61e34607bb1e3aa911e2529dac7b35)

I'd wager that the call to `self.regions.in_last()` isn't reliable here to detect when to stop finishing regions (since the box would never fit into the page). It's possible that there is some extra stuff being added at the top of each new region (page), causing this problem. I've faced a similar issue when implementing repeatable headers, and the solution was my `in_last_with_offset` function, which stops finishing regions if there are no upcoming regions and there is a header above us (not if the page is empty).

However, one would have to run a debugger to confirm that the while loop in the commit is indeed just repeating forever.

**Comment by PgBiel** [comment]
Of note, it'd be useful to run timings (`--timings`) for a bit so we can verify what's the bottleneck here (could also be a problem in polylux itself).

**Comment by laurmaedje** [comment]
> The fact that an item could be laid out each time after finishing a region makes me even more suspicious of this (although there is the drain call).

The carry was indeed the problem. The `in_last` in itself should be okay, I think. The closest thing to headers in flow layout are floats, but those are also guaranteed to be drained over time (one by one if necessary) and then we _do_ want to keep finishing regions. I'll open a fix PR.
