### ISSUE TITLE
above of block doesn't work at the top of the page

### ISSUE THREAD

**Issue by Gn3po4g** [typst/typst#3647]
### Description

here's my code:
```typst
#show heading: set block(spacing: 30pt)
#rect(width: 100%, height: 100%, stroke: 2pt)[
  = heading
  content
]
```
the result is:
![QQ截图20240313135752](https://github.com/typst/typst/assets/92096903/a988cfde-eb56-43ab-8e43-63de8267f9b0)
but it's supposed to look like this:
![QQ截图20240313135925](https://github.com/typst/typst/assets/92096903/04c69154-385d-44ab-bb9f-b5d3819e41ca)
any solutions?

### Reproduction URL

https://typst.app/project/rXgX00NkyXkVTZ0e9Hqb4i

### Operating system

Web app, Windows

### Typst version

- [x] I am using the latest version of Typst

**Comment by caemor** [comment]
I removed the spacing because I didn't see the need for it in your picture, because it adds spacing outside the inner rectangle/block/box. For the block you need to add some stroke (e.g. `1pt` here, default none) and I also added your inset on the y-axis to 30pt.
```
#show heading: set block(stroke: 1pt, inset: (y: 30pt))
#rect(width: 100%, height: 100%, stroke: 2pt)[
  = heading
  content
]
```
The result:
![image](https://github.com/typst/typst/assets/11088935/e0c8b889-5c7d-46fe-b0f7-34ff15127976)

**Comment by Gn3po4g** [comment]
> I removed the spacing because I didn't see the need for it in your picture, because it adds spacing outside the inner rectangle/block/box. For the block you need to add some stroke (e.g. `1pt` here, default none) and I also added your inset on the y-axis to 30pt.
> 
> ```
> #show heading: set block(stroke: 1pt, inset: (y: 30pt))
> #rect(width: 100%, height: 100%, stroke: 2pt)[
>   = heading
>   content
> ]
> ```
> 
> The result: ![image](https://private-user-images.githubusercontent.com/11088935/312359068-e0c8b889-5c7d-46fe-b0f7-34ff15127976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg2NzQsIm5iZiI6MTcxMDMxODM3NCwicGF0aCI6Ii8xMTA4ODkzNS8zMTIzNTkwNjgtZTBjOGI4ODktNWM3ZC00NmZlLWIwZjctMzRmZjE1MTI3OTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZDQ4OTJlYmE5YTkzYWRjYTM2NzFhYzc4NTJmNTY4Zjk1Y2U0MmY1MzVlMDJiMGNlZDc3YTNkNTljNDBlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQ4m1U3sQKVxLk7HAwqSarw_XNxOoh03C2ud2IcExHk)

sorry, stroke seems to be confusing. i mean spacing: 30pt is not spacing the top of the block from the top of the page.
i want it to work like this:
```
  #v(30pt)
  = heading
  #v(30pt)
  content
 ```

**Comment by laurmaedje** [comment]
The `above`, `below`, and `spacing` properties of block produce [weak](https://typst.app/docs/reference/layout/h/#parameters-weak) spacing because, which intentionally collapses at the top of a page, as it's not typically desirable to have the spacing at the top of the page.

You can write a show rule like:
```
#show heading: it => {
  v(30pt)
  it
  v(30pt)
}
```
to force non-weak spacing around the heading.
