### ISSUE TITLE
Text and regex selectors don't match smart quotes

### ISSUE THREAD

**Issue by refparo** [typst/typst#3693]
### Description

Selectors `"\""`, `"“"`, `"”"`, `regex("[\"“”]")` look like they would match quotes. However, since smart quotes are not parsed as text, they can not match smart quotes.

### Reproduction URL

https://typst.app/project/r7oyVGYN6XGbYraxhPGoGP

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/86

**Comment by davystrong** [comment]
Just to add to my previous comment, while I still think it's unintuitive that this regex doesn't work, I have since discovered the incredible power of `show:` commands, without any filters. Ultimately one can bypass any other limitation by manually processing the whole document. Again, blown away by how configurable and fun Typst is!
