### ISSUE TITLE
Spontaneously occuring deformed block stroke 

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#3700]
### Description

```typ
#block(
  radius: 1mm,
  stroke: (left: green+15.9mm)
)[
  This is a test...
]

#block(
  radius: 1mm,
  stroke: (left: green+16.1mm)
)[
  This is a test...
]

#block(
  radius: 1mm,
  stroke: (left: green+16.0mm)
)[
  This is a test...
]
```

When I try to render this in the web app (v0.11), i get a distortion on the 3rd box.

![image](https://github.com/typst/typst/assets/8210233/6b815af0-f001-4b5b-926b-aa3740f0064c)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Beiri22** [comment]
Sometimes it's not so drastic...
![image](https://github.com/typst/typst/assets/8210233/3d409181-d013-41b8-b17a-10e487008b08)

**Comment by Tom4sCruz** [comment]
I've been testing out this bug and realized that, most of the time, one can change the length units (from mm to pt, e.g.) and it fixes the issue, so I believe the issue is in the conversion of values somehow. I've been looking around the code, mainly in the crates/typst/src/visualize directory, but got nowhere. Have any idea of where the bug may be?

**Comment by Tom4sCruz** [comment]
I've fixed the issue for when the stroke has a length of 16mm, 17mm, 1.71cm, etc. (some values that I tested that had this issue), but this only passes the bug on to other values. So, in order to fix it for every value, the stroke rendering code itself is what needs to be fixed. Would I be correct to say that the issue must be in src/visualize/shape.rs or in src/visualize/stroke.rs? (This bug also only happens in blocks where the stroke side is referenced)

**Comment by Tom4sCruz** [comment]
I've solved it. It was because of the way the mid-outer corner was calculated. For values where the discriminant of the quadratic formula was negative, the value of t would be NaN and thus not working. Do I need to add a test for this specific bug or may I just make a PR with the fix?

**Comment by laurmaedje** [comment]
Nice! Best to open a PR with a fix and a regression test in tests/typ/bugs.
