### ISSUE TITLE
Allow use of for loop in table with table.cell() calls

### ISSUE THREAD

**Issue by zakhenry** [typst/typst#3737]
### Description

Example:

```
#let table_range = (
  range(0x00, 0x0b),
  range(0x10, 0x1d),
  range(0x20, 0x21)
)

#table(
  columns: 16,
  for (y, row) in table_range.enumerate() {
    
    for (x, cell) in row.enumerate() {
  
      table.cell(str(cell, base: 16), x: x, y: y)
       
    }
  
  }
)
```

Actual: prints the cell content all in the first cell
Expected: prints each of the fields in their respective cells

Workaround: a more complicated iteration?

### Use Case

This is most useful for filling in tables that have cells in known locations and sparse data.

**Comment by T0mstone** [comment]
It should work if you change the `table.cell()` to `(table.cell(),)` and add a `..` before the first `for`.

For loops don't just repeat what's in them at the syntax level, they "join" the results. This is good, because if that result is content, the contents will be combined as content. By wrapping you cell in `(_,)`, you make it into a single-element array, which makes the for loops join them as arrays, so the whole for loop gives you a single array of cells, which you can then spread into the function arguments using the `..` operator.

**Comment by zakhenry** [comment]
Ah cool yep confirmed the following works:

```
#let table_range = (
  range(0x00, 0x0b),
  range(0x10, 0x1d),
  range(0x20, 0x21)
)

#table(
  columns: 16,
  ..for (y, row) in table_range.enumerate() {
    
    for (x, cell) in row.enumerate() {
  
      (table.cell(str(cell, base: 16), x: x, y: y),)
       
    }
  
  }
)
```

I think I just need to get my head around nearly everything being an expression (which is an awesome design choice btw)
