### ISSUE TITLE
Syntax highlighting wrong with single backtick

### ISSUE THREAD

**Issue by A-Walrus** [typst/typst#3738]
### Description

When code blocks with a single back tick have syntax highlighting applied, the results can sometimes be weird, this was especially noticeable with comments/

``````typ
#set raw(lang:"python")

// good
```
# comment
for i in range(10):
  print(i)```

// bad
`# comment
for i in range(10):
  print(i)`
``````

![image](https://github.com/typst/typst/assets/58790821/fc0cd4d2-c89a-4389-8f31-1ac32697c9fe)

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Hi, this is because content in a single-backtick pair is treated as one line, despite linebreaks in the content. I can confirm by printing the `line`: https://github.com/typst/typst/blob/41db766b83bad4c4671423c03c5e54f308032e7b/crates/typst/src/text/raw.rs#L386

and observeing `"for i in range(10):\n  # comment\n  print(i)"`.

Code blocks are identified by triple-backtick pairs, not by linebreaks in the content. For another example, in the code snippet below, both `# comment` and `print(i)` are given the color of comment, because in Typst's view this is not a code block.
```typ
#set raw(lang:"python")

`for i in range(10):
  # comment
  print(i)`
```

Therefore, I'd say this issue is WAI.

**Comment by laurmaedje** [comment]
I think I disagree. The fact that it's not block-level doesn't mean that lines shouldn't be highlighted separately.

**Comment by Leedehai** [comment]
> The fact that it's not block-level doesn't mean that lines shouldn't be highlighted separately.

Hmm, but in lexer.rs `raw()`, only `blocky_raw()` does the line-splitting operation with `split_newlines()` (and then perform a series of ops on the individual lines) , when there are more than tree backticks. If the backticks are fewer, i.e. the raw content is not recognized as "blocky", then there is no "trimming or extra fancyness", which sounds like processing as is.
https://github.com/typst/typst/blob/41db766b83bad4c4671423c03c5e54f308032e7b/crates/typst-syntax/src/lexer.rs#L272-L279

**Comment by laurmaedje** [comment]
Raw text with single backticks are not really intended to be used in a multi-line scenario as they are an inline objects. Can be seen below:
```typ
#set raw(lang: "python")

// good
alpha ```
# comment
for i in range(10):
  print(i)``` beta

// bad
alpha `# comment
for i in range(10):
  print(i)` beta
```

However, if they still span multiple lines, highlighting should account for that in my opninion. It's just that nobody considered this case before, so the code in the lexer doesn't handle it.
