### ISSUE TITLE
Chained method calls should be able to be commented out

### ISSUE THREAD

**Issue by zakhenry** [typst/typst#3746]
### Description

I'm starting to do much larger and more functional functions, and sometimes need to comment out a filter or similar chained method off array, but it doesn't work and I have to delete the line to get the outcome I'm after

Example:

```
#let demo = {
  range(1, 20)
  // .filter(calc.even)
  .map(x => str(x, base: 16))
}

#demo
```

Expected outcome: the filter method is omitted, the output is just the range shown in hex
Actual: error 
```
This markup in “main.typ”…
…caused this problem:
Unexpected dot
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
Interestingly, it works if you replace the braces by round parentheses:

```typ
#let demo = (
  range(1, 20)
  // .filter(calc.even)
  .map(x => str(x, base: 16))
)

#demo
```

This is still an issue, though.

**Comment by laurmaedje** [comment]
Yes this works because parentheses only contain one expression where braces can contain multiple.

**Comment by Enivex** [comment]
> Yes this works because parentheses only contain one expression where braces can contain multiple.

Does allowing this cause any ambiguity though?

**Comment by laurmaedje** [comment]
Not really, since there is already a special case for when the next line starts with a dot.

**Comment by Leedehai** [comment]
Minimal repro that can be handled by the Discord channel's bot-corner:

---
```typ
#{
  (1,2)

  .first()
}
```
works, output is `1`.

---
```typ
#{ (1,2)/*comment*/.first() }
```
works, output is `1`.

---
```typ
#{
  (1,2)
  // comment
 .first()
}
```
results in the error as described, "unexpected dot".

**Comment by Leedehai** [comment]
Minimal repro that can be handled by the Discord channel's bot-corner's `?r` as well as `?ast`:

---
These run:
```typ
(A)
#{
  "1"

  .at(0)
}

(B)
#{ "1"/*comment*/.at(0) }

(C)
#{
  "1" // comment
 .at(0)
}
```

---
These don't: "unexpected dot".
```typ
(D)
#{
  "1"
  // comment
 .at(0)
}

(E)
#{
  "1"
  /* comment */.at(0)
}
```

It appears that in example (D), the parser did not `eat()` the newline and comment as it is supposed to, at https://github.com/typst/typst/blob/a33d8bf32208ef0fe8556200dd0c9c5a1ad10c54/crates/typst-syntax/src/parser.rs#L788 because it thinks `"1"` is followed by a `SyntaxKind::Eof`, which can't be `skip()`-ed.

In example (A) though, the parse did `eat()` the newlines so the parser arrives at the dot.
