### ISSUE TITLE
table does not correctly size cells with respect to styles of cell body elements

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#3864]
### Description

Notice how the cell in the first example is wider than the in the second example, where an explicit newline is inserted. Removing the raw show rule collapses the upper first example back into a single line. It seems the size calculation is done without the raw show rule.

```typst
#set page(margin: (inside: 4cm, outside: 3cm))
#show raw.where(block: false): box.with(inset: (x: 0.25em))

#figure(
  table(columns: 3,
    table.header[Typ][Statisch][Dynamisch],
    [Array], [`std::array<int, 10>`/`int arr[10]`], [`std::vector<int>`],
    [Stack], [-], [`std::vector<int>`],
    [Hash Map], [-], [`std::unordered_map<int, int>`],
  ),
  caption: [Statische und dynamische Datenstrukturen in C++.],
)

#figure(
  table(columns: 3,
    table.header[Typ][Statisch][Dynamisch],
    [Array], [`std::array<int, 10>`/\ `int arr[10]`], [`std::vector<int>`],
    [Stack], [-], [`std::vector<int>`],
    [Hash Map], [-], [`std::unordered_map<int, int>`],
  ),
  caption: [Statische und dynamische Datenstrukturen in C++.],
)
```

![image](https://github.com/typst/typst/assets/137803093/1fb8946b-5323-49a9-b9e7-dbe754423a2f)

This happens on the web app at the time of writing this (0.11.0), as well as on typst-preview with the following version:
```
typst-preview
Build Timestamp:     2024-03-25T13:38:09.901507948Z
Build Git Describe:  v0.11.3-dirty
Commit SHA:          c623b767d4b9f4968692fe5c9173d2c6be6f47d6
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I think in principle everything is working as intended, though it may not be immediately clear why it's behaving as it is:

In the first example, there is no explicit line break, so the cell would in theory like to take up enough space to fit everything into one line. However, that would exceed it's available budget since the "Dynamisch" column also needs space. So, the space is evenly distributed to both, but then the box doesn't fit. The cell _is_ now unnecessarily wide, but the cell _wanted_ more space, it just didn't get all that it wanted (because life). There is no concept of "give me more x space, but if I can't have all of it, don't give me anything at all". I guess one could consider this a bug, but I think this kind of logic would be very difficult to support.

If you remove the raw show rule or set the box inset to 0, then the raw text fits into the available size budget (the inset adds just too much width).

If you add an explicit line break, the cell doesn't request more space in the first place, so it doesn't get it.
