### ISSUE TITLE
Place moves elements in equations

### ISSUE THREAD

**Issue by SolidTux** [typst/typst#3883]
### Description

According to the [documentation](https://typst.app/docs/reference/layout/place/)

> Placed content will not affect the position of other content.

But when used in formulas, it sometimes does, e.g. in the following (the lines were added later as a visual guide)

```typst
$ a + integral + b $
$ a + #place([]) integral + b $
$ a + integral #place([]) + b $
```
![Place Bug](https://github.com/typst/typst/assets/17935831/b83293f2-6e25-4058-b7f5-ac25e52ec985)

```typst
$ a + x + b $
$ a + #place([]) x + b $
$ a + x #place([]) + b $
```

![Place Bug_x](https://github.com/typst/typst/assets/17935831/ea544d77-58e5-40c0-83af-55c039890c78)

Interestingly, the integral is affected on both sides, while "x" is not.

### Reproduction URL

https://typst.app/project/rcQ92feEk7mtqL0OOia2IA

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is covered by https://github.com/typst/typst/issues/3159

**Comment by SolidTux** [comment]
Is there some discussion already somewhere of something like place that would work in these situations without affecting the layout?

**Comment by Mc-Zen** [comment]
Hi @SolidTux ,
actually the issue lies somewhere else and I think it's not quite the same as #3159. It mostly has to do with spacing in math which follows many different rules to enable a nice formatting of math expressions. 

Consider your second example:
```typ
$ a + x #place([]) + b $
```
This adds a space between `x` and `+` because spaces in math mode are removed and only at certain places added to separate special operators. Removing the space after the `x` fixes it: 
```typ
$ a + x#place([]) + b $
```
Otherwise the space is kept between `x` and the placed element. 

Your first example works differently and removing the spaces won't change anything. This is because of how the binary `+` operator is treated. I'm not into the details of the implementation by any means but it has to do with the [math classes](https://typst.app/docs/reference/math/class/) that certain symbols assume by default. By putting the integral sign next to the plus, the group is not recognized as a binary relation and `+b` is shown too tight. If you add a `place()` element there, it forms the counterpart to the `b` on the other side of the plus symbol and according spacing is applied. 

It is possible to change this behaviour by applying a class to the placed content. Try `"unary"` for example:
```typ
$ a + integral class("unary", #place([]))+b $
```
This will give you the exact same spacing as `$ a + integral +b $`. 

I hope this helps in understanding why your code behaves the way it does. It is definitely possible to `place()` in math mode but you need to be careful sometimes because the placed content is not treated as if it where not there but rather like a (although zero-width) box.
