### ISSUE TITLE
Certain svg files are not rendered correctly in (and only in) PDF output

### ISSUE THREAD

**Issue by karuboniru** [typst/typst#3962]
### Description

When including certain `.svg` figures in document, the rendered plot contains strange unexpected grid-ish overlay on it.
![图片](https://github.com/typst/typst/assets/3437889/61aa21ca-5ddf-4cc8-aef3-4220e40ea60f)

While the plot should be (and it is in png/svg output):
![图片](https://github.com/typst/typst/assets/3437889/0f48255f-933b-4817-9ee0-645779c0fe67)

The svg file is generated by [CERN ROOT](https://root.cern/) by plotting a `TH2D` and print it to svg. 
### Reproduction URL

https://typst.app/project/rYCaZh2SSZiVuQna4xtrHs

### Operating system

Web app and Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This seems like a PDF viewer issue at first, since there are tons of rectangles adjacent to each other. It's possible those artifacts would go away depending on the zoom level.

Cc @LaurenzV

**Comment by LaurenzV** [comment]
I get it in Firefox and Preview, but not in Chrome and Acrobat... I'll try to look into it when I find the time.

**Comment by LaurenzV** [comment]
Yeah... I don't think there is much we can do about this from our side. I think the issue is that the SVG uses some floating point numbers for the positioning, so it looks like this for some reasons leads to seeing parts of the background (which is white) in some PDF viewers. But it doesn't happen in Chrome and Adobe Acrobat. But you get the same result if you convert the SVG to PDF with Firefox/Chrome:

Chrome:
[chrome.pdf](https://github.com/typst/typst/files/15047949/chrome.pdf)

Firefox:
[firefox.pdf](https://github.com/typst/typst/files/15047950/firefox.pdf)

So I'm afraid there isn't much we can do from our side, sorry. :/
