### ISSUE TITLE
Citation formatting fails in table.header

### ISSUE THREAD

**Issue by SeSodesa** [typst/typst#4023]
### Description

When I try to compile a typst document that has a citation in a `table.header` ([link to offending commit][the-doc]), I get the following error message:
```sh
[15:03:11] compiled with errors

error: failed to format citation (this is a bug)
   ┌─ main.typ:69:42
   │
69 │   [Summary of forward vs. inverse problems @söderholm2024peeling],
   │
```
I don't know if this is a problem with `table.header` itself or in the way that I've defined a `frame` template function in the file `tau-presentation.typ`, but it would be cool if this could get resolved.

[the-doc]: https://gitlab.com/SeSodesa/tau-typst-presentation/-/commit/cefd297354da39d0f778431177c80ae15f7d9bfa

### Reproduction URL

https://gitlab.com/SeSodesa/tau-typst-presentation/-/commit/cefd297354da39d0f778431177c80ae15f7d9bfa

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Same happens on footers. Strange...

Thanks for reporting.

**Comment by PgBiel** [comment]
Adding `repeat: false` to header or footer fixes it. Additionally, this doesn't happen within unbreakable rows in general (`table.cell(breakable: false)[@citation]` isn't enough to trigger the bug; the cell has to be in a repeated header or footer). So it's somehow related to repeating headers/footers.

I also tested placing a labelled heading inside a repeated table header, and I could still query it, so introspection isn't completely broken.

Paging @laurmaedje for ideas. Are we doing something too cursed with regions, to the point of somehow breaking citations? Very weird...

**Comment by PgBiel** [comment]
I've tested further, and this only happens in the first page of the table with a repeated header. That is, if you write

```typ
#table(
   table.header([#context { if here().page() == 1 [nothing here] else [@citation] }]),
    ...
)
```

it won't error and will display normally, unless you add the citation on the first page as well.

In a perhaps similar fashion (at least on the surface), for footers, this only happens if the table has only one page. Otherwise, the citation displays normally across all of a footer's repetitions, including the final appearance of the footer, at the last page of the table.

**Comment by bluebear94** [comment]
Taking a look at this issue. It seems that the offending citation group element sometimes shows up with a different location.

**Comment by bluebear94** [comment]
I’ve found that the citation group element is getting two different locations because `elem.children[0]` has a different disambiguator in its location. I thought that discounting a content’s location from its hash would fix it, but there’s still the problem of having different disambiguators for the citation group element itself, so this probably isn’t the correct solution.

**Comment by bluebear94** [comment]
Replacing line 234 of `crates/typst/src/layout/mod.rs`:

```diff,rs
-            let mut locator = Locator::chained(locator);
+            let mut locator = Locator::new();
```

makes this bug not manifest, but this obviously isn’t a desirable solution.

**Comment by laurmaedje** [comment]
Perhaps the error happens because the assigned locations don't line up across measurement and true layout. If it is indeed this, the problem is explained in the "Measurement and Introspection" section in https://laurmaedje.github.io/posts/frozen-state/.
