### ISSUE TITLE
Showybox title frames implode after #4212

### ISSUE THREAD

**Issue by WannesMalfait** [typst/typst#4302]
## The problem

I just compiled the latest version ( 8a9c45e7d4e9f8d7e155c3a90ca07afc65e87238 ) from source, and noticed that my custom theorem environments were looking wrong. After bisecting the issue, I found that this was caused by #4212 . This is possibly related to #4234

## Steps to reproduce

The following code produces a framed box where the title frame is placed wrongly.
```typst
#import "@preview/showybox:2.0.1": *

#showybox(
  title-style: (boxed-style: (:)),
  title: [Title],
)[
  #lorem(50)
]
```
![The title frame becomes part of the main body frame](https://github.com/typst/typst/assets/46323945/e337554a-0228-4481-a108-678503b7b8e9)

This can be "fixed" by adding empty content before it:
```typst
#import "@preview/showybox:2.0.1": *

#lorem(0) // Fixes the issue
#showybox(
  title-style: (boxed-style: (:)),
  title: [Title],
)[
  #lorem(50)
]
```
![The title frame is now properly separated](https://github.com/typst/typst/assets/46323945/a0e2e145-7f6b-4ea0-9973-8b77b0ad237f)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
As mentioned in the PR description, the exact positions yielded by introspection changed a bit due to that PR. It looks like showybox uses quite a bit of introspection to position the title.

The current approach is temporary. Further refactorings will likely change the positions a bit more. If 0.10's output was sensible in this case (I haven't checked yet) rather than showybox working around weirdness, then it will likely be fixed by the end of the refactor.

**Comment by laurmaedje** [comment]
The refactors are finished and it's still broken, so showybox will probably need to be updated (like a bunch of other packages). It's expected that things changed, so I'll close this. If there is some concrete compiler behaviour that seems wrong, that should be reported separately.
