### ISSUE TITLE
Support for installation with cargo binstall

### ISSUE THREAD

**Issue by yodatak** [typst/typst#4388]
### Description

Would love to use simpler typst but it not present in fedora repo and it don't support the install with  cargo binstall typst

i would be cool to support this to make simple install 

Like for debian and other https://github.com/typst/typst/issues/3679

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
One Windows it works with `cargo binstall typst-cli`, don't know about Fedora but I assume it should be similar.

**Comment by alerque** [comment]
All `cargo binstall` does is look for precompiled binaries attached to upstream releases and install those instead of doing a source build like `cargo install` does. In fact it falls back to the latter if binary artifacts were not found.

Typst already attached prebuilt binaries for some platforms to releases, but they are not quite in the default naming scheme binstall expects. I think all that would be required to support it is add some meta data to the Cargo.toml file describing the existing format of artifacts including noting the XZ compression used and the tar file layout.

https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md

**Comment by Coekjan** [comment]
Seems we just need to:
1. add some metadata in Cargo.toml for cargo-binstall
2. publish the `typst-cli` crate when releasing next version

BTW, I think this issue should be labeled "feature request", instead of "bug".
