### ISSUE TITLE
Reached the forbidden condition in the codebase: `failed to format citation (this is a bug)`

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4405]
### Description

```typ
#bibliography("/main.yaml")
// main.yaml:
// ------------
// manual1:
//   type: book
// ------------

#let section-refs = state("section-refs", ())

#show ref: it => {
  if it.element != none {
    if it.target != it.element.key {
      ref(it.element.key, supplement: it.supplement)
    }
  }
  section-refs.update(old => old + (it.target,))
}

#let section-bib() = context({
  let section-refs = state("section-refs")
  let targets = section-refs.at(here()).dedup()
  if targets.len() > 1 {
    targets = targets.filter(x => x != <manual>)
  }
  for target in targets {
    if target == <manual> {
      [#cite(<manual1>, form: "full") <manual>]
    } else {
      cite(target, form: "full")
    }
  }
  section-refs.update(())
})

@1
#section-bib()

@manual
#section-bib()
```

```
error: failed to format citation (this is a bug)
   ┌─ a.typ:29:6
   │
29 │       cite(target, form: "full")
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The error is removed/changed in https://github.com/typst/typst/commit/f91cad7d7829556e24d219e55db7da56a966523f.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Andrew15-5** [comment]
After the mentioned commit, it says:

```
warning: layout did not converge within 5 attempts
 = hint: check if any states or queries are updating themselves

error: key `1` does not exist in the bibliography
   ┌─ a.typ:29:6
   │
29 │       cite(target, form: "full")
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot format citation in isolation
   ┌─ a.typ:29:6
   │
29 │       cite(target, form: "full")
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^
   │
   = hint: check whether this citation is measured without being inserted into the document
```

The second still looks confusing to me.

**Comment by Dherse** [comment]
Is this dependent on the bib file or irrespective of it? If it depends on the file, could you provide it please?

**Comment by Andrew15-5** [comment]
It's right at the top of the code block.

**Comment by Dherse** [comment]
Ugh, my bad I am blind, sowwy :D

**Comment by laurmaedje** [comment]
This error happens because the code is so heavily non-converging that the set of known citations never stabilizes to the point that even in the fifth iteration the compiler doesn't recognize the problematic citation from any earlier iteration. In the final iteration it needs to map every citation to one in the set of all known citations to be able to do global citation formatting.

Notably, the error goes away if you don't redefine the `section-refs` in `#let section-bib()`. Through the redefinition it starts from `none` instead of the empty array which lets the `.dedup()` call fail immediately, leading to the code below not being executed in the first place.

Overall, I'd consider this as not a bug. I intentionally reworded the error and removed the "(this is a bug)" in #4352 since the error shouldn't appear anymore under normal circumstances. It can still appear (typically through measurement, but not exclusively so as seen here) when one does very cursed things.
