### ISSUE TITLE
Extra vertical space in two column list

### ISSUE THREAD

**Issue by m-kru** [typst/typst#4428]
### Description

`typst 0.11.1 (50115102)`

I am not sure if the source of the bug is in the typst compiler or in the https://github.com/andreasKroepelin/polylux package.

```typ
#import "@preview/polylux:0.3.1": *

#import themes.simple: *
#show: simple-theme.with()

#slide[
== Title
#columns(2)[
+ #only(1)[airhdl] #uncover(2)[#text(red)[airhdl]]
+ AGWB
+ #only(1)[AutoFPGA] #uncover(2)[#text(red)[AutoFPGA]]
+ Cheby
+ Corsair
+ #only(1)[FPGA Vendors] #uncover(2)[#text(red)[FPGA Vendors]]
+ hdl_register
+ II & CII
+ IP_XACT
+ Opentitan Register Tool
+ #only(1)[Register Wizard] #uncover(2)[#text(red)[Register Wizard]]
+ RgGen
+ SystemRDL
+ vhdMMIO
+ wbgen2
+ Others (2)
]
]
```

Generated pdf:
![image](https://github.com/typst/typst/assets/26227737/2bd09a55-531e-4bf4-9583-61921d6e55c2)

As you can see, there is an extra vertical space between the item 11 and 12 on the first page.

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is almost certainly an issue with polylux, so I'll close this for now.

**Comment by Enivex** [comment]
Actually, I don't think this is a bug at all. uncover(2) means that the content is still there on the first slide, just hidden, while only(1) means that the content is only there on the first slide. That means that on the first slide, both texts are present in the item, and will overflow on the next line since they do not fit on a single line

**Comment by m-kru** [comment]
You are right, thanks.
