### ISSUE TITLE
Support for loading YAML-files

### ISSUE THREAD

**Issue by P-Andersson** [typst/typst#444]
Typst supports loading data from a variety of standard data formats, but YAML is not one of them. I guess the main reason is that typst Dicts expect a mapping Str -> Value while YAML Mappings can be of any value to any value. 

However, I still think that being able to load YAML data would be useful even if it treats dictionary keys as strings unconditionally. 

What are your thoughts on this? I can implement it myself if you want.

**Comment by laurmaedje** [comment]
Being worked on in #447.

**Comment by reknih** [comment]
Merged

**Comment by jason-sachs** [comment]
I added this comment in Discord, but my employer does not let me access Discord at work, so I'll state it here.

I like the use of YAML, but I would prefer to see the `yaml` object refer to a group of related methods for serialization and deserialization, rather than a standalone method that loads a file (as documented https://typst.app/docs/reference/data-loading/yaml/)

For example:

- `yaml.load_file(some_path.yaml)` returns the loaded yaml file.
- `yaml.load(some_string)` converts the string into an object
- `yaml.dump(some_object)` serializes the object into a string
- `yaml.dump_file(some_object)` serializes the object into a file (if writing to a file is allowed in typst, otherwise don't include this)

**Comment by jason-s** [comment]
As far as use cases for `yaml.dump`, here are a few I can think of, and which I have used frequently in various reports and other cases:

1) You have some hierarchical metadata structure which you would like to show the user. (I use build time, build machine, version control info, etc. in HTML reports that I've generated in Python, and the easiest way to make them readable is to dump them in YAML format.)

2) You have a YAML file for which you would like to show excerpts, so something like:

```
all = #yaml.load_file(...)

Here's part of it under "foo":

#raw(yaml.dump(all['foo']))

Here's part of it under "bar":

#raw(yaml.dump(all['bar']))
```
