### ISSUE TITLE
Partial Evaluation for Huge Documents

### ISSUE THREAD

**Issue by Y-jiji** [typst/typst#4512]
### Brief
Provide a partial evaluation API, with semantics: generate PDF from page $i$ to page $i+m$. 
This feature makes sense only if intermediate results can be offloaded to disk storage. 

### Implementation: Page to Source Mapping
To implement partial evaluation, the compiler has to determine which part of the source should be evaluated from the page range. 
It requires all evaluated expressions to have a pre-computed layout height. By searching a prefix-sum like structure, the compiler can find the part of the code to evaluate for the rendered range and the context. 

### Implementation: Offload Intermediate Results
By peeking into typst codebase a little, I found typst relies on a one-pass VM execution over all expressions with partially cached results. This requires all documents and all intermediate results to be stored in memory, which is prohibitive for huge documents. 
I believe some of the intermediate results can be offloaded to disk storage. It would be better if each file can be compiled into a linkable format and later linked together. This can be done by leveraging module parameters. 

### Implementation: Missing Bits
Functions like `measure` require the layout engine to run first. 
Perhaps allow VM to execute multiple times may solve this problem. 

### Use Case

In plugins like typst-preview, implementing this feature can save a lot of rendering time and memory. I believe this enhancement can benefit user experience. 
I've been writing notes in Typst for several days. I produce 4 paragraphs per day, so in one year, I will have 4*365 paragraphs. To evaluate if typst can still handle my notes after one year, I wrote a python script to generate some content. The preview plugin gets stuck.

**Comment by Enivex** [comment]
> implementing this feature can save a lot of rendering time

I highly doubt that. You would quickly be limited by storage. Even a modern nvme SSD has vastly higher latency and bandwidth than RAM. Not to mention wear.

**Comment by Y-jiji** [comment]
> > implementing this feature can save a lot of rendering time
> 
> I highly doubt that. You would quickly be limited by storage. Even a modern nvme SSD has vastly higher latency and bandwidth than RAM. Not to mention wear.

This feature request is not really about disk offloading 🤣. 
I'm talking about not to generate the whole PDF in-memory when the user is just previewing some of the pages. 
For your concern, by specifying pages to render, only a very small part of the intermediate results will be loaded into memory.

**Comment by Enivex** [comment]
> > > implementing this feature can save a lot of rendering time
> > 
> > I highly doubt that. You would quickly be limited by storage. Even a modern nvme SSD has vastly higher latency and bandwidth than RAM. Not to mention wear.
> 
> This feature request is not really about disk offloading 🤣. 
> I'm talking about not to generate the whole PDF in-memory when the user is just previewing some of the pages. 
> For your concern, by specifying pages to render, only a very small part of the intermediate results will be loaded into memory. 

FYI typst-preview does not use PDF, and doesn't render all pages.

@Enter-tainer

**Comment by Y-jiji** [comment]
But still, all the intermediate records are held in-memory, and used in computation. 
Is that correct?

**Comment by Enter-tainer** [comment]
i feel like this issue is about typst-preview but not typst/typst.

@Y-jiji i suggest you using --timings to measure which part of your document is slow before we discussing potential optimizations.

**Comment by Y-jiji** [comment]
I'm still adjusting the Lorem ipsum size so that typst compiler doesn't crash. 
This is the bench I mentioned: https://github.com/Y-jiji/notizbuch. On the `bench` branch, in the root directory, run `python code/generate-huge-chap.py` will generate a Lorem ipsum project.

**Comment by laurmaedje** [comment]
Properly layouting page n requires to layout all previous page at the least. But the later pages are also required to make introspection work. And the compiler architecture is not at all built to accommodate such a use case. All in all, this is simply not feasible to implement.

**Comment by SkiFire13** [comment]
@Y-jiji I tried your script, here's a couple of findings:

- it is creating ~10000 "tags", each of which corresponding to a 100 words/refs paragraph. This doesn't seem very consistent with the "4 paragraphs a day for a year", since with that pace you would need almost 7 years to write this many paragraphs. It would also contain 200000 references on average, which generally seem to be pretty costly;

- reducing the amount of tags and tasks to 1000 makes it much more manageable, taking 15 seconds to compile. If I remove the references (i.e. make the paragraphs only consist of 100 words) this reduces even further to just 5 seconds, which goes to show how costly references are. Does this number seem more realistic/reasonable to you?

- going from 1000 to 2000 tags/task (with references) increases the compilation time from 15 to 40 seconds, showing that compilation doesn't fully scale linearly;

- your script doesn't ensure labels are unique, which gave me some errors a couple of times (it seems both tasks and tags create labels, but you don't ensure that they are disjoint).
