### ISSUE TITLE
Incorrect introspection in outline for headings using weak page breaks

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#4527]
### Description

The page numbers reported in the outline of the following code are off by one:
```typst
#outline()

#set page(numbering: "I.")
#set heading(numbering: "1.")
#show heading: it => pagebreak(weak: true) + it

= Hello
#lorem(1000)

= World
#lorem(1000)
```

![image](https://github.com/typst/typst/assets/137803093/0ed58aa0-fa53-45cf-bfe8-32dc7117325c)
`World` is located on page `IV.`

This was introduced somewhere between a2c98071 and 34990f7f.

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Coekjan** [comment]
I used `git bisect` to find out that the bug was introduced at a52987a8c26bc13e3db4cc300b8cd9d81eb8a18d .

**Comment by Sagmedjo** [comment]
Please reopen this one. My outline is two sites long, and now the outline is off by one again. Using latest version 0.11.1

**Comment by tingerrr** [comment]
Could you post an MRE?

**Comment by Sagmedjo** [comment]
Sorry, what do you mean by MRE?

**Comment by laurmaedje** [comment]
> I'm using version 0.11.1.

The open/close status of issues reflects the state of the main branch. Please check if the issue persists if you compile Typst from the main branch.

MRE = Minimum Reproducible Example

**Comment by Sagmedjo** [comment]
I've pinpointed the issue: everything was functioning correctly, but I mistakenly relied on a template, assuming it was properly configured. It turns out the creator began the page numbering at 0 and neglected to add page breaks after the outlines, even though the pages were separated. This led to the problem I encountered, but it’s not related to Typst.

Apologies for any confusion.
