### ISSUE TITLE
How does alignment actually work?

### ISSUE THREAD

**Issue by Enivex** [typst/typst#460]
The documentation simply says

https://typst.app/docs/reference/math/

"Formulas can also contain line breaks. Each line can contain one or multiple alignment points (&) which are then aligned."

Coming from LaTeX the following
```
\begin{alignat*}{2}
        a &=b &\quad c&=d\\
        e&=f & g&=h
    \end{alignat*}
```
is displayed as

![image](https://user-images.githubusercontent.com/2191754/228878079-de0ede92-0297-4fa6-8b46-a2c58bba6374.png)

Therefore I expected

```
$
a &=b & quad c&=d \
e &=f & g&=h
$
```
to look similar. However, it's displayed as

![image](https://user-images.githubusercontent.com/2191754/228879117-2cca91e0-36a3-47e5-846f-7fd2daefa26a.png)

Am I missing something?

Is it not based on alternating right and left aligned columns, like in LaTeX? Or is this a bug?

**Comment by Enivex** [comment]
Let me add that I first discovered this because I was trying to create a left-aligned version of this https://github.com/typst/typst/issues/460

But
```
$
mat(&a+b,c;&d, e)
$
```
displayed as 
![image](https://user-images.githubusercontent.com/2191754/228881050-42458f49-7454-47cb-9e32-8127a4bddf22.png)

What I expected to see was what I get from

```
 \begin{pmatrix*}[l]
            a+b & c \\
            d & e
        \end{pmatrix*}
```
which is
![image](https://user-images.githubusercontent.com/2191754/228881317-097a324a-3f81-418c-833e-5e9c045a604c.png)

I'm not entirely certain if these two issues are the same, but both are related to alignment.

**Comment by user202729** [comment]
I feel that the first column is right-aligned, everything after is left-aligned. (which is rather unconventional I think.)

Random opinion: TeX has the `\halign` primitive which is responsible for both alignment in text and math mode (to be fair there's a special case of halign being "display math alignment" but it doesn't make too much difference). Here in Typst, there are 4 -- math alignment, 
math matrix, https://typst.app/docs/reference/layout/grid/, and https://typst.app/docs/reference/layout/table/. Not a good design in my opinion.

**Comment by Enivex** [comment]
> I feel that the first column is right-aligned, everything after is left-aligned. (which is rather unconventional I think.)

That can't be the entire story, because the first column in the matrix looks centered. But then again, maybe alignment works differently in matrices.

**Comment by Enivex** [comment]
@laurmaedje This is also possibly quite possibly a bug, depending on what the answer is.

**Comment by laurmaedje** [comment]
Probably it should toggle between left and right like TeX does.

**Comment by SUPERCILEX** [comment]
@laurmaedje I have a fix for the equation part of this issue, but it basically requires tabular alignment semantics. Consider this typ:
```
$
& "right" \
"a very long line" \
"left" \
$
```

`left` should be right aligned while `right` should be left aligned which ends up being nonsensical (adding alignment, de-aligns things). We could probably hack our way around this, but it seems like part of the reason latex uses tabular alignment is because it naturally falls out of the right/left aternating semantics.

**Comment by Enivex** [comment]
I'm not sure why you call it nonsensical. Just imagine there being invisible &s added at the end if you don't put them explicitly.

**Comment by SUPERCILEX** [comment]
Yeah, that's exactly how I implemented it. So `left` finds its implicit alignment and sticks to it. But that's the same alignment that `right` should be using since there's an explicit alignment point! So `left` tries to be as far right as possible while `right` tries to be as far left as possible.

Here's the current behavior:
```
$
"right" \
"a very long line" \
"left" \
$
```
![image](https://user-images.githubusercontent.com/9490724/233797275-6df4865c-3dec-49c0-8b8b-a72e0357d0b0.png)

```
$
& "right" \
"a very long line" \
"left" \
$
```
![image](https://user-images.githubusercontent.com/9490724/233797264-1a989645-6244-4aff-a29f-9137686d701a.png)

If we're saying equations should alternate between right left alignment, then `left` should be shoved to the right and `right` should be left aligned with the two bottom lines. In the non-tabular world, that means `right` stays where it is which is the part that doesn't make sense: adding an alignment point brings the line to the left of everything else? Makes no sense. In the tabular world (which actually falls out of the alternative alignment naturally), `right`'s explicit alignment is the same one as `left`'s implicit alignment so `left` will end there and `right` will start there which makes it behave tabularly.

**Comment by SUPERCILEX** [comment]
Ohhhh, I even have a fix for the broken matrices that also improves performance! I decided to open the PRs as drafts since they're pending a decision on tabular alignment:
- https://github.com/typst/typst/pull/935
- https://github.com/typst/typst/pull/936
