### ISSUE TITLE
Bibliography is sorted by uppercase letters, then lowercase letters when using 'author-date' style

### ISSUE THREAD

**Issue by jamesWalker55** [typst/typst#472]
When using the 'author-date' style, the bibliography is sorted alphabetically. However, it sorts the entries with uppercase first, then lowercase.

**Minimal example**

bibliography.bib

```bib
@misc{entryA, author = {{A entry}}}
@misc{entrya, author = {{a entry}}}
@misc{entryB, author = {{B entry}}}
@misc{entryb, author = {{b entry}}}
@misc{entryC, author = {{C entry}}}
@misc{entryc, author = {{c entry}}}
```

temp.typ

```typ
@entryA
@entrya
@entryB
@entryb
@entryC
@entryc

#bibliography("bibliography.bib", style: "author-date")
```

Result:

![image](https://user-images.githubusercontent.com/30405220/228975863-76035524-e6f3-4b00-8cf9-37ac7572a1b6.png)

**Comment by ararunaufc** [comment]
This will need proper collation handling.

That might be a bit hard, because the authors' names might not be in a compatible collation with respect to the document's language...

But also the native readers maybe won't be surprised with the ordering is the language is respected...

I don't know. Let's see how the discussion goes

**Comment by reknih** [comment]
Bibliography sorting is now keyed by the CSL style and case-insensitive. Proper collation support is to follow, but merits its own issue.
