### ISSUE TITLE
Selector from counter/state value

### ISSUE THREAD

**Issue by igidrau** [typst/typst#4742]
### Description

It is currently difficult to style content depending on the value of a state or counter. Allowing the construction of selectors from states and counter would make this easier.

Such selectors could either reuse the `where` syntax
```typst
#let my-counter = counter("my-counter")
#show my-counter.where(value: (1,)): set text(red)
```
or with arbitrary conditions on the value
```typst
#show selector(counter(heading).at(1) == 0): set text(red)
```

### Use Case

In templates, this would allow to easily style the content under a particular heading, or on a particular page.

**Comment by laurmaedje** [comment]
You can do it like this:
```typ
#set heading(numbering: "1.")
#show heading: it => {
  let nums = counter(heading).at(it.location())
  set text(red) if nums == (1,)
  it
}

= Hello
= World
```

Other alternatives include giving the heading a label or wrapping it in a function call.

Regarding the proposed syntax: I'm not sure whether it would really make sense, since conceptually it would select the _counter,_ not the heading. But aside from that it would also be _very_ hard to fit into the existing systems implementation-wise. Given the existence of the other options, I'll thus close this.
