### ISSUE TITLE
Set document conditionally

### ISSUE THREAD

**Issue by cahalu** [typst/typst#4769]
### Description

```typst
// Definition
#let authors = context document.author.len()

// Output
Authors: #authors

// Error A (no error and nothing in about dialog)
#set document(author: "test") if authors == 0

// Error B (no error and nothing in about dialog)
#if (authors == 0) { set document(author: "test"); [Done] }
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
In your example, `authors` is of type `content`, not `int` so all the comparisons return false. Everything that depends on the contextual information needs to be inside of the [context expression](https://typst.app/docs/reference/context/).

That said, before https://github.com/typst/typst/pull/4768 was merged (which I coincidentally was just working on as you opened the issue) this still wouldn't have worked due to other bugs.

However, with it now merged, you can do it like this:
```typ
#set document(author: "Normal")
#context {
  set document(author: "Changed") if "Normal" in document.author
}
```

Note that document set rules are a special case here. Usually having a set rule without any following content in the same block is pointless because the set rule is scoped to the code block. However, because the document is a singleton, scoping does not make sense. So for document set rules, the last one just wins. 

For other kinds of set rules, you'd usually have a setup like this, with an ["everything show rule"](https://typst.app/docs/reference/styling/#show-rules):
```typ
#set document(author: "Normal")
#show: body => context {
  set text(red) if "Normal" in document.author
  body
}
Hi there!
```
