### ISSUE TITLE
Incorrect link to footnote with  0pt indent

### ISSUE THREAD

**Issue by FlorentCLMichel** [typst/typst#4770]
### Description

It seems that the link to footnotes is incorrect in `main` (commit feb0c913954d385a3f906f9d9d8ec33cbcf2b2d0)  when setting `footnotes.entry(indent: 0pt)`. (Any other value for `indent` seems to give the correct behaviour.) I could not reproduce the issue on the Typst app, so it was presumably introduced after the latest release. 

**Example code to reproduce the issue and a workaround:**

```
#page[
  this works#footnote[test]
]

#page[
  #set footnote.entry(indent: 0pt)
  this does not#footnote[test]
]

#page[
  #set footnote.entry(indent: 1em)
  #show footnote.entry: it => h(-1em) + it
  this works#footnote[test]
]
```

Viewing the document with Evince 42.3:

Correct link to footnote 1:

![image](https://github.com/user-attachments/assets/63edd6e1-de47-4cb3-b9f0-68f6b317e6e8)

Incorrect link to footnote 2:

![image](https://github.com/user-attachments/assets/e59beb16-8918-4d2d-b767-cdaeab5282e4)

Correct link to footnote 3:

![image](https://github.com/user-attachments/assets/b603f04b-bdb4-4000-9529-46906e6b2b6d)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The problem is that tags at the start of paragraphs are failed to be processed properly. Usually tags don't appear there because they become part of the flow instead of the paragraph. But because of the `h(0pt)` (which is removed as useless during paragraph collection), it does end up happening in this case.

Minimal example:
```
#h(0pt) // toggle this line
Text <label>

#context query(<label>)
```

The query result should always have length 1, but with the `h(0pt)` it fails. Might have been caused by https://github.com/typst/typst/pull/4497.

**Comment by laurmaedje** [comment]
Related to https://github.com/typst/typst/pull/4468#issuecomment-2243091367 in the sense that both cases there are problems with properly distributing zero-length items across lines.
