### ISSUE TITLE
Minus sign followed by extraneous space in some situations

### ISSUE THREAD

**Issue by Itay123TheKing** [typst/typst#487]
minimal example:
```typst
$-1 != -2$ \ // Unexpected
$-1 != - #h(0pt) 2$ // Expected
```
![Rendered by Typst-Renderer on discord](https://cdn.discordapp.com/attachments/1091297853055455335/1091297854317924352/rendered.png)

**Comment by yichenchong** [comment]
The issue in question seems to be due to this fragment in src/math/row.rs:
![image](https://user-images.githubusercontent.com/40590448/229283149-bcb53bb3-1d98-4c7c-aa70-6cfca2c0de8e.png)

It assumes that all the "Vary" operators (+, -, +-, -+) are binary operators if they are preceded by something (i.e. are at the front of an equation). As binary operators, the next few lines, then proceed to add the appropriate spacing for binary operators. That's why the first "-1" in both examples are spaced correctly. The second "-2" is also spaced correctly because explicit spacing disables the auto-spacing feature.

I think that removing | MathClass::Binary and | MathClass::Relation might make it work, so I'm testing it on a fork now.

**Comment by yichenchong** [comment]
Ok, I think that fixes it, here are some sample outputs:
![image](https://user-images.githubusercontent.com/40590448/229288003-fa947036-3409-4ace-8a24-5c062cb80354.png)

Let me just make a PR

**Comment by laurmaedje** [comment]
Fixed in #500.
