### ISSUE TITLE
`show` rule not updating state when returning a non-content value

### ISSUE THREAD

**Issue by LEXUGE** [typst/typst#4913]
### Description

The show rule doesn't update the state variable when returning value is not of type `content`:
```typst
#let s = state("s", 0);

#show heading: (args) => {
  s.update(s => s+1)
  return "Some Heading"
}

= Hello

// Should be 1 but instead gets 0?
#context s.get()
```

### Reproduction URL

https://typst.app/project/rsuLOa4uvA8NCJKMvjv4zf

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is working as intended, `s.update()` returns content which, when placed in the document, will trigger an update. (To be a bit more precise, `state.get()` will query all state update elements in the document before returning the final value.)

So, if you `return` a single value, the state update element isn't joined with that value and is effectively useless.

The solution in this case is to remove the `return` keyword, as by default each line in a block is joined and returned.

See also #4262 for further discussion on ways to improve diagnostics for this case.

**Comment by LEXUGE** [comment]
Removing the `return` keyword seems to make the joined return value of type `content` instead of `string`. I have the case where I want a function to `update` and return `string` to be reused in other codes. To achieve so, I have to workaround.

At least, in this case, I feel the semantics are somewhat unintuitive. As a typical user, I would expect `update` to be "executed" when function is called, rather than joined and returned and executed in the final phase.

**Comment by PgBiel** [comment]
Typst functions are pure, so they cannot have side-effects. In particular, they cannot modify global variables. This is why using `state` instead of a simple global variable is needed: the state variables updated by the function are all encoded in what the function returns and places in the document. This means there is no way to update a state and _not_ return a state update element (which is `content`).

Then, when calling `state.get()`, that's the same operation as something like `query(state.update)` to query all elements of that type, followed by consecutively applying updates to the state's initial value and returning what the last update returned. That's more or less how the state system works.

You may wish to share your use case in a Discussion so others may help you find an alternative way to do what you need. But, in general, it is unavoidable - you will have to return `content` at _some_ point if you want a state update to "work".

**Comment by LEXUGE** [comment]
Reading on the documentation I find myself happy:
> The update will be in effect at the position where the returned content is inserted into the document. If you don't put the output into the document, nothing happens! This would be the case, for example, if you write let _ = state("key").update(7). State updates are always applied in layout order and in that case, Typst wouldn't know when to update the state.

And updating in layout phase seems like the right choice.

In that case probably my use case is not very compatible with the current scheme.
