### ISSUE TITLE
Implement reverse numbered lists in `enum`

### ISSUE THREAD

**Issue by liamtoney** [typst/typst#4949]
### Description

In HTML, one can write a list like:
```html
<ol reversed>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```
which produces
```
3. Coffee
2. Tea
1. Milk
```
---
In LaTeX, one can likewise use the [`etaremune`](https://ctan.org/pkg/etaremune) package:
```latex
\begin{etaremune}
  \item Coffee
  \item Tea
  \item Milk
\end{etaremune}
```
---
In Typst, the closest I've come to this is:
```typst
#let items = ([Coffee], [Tea], [Milk])

#enum(
  numbering: n => [#{items.len() + 1 - n}.],
  ..items,
)
```
This actually works fine in terms of producing a PDF with the proper output. However, it seems hacky, and tools like e.g. pandoc interpret lists like this as non-reversed when converting to e.g. HTML.

Could `enum` implement a reverse numbering option that natively supports something akin to `<ol reversed>`? Syntax could be:
```typst
enum(
  ...
  reversed: bool,
  ...
)
```

### Use Case

Anywhere where a reversed list is useful. For example, publications on a CV are typically numbered from most recent to least recent, with the most recent being publication $N$ and the oldest being publication $1$.

**Comment by sitandr** [comment]
### How it can be done

Just in case, I will list the ways it can be done now.

For small lists, you can just straight up write the following:

```typ
3. The third place.
2. The second
1. The first
```

And that would be in fact a numbered list with all rules applied, _maybe_ even correctly interpreted by pandoc.

The better way would be, of course, using custom function with code you provided:

```typ
#let rev-enum = enum.with(numbering: n => [#{items.len() + 1 - n}.])

#rev-enum(
  [Third place],
  [Second place],
  [First place]
)
```

Or you can even use `set` rule to make the enums reversed by default the same way.

### About the proposal 

It doesn't seem hacky to me. That's quite a normal way of dealing with things for Typst.

However, I agree such option may be convenient to simplify things a bit and shouldn't be hard to add.

Out of my head, that may cause some small confusion with items. For example, if constructing enum from array, it may seem that `reversed` option will reverse the order of items — though I would argue in favor of opposite behaviour. The same applies to getting enums childs. So maybe renaming it to `reverse-numbering` or something similar would be better.

Finally, I would say the `reversed-numbering` option isn't exclusive to lists only. It may apply to chapters, pages, just everywhere where `numbering` is used. So maybe we should add `reverse()` method to `numbering` object instead?

That would, however, make the thing similar in terms of code and convenience to currently available and maybe mess with layout a bit (eg., the total number for each heading level has to be known).

So I'm not very sure about it, happy to hear other thoughts. The pandoc argument just isn't good enough, and otherwise it doesn't seem like a big win.

**Comment by laurmaedje** [comment]
One thing that a built-in reversal could do, but just changing the numbers not, is change the logical ordering for accessible PDFs. But we don't write such a thing anyway yet.

**Comment by liamtoney** [comment]
> One thing that a built-in reversal could do, but just changing the numbers not, is change the logical ordering for accessible PDFs.

And once HTML export is added to Typst, a built-in reversal would [hopefully] produce `<ol reversed>` in HTML output. And pandoc would theoretically be able to latch into this as well.

@sitandr — I agree that it's not too hacky to reverse the numbering of a list for appearance. It's the built-in reversal that I specifically think could be useful.
