### ISSUE TITLE
Feature Request: Add `PRESENTATION_16_10` page size option

### ISSUE THREAD

**Issue by singularitti** [typst/typst#4965]
### Description

Recently, the 16:10 aspect ratio has become increasingly popular for presentations due to its wide-screen compatibility, particularly on modern laptops and monitors. It would be great if Typst could offer a predefined page size option like `PRESENTATION_16_10`, similar to how other presentation aspect ratios such as 4:3 and 16:9 are often supported in various tools.

### Proposed Solution

Add a predefined `PRESENTATION_16_10` page size option to the Typst settings that sets the page width and height according to the 16:10 aspect ratio.

For example:
- Width: 297.0mm
- Height: 185.625mm

This would make it easier to create presentation slides with a 16:10 ratio without manually specifying the dimensions every time.

### Use Case

- Convenient for users who frequently create presentations in the 16:10 format.
- Keeps up with modern display trends.
- Simplifies the process of switching between different presentation aspect ratios.

**Comment by Enivex** [comment]
> Recently, the 16:10 aspect ratio has become increasingly popular

I'd argue that it was popular 15-20 years ago, but has since vanished

If you mean laptops taller than 16:9, then they're typically 3:2 (though I'd be happy to be proven wrong).

In any case, it _is_ useful to have an aspect ratio in-between 4:3 and 16:9 available for when you don't actually know what display will be used (say at a conference). The geometric mean of (4/3 and 16/9) is approximately 1.54, which is somewhere in-between 3:2 and 16:10.

**Comment by singularitti** [comment]
For example, on recent MacBook Pros, the most popular resolutions are 1728x1117, 2056x1329 (16 inch), or 1512x982, 1800x1169. They are approximately 1.54, closer to 16:10, rather than 16:9.

**Comment by Coekjan** [comment]
My laptop "Dell Inspiron 16 Plus 7610" has a 16:10 screen.

**Comment by laurmaedje** [comment]
It's very easy to set a custom width and height if you need a 16:10 presentation. I'm not sure it's really necessary to have built-in names for all the display ratios.
