### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by HarmoGlace** [typst/typst#497]
It would be nice to support complex numbers in typst calculation methods, which is not the case currently.

**Comment by Bowuigi** [comment]
I would even argue that the generalization of complex numbers (vector2, vector3, vector4, ...) would be even more useful, specially if doing a library that draws stuff (2D/3D plots, for example)

**Comment by user202729** [comment]
more generalized would be to allow user to define arbitrary data type with operator overloading, but making a new whole _programming language_ is a huge effort and easy to do incorrectly.

(Side remark, I think creating a Typst programming language was absolutely necessary because of the amount of syntactic sugar needed -- you need `[...]` and `$...$` special syntax inside code, as well as `#set`, automatic concatenation etc. -- but it would also have been possible to make a precompiler into e.g. Lua -- and I think it's possible to sandbox the runtime environment of Lua to disallow interaction with operating system as well)

**Comment by Bowuigi** [comment]
If operator overloading is an option, I would recommend to keep following Haskell's way and using typeclasses (similar to Rust's traits). But it would be out of scope for *any* kind of word processing software, you can always write some actual Haskell and generate Typst code from there

**Comment by Bowuigi** [comment]
As for Lua sandboxing, it is just disabling os.execute and io.popen and you no longer can execute shell commands. Changing I/O is a bit more involved though, but still fairly simple (BTW, I would compile to a Scheme instead)

**Comment by TheKaram** [comment]
are there any plans to support it?

**Comment by laurmaedje** [comment]
There are currently no plans to support this in the core language. I think this is best left to packages.

**Comment by burrbull** [comment]
It would be nice to have at least `IntoValue` implementation for `Complex`.
