### ISSUE TITLE
Symbols aren't callable in maths mode

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#4980]
### Description

$hat(a)$ #sym.hat("a") #(sym.hat)("a")
> ```
> error: expected function, found symbol
>     ┌─ mmn15.typ:148:10
>     │
> 148 │ $hat(a)$ #sym.hat("a") #(sym.hat)("a")
>     │           ^^^^^^^
> ```

### Typst version

- [X] I am using the latest version of Typst

**Comment by mkorje** [comment]
Symbols themselves are different from the callable symbol functions. We define for a certain set of symbols (accents) a function with their name, which is made available in the math scope. They aren't related at all to the `sym` module.

The behaviour you show is to be expected, as it should be accessed as `#math.hat("a")` instead, I think.

**Comment by emilyyyylime** [comment]
I see, I suppose we would want to fix the name overloading problems then. I really don't get why `sym` items are even available under `math` in code mode to be honest

**Comment by mkorje** [comment]
Maybe I should clarify that they aren't quite "in scope" in the usual sense. The `sym` items are made available by simply defining them in math as well (https://github.com/typst/typst/tree/main/crates/typst/src/math/mod.rs#L208-210). So they are still accessible under `math` in code mode as they are defined there.

We could probably change it so that the `sym` items aren't redefined in math, and instead perform a lookup inside the `sym` module when evaluating identifiers in math mode.

**Comment by emilyyyylime** [comment]
That makes more sense to me

**Comment by Coekjan** [comment]
Could you please try to compile your code with the main branch code? AFAIK, symbol `hat` is now callable since #4299

https://github.com/typst/typst/blob/92ec56601831b9c454dbeaf28dba84e2769c7726/crates/typst/src/symbols/sym.rs#L158

**Comment by mkorje** [comment]
> Could you please try to compile your code with the main branch code? AFAIK, symbol `hat` is now callable since #4299

I hadn't realised this change had been implemented on main, sorry I gave a very wrong description of the current behaviour!

I also thought there might still be overlapping definition problems when using `#math.hat` (or something similar) with those changes, but I just checked and it isn't a problem.

**Comment by PhyX-Meow** [comment]
@Coekjan Could you also make `math.bar` callable? It should behave the same way as `hat`
