### ISSUE TITLE
Breakable block equations can overflow

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#5025]
### Description

_A regression introduced with #5017_

A breakable block equation can overflow outside the bounds of its parent container. For example, the code
```typ
#set page(width: 3cm, height: 2cm, margin: 3.5mm)

#show math.equation: set block(breakable: true)

This equation overflows:
$ a + b $
```
results in the following output, where the left is before the regression and the right is after:

![image](https://github.com/user-attachments/assets/7f4674b0-d45f-4e1a-8511-fdec6fedd50f)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is actually a bug in the equation layout that is surfaced by the changes in the flow. The contract of a multi-layouter is that it produces frames that corresponds 1-1 to regions. The math layouter produces just one frame and that one overflows the first regions. The old flow layouter "healed" that by moving the frame to the next region (because this check happened to be in the code path for all frames), but the new flow layouter doesn't do that anymore.

**Comment by laurmaedje** [comment]
Still a good catch though, we should check whether other multi_layouters also have this problem
