### ISSUE TITLE
Defaults for US paper sizes (e.g. "us-letter") have rounding errors

### ISSUE THREAD

**Issue by lazyeights** [typst/typst#5165]
The defaults for US paper sizes (like `#set page(paper: "us-letter") are defined in millimeters not inches,  as seen here:

https://github.com/typst/typst/blob/9ee80762a55c0d173664d9ac33cb762b79341a96/crates/typst/src/layout/page.rs#L902C4-L904C51

This forces a conversion to user space units that has apparently has rounding errors. For example, "us-letter" results in fractional point values for the dimensions:

![CleanShot 2024-10-08 at 15 37 13](https://github.com/user-attachments/assets/ac22008a-4aca-45b5-baa9-b31964e55d58)

When the paper size is defined directly in "freedom" units (like `#set page(width: 8.5in, height: 11in)`) the dimensions are properly set.

**Comment by Enivex** [comment]
I do not believe the issue is that it's defined in millimeters instead of inches. In fact, one inch is _exactly_ 25.4 mm, so a sheet of letter paper (8.5 in x 11 in) is _exactly_ 215.9 mm x 279.4 mm.

Rather, I think the issue is here
https://github.com/typst/typst/blob/9ee80762a55c0d173664d9ac33cb762b79341a96/crates/typst/src/layout/abs.rs#L261

The actual number is $72/25.4 =2.834645669291338582677165354330708661417322...$. Obviously not representable as a float, but I see no reason for typst to arbitrarily round it to just 5 digits.

**Comment by alerque** [comment]
PDF paper sizes should be defined in points. US Letter is 612 × 792 points.

**Comment by Enivex** [comment]
> PDF paper sizes should be defined in points. US Letter is 612 × 792 points.

As long as typst uses floating and not fixed point, I can't imagine it would matter as long as the conversion factor is corrected. We would be talking about a tiny fraction of a point. ISO paper can't be exactly represented in points either.

**Comment by lazyeights** [comment]
The PDF spec default is 1/72 in per inch, so it seems like Typst should be built around that, otherwise there will be edge cases (like this) where Typst differs because it is built around a different unit standard.

> [PDF 32000-1:2008 Annex C.2] The minimum page size should be 3 by 3 units in default user space; the maximum should be 14,400 by 14,400 units. In versions of PDF earlier than 1.6, the size of the default user space unit was fixed at 1 ⁄ 72 inch, yielding a minimum of approximately 0.04 by 0.04 inch and a maximum of 200 by 200 inches. Beginning with PDF 1.6, the size of the unit may be set on a page-by-page basis; the default remains at 1/72 inch.

> [PDF 32000-1:2008 14.11.2.1] The page object dictionary specifies these boundaries in the MediaBox, CropBox, BleedBox, TrimBox, and ArtBox entries, respectively (see Table 30). **All of them are rectangles expressed in default user space units.** The crop, bleed, trim, and art boxes shall not ordinarily extend beyond the boundaries of the media box. If they
do, they are effectively reduced to their intersection with the media box. Figure 86 illustrates the relationships
among these boundaries. (The crop box is not shown in the figure because it has no defined relationship with
any of the other boundaries.)

> (Optional; PDF 1.6) **UserUnit**. A positive number that shall give the size of default user space units, in multiples of 1 ⁄ 72 inch. The range of supported values shall be implementation-dependent. Default value: 1.0 (user space unit is 1 ⁄ 72 inch).

**Comment by Enivex** [comment]
Typst does use points internally. That's not the issue here.

**Comment by knuesel** [comment]
One inch is exactly 25.4mm but there's the issue of floating point precision: 25.4 cannot be represented exactly as a 64-bit float (instead you get ~25.3999999999999985789). And doing floating-point calculations will add additional errors, so it's not surprising that you get something inexact in the end.

For example trying to convert 215.9mm to points with the factor 72/25.4 gives ~612.0000000000001136868. 

(You see this in Julia by evaluating `big(215.9 * (72/25.4))`)

The imprecision shouldn't matter for the appearance of the document, but maybe some software will fail to detect known paper sizes if values are not exact?

Some calculations do work exactly with floats, for example 8.5*72 gives exactly 612 because 0.5 is exactly 2^-1, so it's true that defining us letter and us legal in inches would solve the issue.

I agree with @Enivex that the conversion factor 2.83465 is needlessly imprecise, I think we should use `72/25.4` which will give the closest floating point number.

**Comment by laurmaedje** [comment]
This is probably _the_ oldest remaining bug in Typst. I traced it back to the [_first_ public commit](https://github.com/typst/typst/commits/5a600eb354c65ec008cbf020e45705c2f401d669/src/doc.rs) where Typst consists of a grand total of six files: https://github.com/typst/typst/blob/5a600eb354c65ec008cbf020e45705c2f401d669/src/doc.rs#L70-L72

**Comment by laurmaedje** [comment]
Opened https://github.com/typst/typst/pull/5169
