### ISSUE TITLE
State Updates Are Not Reflected When Displayed in the Same Context Block

### ISSUE THREAD

**Issue by efeyakinci** [typst/typst#5206]
### Description

The following code
```
#let ctr = counter("my_counter")

#context {
  ctr.step()
  ctr.display()
}
#context {
  ctr.step()
  ctr.display()
}
```

Displays `0 1`, when I would argue that the expected behavior is displaying `1 2`.

I'm not sure whether this is expected behavior currently, and if so, I think it should be discussed whether it _should_ be expected behavior.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
`context` generates an element which, when placed, provides its location and local styling (information normally only available during the layout phase, hence why code execution inside `context` is delayed) to anything inside it. This means, for example, that all `here()` calls will return the location of that element, as well as that any counter or state accesses are relative to that element's location, which is either before or after all accesses inside it (Typst seems to have chosen the parent to mean "before"), so it's not possible to capture counter or state updates without placing another context element to provide a separate location, by design.

This is documented here: https://typst.app/docs/reference/context/#nested-contexts

**Comment by efeyakinci** [comment]
Thanks for the info!
