### ISSUE TITLE
Blockquote fill with transparentize behaviour has changed

### ISSUE THREAD

**Issue by quachpas** [typst/typst#5266]
### Description

Because `quote` is now affected by all block properties, transparentize smart behaviour clashes with the previous version output.

v0.12.0
![image](https://github.com/user-attachments/assets/ffd5f131-36b7-4afc-9f79-3733a8277360)
v0.11.1
![image](https://github.com/user-attachments/assets/cbe60fc0-b4cf-4c93-87df-41be9cf87988)

MWE
```typst
#show quote: set block(
  fill: black.transparentize(90%),
  width: 100%,
  inset: 5pt,
  radius: 1pt,
)

#quote(block: true)[
  #lorem(10)
]
```
Discovered by @shhuang at https://forum.typst.app/t/change-of-quote-format/1250

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Not much we can do here. Currently, I would not recommend using show-set rules on blocks that produce visible different output with nested blocks (because there always can be some). With `breakable` it's not a problem because it doesn't matter.

Once we have non-recursive show-set rules, things would be different.
