### ISSUE TITLE
0.12 handles CJK fonts incorrectly  

### ISSUE THREAD

**Issue by leana8959** [typst/typst#5277]
### Description

Hello,

I noticed that documents with CJK fonts are compiled with "tofu" text when using typst version 0.12.
I also noticed that compiling to svg works just fine, this seems to be related to pdf.

```typ
#set text(size: 3em)
#set align(center + horizon)

我在測試我的 CJK 字體
```

The one that works is 0.11.1.

![0.11.1](https://github.com/user-attachments/assets/abbecc52-4d90-4018-8a2c-55e090dd7418)
![0.12.0](https://github.com/user-attachments/assets/152f012a-1357-4148-82aa-e04a73113654)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
From what I can gather, the problem lies with the font being a variable font.

When using one of the static [Noto Serif CJK](https://github.com/notofonts/noto-cjk/releases/tag/Serif2.003) variants, the output looks perfectly fine on both 0.11.1 and 0.12.0.
After switching to a variable variant, tofus appear on 0.12.0 and on first glance looks fine on 0.11.0. However, that is just when exporting to PDF.

When exporting to PNG, the output in 0.11.1 is noticeably worse than on 0.12.0:
- 0.11.1:
![0.11.1](https://github.com/user-attachments/assets/278b6faa-cb92-4558-9550-d97836317b79)
- 0.12.0:
![0.12.0](https://github.com/user-attachments/assets/17504da8-30c7-408c-bb05-c6176cbde3c1)

Considering that variable font export never truly functioned correctly for PDFs either (#185), I think the tofus are actually the better choice.

The ideal solution would of course be to support variable fonts, but until that date, you'll have to use a static font.
We could also consider warning the user when trying to use a variable font, or not even selecting it when searching for fonts. Both of these seem tricky and counterproductive, though.

**Comment by leana8959** [comment]
I see, I’ll try using a static font and see if that fixed the problem. Thank you !

**Comment by leana8959** [comment]
I confirm that Noto CJK's static variant works :)

Would it be possible (if it's a good idea) to detect whether the user is trying to use variable fonts, and show a compiler hint?

**Comment by laurmaedje** [comment]
Opened https://github.com/typst/typst/issues/5304, closing this.
