### ISSUE TITLE
Data loading leaks memory

### ISSUE THREAD

**Issue by TS53** [typst/typst#5303]
### Description

Tested with `typst watch` but probably also problematic for `typst compile` but harder to see there.

Example:
```typst
#read("bigfile.ext", encoding: none)
```
Note that the data is not declared to a variable and should be dropped immediately. Instead, the contents are kept in RAM for no reason.
With `typst watch`, we can now change the filename to a smaller file like `image.jpg` and we expect that the big contents unload from memory and instead at most the small image contents are loaded into RAM (the expected scenario would be immediate dropping here, too).

The problem is more practical and visible with loading big images like in https://github.com/typst/typst/discussions/5279.

Also, with code like the following, the memory should drop immediately:
```typst
#let varname = read("bigfile.ext", encoding: none).at(10) == 0
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
It's not really a "memory leak", this is most likely happening because Typst memoizes most things so that it can provide good incremental compilation, so it's intentional. If it didn't keep the file in memory, it would have to reload it on every keystroke when using `typst watch`, which will obviously make it much slower. But yes, this indeed isn't great when very big files are used, so something should definitely be done about it.

**Comment by TS53** [comment]
> In computer science, a memory leak is a type of resource leak that occurs when a computer program incorrectly manages memory allocations in a way that memory **which is no longer needed** is not released.

I think, this is exactly what happens in the examples shown above. Maybe a cache is the reason or a wrong lifetime, yes.

**Comment by laurmaedje** [comment]
In the second case, the array is dropped immediately because it itself doesn't end up in the cache, just the results. If you put it into a function call, it will behave the same as function calls are cached.

> which is no longer needed 

Well, we precisely do not know whether we're gonna need it. That's the whole idea of having caching: As the compiler doesn't know what you're gonna do, it keeps things around. And in your example of `read("bigfile.ext", encoding: none).at(10)`, it actually _does_ need it again, in the next compilation. For files specifically, it also needs to check whether the contents changed for incremental compilation.

This is all working as intended. But reducing memory usage by making caching a little less aggressive in some places  and eviction a little smarter is on the roadmap.

**Comment by TS53** [comment]
> And in your example of read("bigfile.ext", encoding: none).at(10), it actually does need it again

I assumed that file contents are never cached, I can't think of a case where this makes sense. Instead, storing the filename and last change time of a file or so would make sense. If the file changed, then compute the result again. Otherwise, since the file has not changed, we know that `read("bigfile.ext", encoding: none).at(10)` will return the same result again.

Storing it for `#read("bigfile.ext", encoding: none)` is never helpful, I think.

I still think that we can see a memory leak here.

**Comment by laurmaedje** [comment]
We did use last change time for a while but it was unreliable on some platforms. I can't remember the details but I'm sure you can find them in the git history.
