### ISSUE TITLE
Issue with syntax highligting in Raw block on Windows

### ISSUE THREAD

**Issue by arkadiuszwojcik** [typst/typst#5309]
### Description

My simple typst document looks like this:

````
#show raw.where(lang: "rust"): set raw(theme: "VisualStudioDark.tmTheme")

```rust
// test
pub struct Wow { hi: u64 }
let logical: bool = true;
fn blah() -> u64 {}
```
````

`VisualStudioDark.tmTheme` can be any theme but important is to use some distinct color (like red) for `variable` scope so `hi` variable will be red in output pdf. Problem is that everyting is colored except `variable` scope so `hi` stays black. I thought this must be some issue with my template file but after long investigation and switching to Linux and using very same example ... it works, and `hi` becomes red in output pdf. So I guess this must be something specyfic to windows.

On Windows I am using Typst 0.12 and on Linux i compiled source from 0.12 branch.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Could you share the `.tmTheme` file you're having this problem with?

**Comment by arkadiuszwojcik** [comment]
@PgBiel  sure (please change extension from `txt` to `tmTheme`)

[VisualStudioDark.txt](https://github.com/user-attachments/files/17534829/VisualStudioDark.txt)

**Comment by PgBiel** [comment]
It appears like this to me in both Linux and the web app. Seems like the theme is the culprit (if that's not the intended output).

![image](https://github.com/user-attachments/assets/749f0f4b-1d1f-4b67-914c-2c04c39ebdaa)

The fact that it was different on your Linux machine was likely due to user error (either using a different Typst version, a different theme file, or something else).

**Comment by arkadiuszwojcik** [comment]
@PgBiel hmm you are right, I had to mess something up at some point with my files. Sorry for that. Closing.
