### ISSUE TITLE
Blocks with clipping interferes with text fill color transparentize

### ISSUE THREAD

**Issue by diquah** [typst/typst#5499]
### Description

Blocks with clipping enabled messes up transparency, but only fill text fill colors. Strangely, rect fill seems to be unaffected.

![image](https://github.com/user-attachments/assets/0c848eb2-1eda-4006-a51f-8128342ca85e)

```typst
#set page(width: 2in, height: 2.1in)

#block(clip: false, {
  text(fill: blue.darken(20%).transparentize(50%), "Hello, World")
})
#block(clip: true, {
  text(fill: blue.darken(20%).transparentize(50%), "Hello, World")
})

#block(clip: false, {
  rect(fill: blue.darken(20%).transparentize(50%))
})
#block(clip: true, {
  rect(fill: blue.darken(20%).transparentize(50%))
})
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Works fine on the exported PDF, as well as on SVG export, so it's specific to PNG export.

<details><summary>Exported PDF output</summary>
<p>

![correct colors](https://github.com/user-attachments/assets/906cd7c6-476b-4027-818d-3f92f4005ab8)

</p>
</details>

**Comment by PgBiel** [comment]
Interestingly, adding `#set text(stroke: 0pt)` (i.e. adding any stroke, even if it's not visible at all) fixes it.

**Comment by PgBiel** [comment]
Given the above, I suspect the problem is in either `render_outline_glyph` or `write_bitmap` of `typst-render/src/text.rs` (I'd bet on the second function):

https://github.com/typst/typst/blob/76c24ee6e35715cd14bb892d7b6b8d775c680bf7/crates/typst-render/src/text.rs#L40
https://github.com/typst/typst/blob/76c24ee6e35715cd14bb892d7b6b8d775c680bf7/crates/typst-render/src/text.rs#L158

This is because

1. The second function isn't called at all if text has a stroke. Then it is rendered as a path.
2. The second function has a conditional for the presence of a mask (which I believe is implied by `clip: true` in a block).

So it's possible the problem is somewhere in the first branch in that second function.

While I'm not very knowledgeable on this part of the repository, I don't see anything too weird popping out to me after analyzing the code (and the code in some of the functions it uses) for a bit. I wonder if this could be an upstream bug in tiny-skia? (Haven´t tested enough to tell yet)

**Comment by PgBiel** [comment]
It's not an upstream problem, we're just doing the wrong math here:
https://github.com/typst/typst/blob/76c24ee6e35715cd14bb892d7b6b8d775c680bf7/crates/typst-render/src/text.rs#L175-L184

By using `alpha_mul` like in the other branch, it is fixed.

**Comment by PgBiel** [comment]
I noticed that gradients are also broken in `clip: true` blocks in PNG export:

```typ
#set page(width: 2in, height: 2.1in)

#block(clip: false, {
  text(fill: blue, "Hello, World")
  [\ ]
  text(fill: blue.darken(20%).transparentize(50%), "Hello, World")
  [\ ]
  text(fill: gradient.linear(..color.map.rainbow), "Hello, World")
})
#block(clip: true, {
  text(fill: blue, "Hello, World")
  [\ ]
  text(fill: blue.darken(20%).transparentize(50%), "Hello, World")
  [\ ]
  text(fill: gradient.linear(..color.map.rainbow), "Hello, World")
})
```
![image](https://github.com/user-attachments/assets/c741f4c1-246f-4a22-8ca3-6e302d7bd1af)

My fix using `alpha_mul` seems to fix transparency but not gradients, I'll have to investigate. Might be a separate but related problem
