### ISSUE TITLE
lonely #cite in #align does not produce block

### ISSUE THREAD

**Issue by michalmoc** [typst/typst#5503]
### Description

```
sdadsafsafafsf
#align(right)[#cite(<uuu>)]
#align(right)[b]
```
makes for
![obraz](https://github.com/user-attachments/assets/1ecc2c91-0a5e-4a6e-a411-cf73189a6d28)

adding anything to the cite, eg.
```
sdadsafsafafsf
#align(right)[a#cite(<uuu>)]
#align(right)[b]
```
changes it to
![obraz](https://github.com/user-attachments/assets/7d9f01d6-59b2-4322-80d9-dabf65a0f0a0)

At least one of the behaviours is probably incorrect

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Seems to be a 0.12 regression (works correctly in 0.11.1 and lower).

**Comment by PgBiel** [comment]
Not exclusive to `cite`. Boxing a `list` or `enum` exhibits the same behavior. The same can't be said about other elements, however; to name a few, `rect` and `heading` do not seem to be affected.

```typ
#align(right, cite(<name>))
#align(right)[a]

#align(right)[- a]
#align(right)[b]

#align(right)[+ a]
#align(right)[b]

#align(right)[= a]
b

#show list: box
#align(right)[- a]
#align(right)[c]

#show enum: box
#align(right)[+ a]
#align(right)[b]

#show heading: box
#align(right)[= a]
b
```

![output: aligned boxed lists and enums are not properly interrupting the paragraph, but headings are](https://github.com/user-attachments/assets/9d571317-1093-4649-b6fd-36858fa96a9c)

**Comment by PgBiel** [comment]
Indeed, things outside `align` are being grouped with what's inside `align`:

```typ
#align(right, cite(<name>))
@name
@name

#align(right)[- a]
- b
- c
```

![cite groups and full lists despite the presence of align](https://github.com/user-attachments/assets/fa8ab248-e7a7-4824-a785-04a666832683)

**Comment by PgBiel** [comment]
`par` is also affected, which strengthens my suspicion:

```typ
Par:

+ a
#par(leading: 1em)[+ b]
+ c
```

![image](https://github.com/user-attachments/assets/34a3a2a1-d174-47a9-ab36-f562a139092b)

**Comment by PgBiel** [comment]
I've added some debug prints, and the problem seems clear: `par` and `align` are not being treated any differently from `text` for cite and list grouping. They are all elements which simply apply set rules to their children. Thus, they are not seen as an impediment to grouping, since in theory they just applied some styling to what's in them.

They interrupt paragraphs because paragraph grouping has an explicit interrupt check for `par` and `align`, so the styles they apply to their children are checked, so in particular `#par(leading: 1em)[something]` and `#align(right)[something]` interrupt a paragraph because they add set rules for par and align, which are manually checked. The same check isn't present for cite grouping and list grouping, so align and par don't interrupt cites and lists - **but their styles are still applied:**

```typ
List:

+ abcdefghiabcdefghi
#align(right)[+ to the right]
+ b
+ c
```
<details><summary>Output</summary>
<p>

!["to the right" is right aligned](https://github.com/user-attachments/assets/08fe0e68-935d-4f6e-9a77-4b7aeef3ae5b)

</p>
</details>

I've verified that this also exposes a behavior that was also present in 0.11.1: a `par` which doesn't apply any styles does not interrupt a list.

```typ
Par (no style changes):

+ a
#par[+ b]
+ b
```

<details><summary><strong>0.11.1</strong> output (same as 0.12)</summary>
<p>

![image](https://github.com/user-attachments/assets/0ef926f6-2e11-44f9-8dd6-309542941daf)

</p>
</details>

I'd consider that a **separate, but related** bug. In general, `par` seems to be rather inconsistent with its "blockiness". But, for now, an easy fix is to simply ensure changes to styles in paragraph and align will interrupt all other grouping kinds as well.
