### ISSUE TITLE
Imports that are global to the project

### ISSUE THREAD

**Issue by paulgoulain** [typst/typst#595]
Hi everybody,

As an exercise, I started to redo my PhD manuscript using Typst. Originally I did it using Latex, with a main.tex file, and imports of the different chapters (chapter1.tex, chapter2.tex, ...). For physic notation typesetting, I use the [typst-physics](https://github.com/Leedehai/typst-physics) package. I noticed that even if I import this package in the main. typ file, I still need to import it in the chapter files too. 

Is it the expected behavior or am I doing something wrong ? Is there a way to make imports made in a parent file to propagate its children ?

**Comment by laurmaedje** [comment]
An import is indeed only available in one file. If you import multiple packages and don't want to repeat all of the imports in each chapter, you can create a single file with all imports and import only that file in your chapters.

**Comment by astrale-sharp** [comment]
It's how scope usually works (in many many programming language),

If you don't specify where a language item comes from, the language probably shouldn't guess.
This is not an issue so can you please close this @paulgoulain ? I hope this was informative, otherwise there is the beginner channel of the discord!

**Comment by paulgoulain** [comment]
Well then let's turn this into a feature request :)

Is it desirable to be able to make imports global to a whole document ? Something similar to the Latex usepackage ?

**Comment by laurmaedje** [comment]
Relevant other discussion: #754. I am not a fan of global imports as they fundamentally mess with how the module system works and break the notion that a module is well-defined on its own.

**Comment by Jollywatt** [comment]
I guess what people want is not to break the module system, but to have files that aren’t tied to modules.

I.e., to have a way of sourcing a file that is equivalent to inserting the file’s contents where it is imported — without any of the hassle of that comes with a module namespace.

(Compare python’s `import` for files _and_ modules to Julia’s `include()` for files and `import/using` for modules. One of those is much easier to use than the other.)

**Comment by 7sDream** [comment]
The raw input mechanism is useful for big document, I used it [heavily](https://github.com/7sDream/scp-pdf/blob/master/part01/index.tex) when using TeX. Constants/shortcut commands needn't to be imported in each real document file, only once in main file, it saves a lot of time and very intuitive.

This can be done in many different way:

- Way 1, insert content of input file in lex/parser stage
  - [`#include` preprocessing directive](https://gcc.gnu.org/onlinedocs/cpp/Include-Operation.html) in C/C++
  - [`include!` macro](https://doc.rust-lang.org/std/macro.include.html) in Rust
  -  [`input` command](http://latexref.xyz/_005cinput.html) in TeX
- Way 2, dynamic code execution with current scope
  - Python [`exec`](https://docs.python.org/dev/library/functions.html#exec): `exec(open("file.py", r).read(), globals(), locals())`
  - Lua [`dofile`](https://www.lua.org/pil/8.html): `dofile("file.lua")`
- Way 3, code template, not sure how it works yet
  - [Template Mixins](https://dlang.org/spec/template-mixin.html) in D language

Conceptually, I prefer the way 1 as it simple, clean and easy to understand. 

In theory, dynamic code execution can given the same results.  And, in practice, now in Typst we alreay have `eval`, which just like `exec` in python. If we can let it access current scopes(and filesystem), a Tex style `\input` can be easily writen, like

```typst
#let input(path) = eval(read(path), mode: "markup", root: path, scope: current_scopes())
```

But `current_scopes` function may have perf issue due to deep copy of all values in scopes, and modifications to scopes will be lost after `eval` finish. So maybe the scope inherit need to be a separate argument:

```typst
#let input(path) = eval(read(path), mode: "markup", root: path, inherit_scope: trrue)
```

The inherit mechanism can be implemented in Rust side, for example take out vm's scopes and give it to `eval_string`, then return and set back to original vm.

Obviously source span and diagnostics need some update too, just some early thought.

**Comment by 1216892614** [comment]
If it possible just allow us use `let` as `set` or `show` to export the whole rest part?

**Comment by laurmaedje** [comment]
We do not plan to support this, see https://github.com/typst/typst/issues/4194#issuecomment-2120291989 for reasoning.

**Comment by Splines** [comment]
> When wanting to use definitions across many files, the Typst way is not to define them in the main file, but to have them in a shared utility file which is imported in every chapter. Requiring this import in every chapter might need some getting used to, but it improves robustness, predictability, and performance, as every file is well-defined in isolation. ~ from [here](https://github.com/typst/typst/pull/4907#issuecomment-2334429014)

@laurmaedje While I understand this design choice from a programming perspective, this just struck me as someone coming from LaTeX. As a suggestion to improve the user experience, would it be possible to introduce a new function (e.g. `#import-global`) that serves to import a module into every `.typ` file of the project?

```typ
#import-global "@preview/physica:0.9.5": *
```

For example, I have a `content/` folder with chapters as individual files. In every file, I want the following line to be included automatically at the top: `#import "@preview/physica:0.9.5": *`.

In comparision to your suggested workflow of importing a shared utility file (which holds the "global" imports) in every file, this `import-global` approach should not deteriorate robustness, predictability and performance, right?

Maybe this function could also accept an array of packages, e.g. something like this:

```typ
#import-global(
  "@preview/physica:0.9.5": *,
  // other packages you want to make globally available to the project
)
```

If the concern is performance, maybe it'd be feasible in the compiler to check in every file if a global import is actually made use of in it and if not, skip the import process.

**Comment by schmeisers** [comment]
I hope this gets reconsidered.  An `input()` function would be great.  Or a way to pass the entire scope into the `eval()` function so that we can roll our own.

**Comment by kgs233** [comment]
In typesetting, some things are global (the scope is the entire book or article), such as specific style functions and page settings. In the current Typst, these can only increase the bloat of the `main.typ` file or result in ugly and repetitive imports in each file. Typesetting does not follow a one-file-one-scope model, but rather a nested scope model from large to small (e.g., a book contains chapters, and a chapter contains sections). Designing a DSL for typesetting with the mindset of a conventional programming language is a poor approach.
