### ISSUE TITLE
Locate in numbering can overflow stack

### ISSUE THREAD

**Issue by werifu** [typst/typst#616]
Reproduce:
https://typst.app/project/w2Re4BikAWWRrhiKWPKja4

It seems that code like following will cause an stack overflow. I guess it calls the numbering function recursively when accessing to the element of the array.

```
#let image_num(num) = {
  locate(loc => {
    let imgs = query(figure.where(kind: "image"), loc)
    imgs.at(num - 1)
  })
}

#figure(
    image("avatar.jpeg", width: 30%),
    caption: [my caption],
    supplement:[Fig],
    numbering: image_num,
    kind: "image"
) <img0>

```

**Comment by laurmaedje** [comment]
The numbering argument directly gives you the numbers, no need to do locate and query here. The crash is not ideal anyway, of course.

**Comment by laurmaedje** [comment]
This doesn't crash anymore. It says "maximum show rule depth exceeded" now which is arguably a bit confusing here because there is no user-defined show rule, but it's talking about a built-in show rule. While there might be some potential for better diagnostics down the road, I'm still going to close this for now.
