### ISSUE TITLE
A Feasible Solution to SVG Text Rendering Issue

### ISSUE THREAD

**Issue by jerrita** [typst/typst#689]
When I using SVG as images, text is lost(#371).

 This problem seems to have occurred in earlier versions of usvg. I tried the following with usvg 0.30, and everything rendered correctly. I tried to modify the code in this repository, but I didn't understand the parts related to svg2pdf, so I didn't continue. 

Attached is some reference code, hoping to be helpful in solving this problem.

```rust
use std::{fs::File, io::Read};

use resvg::{render, tiny_skia};
use usvg::{fontdb, Options, Tree, TreeParsing, TreeTextToPath};

fn main() {
    let mut svg_file = File::open("in.svg").unwrap();
    let mut svg_data = Vec::new();
    svg_file.read_to_end(&mut svg_data).unwrap();

    let opt = Options::default();
    let mut tree = Tree::from_data(&svg_data, &opt).unwrap();

   
    let mut fontdb = fontdb::Database::new();
    fontdb.load_system_fonts();
    tree.convert_text(&fontdb);

    let pixmap_size = tree.size.to_screen_size();
    let mut pixmap = tiny_skia::Pixmap::new(pixmap_size.width(), pixmap_size.height()).unwrap();

    render(
        &tree,
        resvg::FitTo::Original,
        resvg::tiny_skia::Transform::default(),
        pixmap.as_mut()
    )
    .unwrap();

    pixmap.save_png("out.png").unwrap();
}
```

```toml
[dependencies]
usvg = "0.30" 
resvg = "0.30"
```

**Comment by laurmaedje** [comment]
The problem is that we currently do not provide a font database to usvg. We can't simply call `load_system_fonts` because this also has to work in our web app. And fontdb expects all fonts up-front whereas the web app lazily loads them on use. 

There are two possible approaches:
1. Initialize a fontdb with just the main font and use usvg to outline it
2. Extract the text with usvg and use Typst's text layout to display it

The first is simpler. Possibly it could be a good stop-gap solution. The text will not be copyable because usvg outlines, but that's better than nothing.

**Comment by astrale-sharp** [comment]
If we were to extract the text via usvg, what font should typst use to render the text? current style I assume

**Comment by jerrita** [comment]
See #709 @astrale-sharp

**Comment by laurmaedje** [comment]
An alternative version is now [implemented](https://github.com/typst/typst/commit/d09a0327fb0657177fc17f2cb1f49cf57b26319b).
