### ISSUE TITLE
bug: running CLI with --open can block, stopping recompilation when used with watch

### ISSUE THREAD

**Issue by tbethe** [typst/typst#704]
When running `typst watch --open`, the pdf is never recompiled after changes.

This is because the call used to open the pdf viewer can block on some systems. Evidently, on my system it does block.

**Comment by Coekjan** [comment]
Does `--open` block when no resource opener specified? I tested the behavior on #4430 , and here are some results:
1. `typst watch --open`: recompilation process is not blocked.
2. `typst watch --open /path/to/opener`: recompilation process is not blocked.
3. `typst watch --open /path/to/viewer`: recompilation process is blocked. I think this is because **viewers is different from resource openers**. The latter ones just **detached**, open the file with users' preferred application and **exit quickly**.

**Comment by tbethe** [comment]
I am unsure what you are asking. Are you asking me to test / try to reproduce your results?


----
To keep up real expectations. I might be able to do that next week, but there's a real possibility it won't happen.

**Comment by Coekjan** [comment]
> I am unsure what you are asking. Are you asking me to test / try to reproduce your results?

This issue said `--open` blocked the watch process. But when I checkout 6f625fc73cd17f1a1025e88022e67730fb11b5c4 (the last commit before your PR #706 ), compile the code and run `./target/debug/typst watch ../test.typ --open`, **the typst file does get recompiled**.

Only when running `./target/debug/typst watch ../test.typ --open <your-pdf-viewer>`, the typst file is not recompiled until "okular" exits.

So, was this issue only saying `typst watch ../test.typ --open <your-pdf-viewer>` got blocked?

**Comment by tbethe** [comment]
This was over a year ago, but i believe my use case was the following: 

I have a standard pdf viewer (probably okular) but I wanted a different viewer (mupdf) to open the pdf when I was watching a typst file.

So, using something like xdg open did not do it for me. 

In short, yes, the issue watch with watch AND --open when open is specifying a pdf viewer.

**Comment by Coekjan** [comment]
Thanks for your clarification!
