### ISSUE TITLE
'+' and '...' horizontal spacing issue

### ISSUE THREAD

**Issue by VincentTam** [typst/typst#713]
# Description

The spacing to the right of '+' after '...' (`dots.c.h`) is incorrect.

# Error output

`$a + dots.h.c + b$` gives
![error output](https://media.discordapp.net/attachments/1056574658771681361/1094941275951730698/rendered.png?width=405&height=172)

Here's the expected spacing to the right of '+'
![renderedBin](https://user-images.githubusercontent.com/5748535/230895973-695f0c99-c2c2-40e8-87fd-3cbb1eb60308.png)

The above images are downloaded from the bot's output on Discord.

# Technical details

`$a + dots.h.c + thin b$` gives output that looks the same.  I've included some screenshots here to illustrate the actual difference between the expected spacing to the right of '+' and the workaround's output.  There's a **difference of three pixels**.

![230410-typst-plusDots-rhsp](https://user-images.githubusercontent.com/5748535/230896852-457a47e6-ab96-42e3-a219-467b8a9c41a7.png)
![230410-typst-plusDots-lhsp](https://user-images.githubusercontent.com/5748535/230896856-2ea1385b-dcba-4762-bb63-a4692ca26ff7.png)
![230410-typst-plus-lhsp](https://user-images.githubusercontent.com/5748535/230896858-38f9e324-ebc9-4bda-9d05-fdd54b3c379f.png)
![230410-typst-plus-rhsp](https://user-images.githubusercontent.com/5748535/230896860-3aae0d66-316e-4242-ab81-660833157a6e.png)

**Comment by Liamolucko** [comment]
This has been bugging me too. I looked into it and it's because Unicode classifies '⋯' as a relation. This causes a '+' after any of them to be considered a unary operator, because it's only made a binary operator if it comes after a character classified as normal, alphabetic, closing or a fence:

https://github.com/typst/typst/blob/507efc3a1c14e8487705c7424d605a1663d3fe6e/crates/typst-library/src/math/row.rs#L56-L68

'⋱', '⋰', and '⋮' are also classified as relations, but the regular ellipsis '…' is actually classified as normal. To be honest, that classification makes more sense to me than a relation, and would also fix the spacing. Would it make sense to add a special case for this in `GlyphFragment::with_id` to classify '⋯', '⋱', '⋰', and '⋮' as normal, similar to what's already done for ':'?

https://github.com/typst/typst/blob/507efc3a1c14e8487705c7424d605a1663d3fe6e/crates/typst-library/src/math/fragment.rs#L217-L220

**Comment by laurmaedje** [comment]
@Liamolucko I didn't end up fixing this for some reason, but I came to the same conclusion: Unicode is wrong here. Your suggested fix seems fine.
