### ISSUE TITLE
Smarter parenthesis sizing

### ISSUE THREAD

**Issue by classabbyamp** [typst/typst#719]
```typ
#set text(size: 9pt)
$P(0|1) = 1/2 "erfc"((A-lambda)/sqrt(N_0/T_b))$, 
$P(1|0) = 1/2 "erfc"((A+lambda)/sqrt(N_0/T_b))$
```

![image](https://user-images.githubusercontent.com/5366828/230979318-eea218ab-a70b-4c9a-8ab3-eec294c7261d.png)

I would expect the contents of the `erfc()` to be the full height, or the parentheses to not be as tall

this was done locally, with typst-lsp v0.3.2 in vscode

**Comment by Enivex** [comment]
This doesn't look great in Latex either, because you typically want the main fraction line kept centered (like here). It's not really a bug.

![image](https://user-images.githubusercontent.com/2191754/230989344-dff532b8-d37e-4a33-883a-ca00f41e0b38.png)

In general I'd avoid writing "unbalanced" fractions like this, because it'll invariably end up looking bad. In this instance, I would recommend either introducing some notation for the quantity in the denominator, or at least write

![image](https://user-images.githubusercontent.com/2191754/230989513-f3a87b80-87bf-4008-aaee-651eeed9a0b6.png)

**Comment by classabbyamp** [comment]
> As an aside, you should check out https://typst.app/docs/reference/math/op/

I've seen that, but I was unsure how to define custom ones that can be used multiple places

**Comment by classabbyamp** [comment]
> I'd avoid writing "unbalanced" fractions like this in general, because it'll invariably end up looking bad. In this instance, I would recommend either introducing some notation for the quantity in the denominator, or at least write

even "balancing" that expression has the imbalance:

![image](https://user-images.githubusercontent.com/5366828/230993805-72ec8303-96b9-4d0c-bf39-52af3c69d2e2.png)

**Comment by Enivex** [comment]
Some imbalance is unavoidable if the convention of keeping the main fraction line centered is to be followed. You can see the same behavior in my second picture above, which is rendered in latex.

**Comment by classabbyamp** [comment]
does typst need to match what LaTeX does?

**Comment by Enivex** [comment]
More or less, though I'd argue that LaTeX has more refined spacing.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/360
