### ISSUE TITLE
Layout function doesn't work in grid?

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#739]
cc @PgBiel 

```
#grid(
  columns: 2,
  layout(size => line(
    angle: 90deg,
    length: size.height,
  )),
  lorem(100),
)
```

The line is the size of the page instead of the grid. Some context: https://github.com/typst/typst/issues/679. My goal is to draw a vertical line the size of the content.

**Comment by PgBiel** [comment]
Note that the behavior is the same as just using `length: 100%` (as that's what `layout` gives you - the equivalent of 100% in a given context). This is because your rows have size `auto`, so typst will draw your items inside a pod (box) with the height of the page. Adding `rows: 10em`, for example, shows that restricting rows makes this approach possible.

Here's your way around this:

```
#let mytext = lorem(100)

#layout(page_size => style(styles => grid(
  columns: 2,
  rows: measure(box(width: page_size.width, mytext), styles).height,
  line(
    angle: 90deg,
    length: 100%,
  ),
  mytext,
)))
```

(using `box(width: page_size.width)` instead of `box(width: 100%)` was necessary there, as it seems to understand `100%` as 0pt if the box isn't placed.)

**Comment by SUPERCILEX** [comment]
Clever, thank you! I feel like this should be easy to accomplish long-term, but this is a nice trick for now.

---

Ended up using this:
```
  layout(size => grid(
    columns: 2,
    line(
      angle: 90deg,
      length: measure(box(width: size.width, body), styles).height,
      stroke: stroke,
    ),
    body,
  ))
```
