### ISSUE TITLE
Functions defined in one file are not recognised in included file

### ISSUE THREAD

**Issue by nikmennega** [typst/typst#754]
```
// main.typ
= Define our `let` binding
#let simple = emph

We have defined a #type(simple) named `#simple`.

= Using `#simple` in main file

#simple[
	#lorem(8)
	Come on in, the lorem's fine!
	#lorem(12)
]

#include("included.typ")
```

```
// included.typ
= Using `#simple` in imported file

#simple[
	#lorem(8)
	Some great lorem in here!
	#lorem(12)
]
```
## Expected behaviour
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1085754/231418318-4acc746c-87ff-4f6a-a664-d66d12cb7282.png">

## Experienced behaviour
```
watching main.typ
writing to main.pdf

[19:36:47] compiled with errors

error: unknown variable
  ┌─ included.typ:7:1
  │
7 │ #simple[
  │  ^^^^^^

help: error occurred while importing this module
   ┌─ main.typ:15:8
   │
15 │ #include("included.typ")
   │         ^^^^^^^^^^^^^^^^
```

**Comment by laurmaedje** [comment]
This is actually working as expected. Each module has its own scope and if you want to have shared functions its best to define them in a third file that you import in `main.typ` and `included.typ` with [`#import`](https://typst.app/docs/reference/scripting/#modules).

**Comment by laurmaedje** [comment]
The reason for this is that this way a module is free-standing. In your proposed design a module could result in different things depending on from where it is imported. That would complicate things a lot.

**Comment by laurmaedje** [comment]
Side note: The syntax is `#include "text/lorem.typ"`, the parentheses just happen to be allowed.

**Comment by laurmaedje** [comment]
If I understand what you want correctly, the below setup would lead to "1 2" being displayed in your proposal. That means that `foo.typ` needs to be evaluated twice, once with the context of `a.typ` and once with the context of `b.typ`. Currently, each module is evaluated just once.
```
// main.typ
#include "a.typ"
#include "b.typ"

// a.typ
#let foo = 1
#include "foo.typ"

// b.typ
#let foo = 2
#include "foo.typ"

// foo.typ
#foo
```

**Comment by nikmennega** [comment]
That explanation makes things a bit more clear, thank you.

In [my use case](#issuecomment-1506968248), I only *want* to include things once. There's discussion in issue #553 about `scope` arguments. I still think it would be desirable (because…I desire it :-]) to `#import` a module and have its let bindings be available to (understood by) subsequent `#include` statements: would a similar treatment for either `#let` or `#import` be reasonable?

Example:
```
// layout.typ
#let(global) simple = emph
```
or perhaps:
```
// document.typ
#import(scope: global, "layout.typ"): *
```
I guess this issue becomes a feature request instead of a bug.

**Comment by pricklygorse** [comment]
If I'm correct, one way to approach this is to pass the global functions and variables to each included file? Bit messy if you have a lot that needs passing though

```
//main.typ

#let amazed(term) = box[✨ #term ✨]
#let var1 = "66"

// import sub document instead of include
#import("doc1.typ"): *

#show: doc1.with(var1: var1, 
                  funct: amazed
                 )

// doc1.typ
//wrap document in this function
#let doc1(
  var1: none,
  funct: none,
  body,
) = {
[ 
  = Document starts here
 
 Then runs the function originally defined in main.typ #funct(var1)

 ]
}

```

**Comment by laurmaedje** [comment]
Generally, I would rather put `amazed` and `var1` into a third file and import them into `doc1.typ` and `include` `doc1.typ` in `main.typ`.

**Comment by laurmaedje** [comment]
I see. You could probably achieve this via [state](https://typst.app/docs/reference/introspection/state/).

**Comment by kapple19** [comment]
This makes Typst projects unscalable. Take the following book project, for example. I was hoping to support a filesystem structure of:

```
project_folder
├─ my-book.typ
├─ chapter_one/
│  ├─ main.typ
│  ├─ section_one/
│  │  ├─ main.typ
│  │  ├─ subsection_one.typ
│  │  ├─ subsection_two.typ
│  │  └─ subsection_three.typ
│  └─ section_two/
│     ├─ main.typ
│     ├─ subsection_one.typ
│     └─ subsection_two.typ
└─ chapter_two/
   ├─ main.typ
   ├─ section_one/
   │  ├─ main.typ
   │  ├─ subsection_one.typ
   │  ├─ subsection_two.typ
   └─ section_two/
      ├─ main.typ
      ├─ subsection_one.typ
      ├─ subsection_two.typ
      └─ subsection_three.typ
```
where each `main.typ` manually `include`s the adjacent `*.typ` and `*/main.typ` files.

I'm not going to create a `definitions.typ` module and `import` them into every single `*.typ` file in this filesystem hierarchy.

And I'm not going to have one enormous `*.typ` file.

LaTeX is excellent at supporting this document scalability. The fact that Typst does not support this makes it a non-viable alternative to LaTeX for large scale documentation projects. Books!

The concept of programming/typesetting languages is to provide user ease and automation for performing certain behaviours. The workings of the language does the hard parts internal to the language, and can hide such difficulties from the user. You solve the problems once _inside_ the language's design, and that solution becomes reusable to its users. This design choice of yours makes your users repeatedly implement workarounds and boilerplate that contradicts the idea of why a programming/typesetting language is created in the first place.

**Comment by kapple19** [comment]
Maybe a viable alternative for is to define a new type of file, something like `*.subtyp` which is expected to be included in a `*.typ` or another `*.subtyp` file.

**Comment by Enivex** [comment]
@kapple19

Having a separate file for each chapter is fairly reasonable, but splitting up the document to the level of subsections passes into what I'd consider ridiculousness.

Regardless, I'm a bit confused as to what your actual problem with importing a file of definitions is. It's a single line. What part of that is not scalable?

**Comment by kapple19** [comment]
Thanks for the clarification request.

> splitting up the document to the level of subsections passes into what I'd consider ridiculousness.

I can see why you think it's ridiculous.
I've tried out different collation patterns, and a topically hierarchical structure turned out to be the best.
Think of a LaTeX file with parts, chapters, sections, subsections, and subsubsections.
Think of each subsection as dedicated to a specific topic for derivations, dissections, visualisations, etc.

I work in ocean sonar, so an example of a tree path of topical layers is: ocean acoustics, acoustic propagation, beam propagation models, Gaussian beams, Gaussian beam pressure.
At every layer of this topical hierarchy, there's many branches off into other topics.
E.g. at the very top layers, there's: acoustical oceanography, ocean acoustics, sonar signal processing, and statistical detection theory.
E.g. at the beam propagation models layer, there's: parabolic equation models, normal modes, finite difference/element/volume, and others.

Having Typst's "Markdown with code" kind of design is ideal for the scale of this personal wiki I'm building.
All the topics in this hierarchy need to be able to refer to each other (e.g. equations, plots, etc).
And I definitely need a format that can take in runnable code with minimal boilerplate to get working.

Now, my gripe is that it's not just a single line, it's mostly two lines at each non-"leaf" layer of the topical hierarchy:

1. The `#import` of definitions, setups, etc.
2. The `#include` of nested topics one layer deeper for each topic.

The most specific topics that don't have sub-parts (subsections, or subsubsections, etc.) only need to `#import`.
On top of that, since such a complicated hierarchical structure is best organised into a nested filesystem, each time I `#import` my definitions, I have to keep track of how many layers up the filesystem I have to specify the definitions file location relative to that file.
And that also makes for a nightmare when I decide to reorganise my files, e.g. moving topics up/down the layers.

In addition to Typst I've also tried out many other formats, and am still open to learning of others. Typst seemed the best for my personal wiki, bar this one design choice that I and others have queried. Let me know if you guys know of any other alternatives that I may not have tried, thanks in advance!

**Comment by laurmaedje** [comment]
> On top of that, since such a complicated hierarchical structure is best organised into a nested filesystem, each time I #import my definitions from the parent directory, I have to keep track of how many layers up the filesystem I have to specify the definitions file location relative to that file.

You can use an absolute import (with a leading slash) to import relative to the project root. In combination with a wildcard import, it's the same single line in every of your files: `#import "/common.typ": *`.

**Comment by mbivert** [comment]
Somewhat related: I have a project structured as follow: (see [typst-754.zip](https://github.com/user-attachments/files/17401652/typst-754.zip))

 ```
defs/
     vector-space.typ
    ...

prelude.typ

path/to/document.typ

other/path/to/other/document.typ
```

The goal being to share `defs/*` (or `thms/*`, etc.) among multiple files.

Then:

1. As already stated ITT, one can't `#include "../../defs/vector-space.typ"`: I understand the security concerns; the default behavior is reasonable, but having a way to override it could be useful (we often *known* what we're including);
2. Alright, so I can configure `--root` (side issue: this requires my text editor to be smarter), but then I indeed need a `prelude.typ`, to be included everywhere (cumbersome: I'm going to have dozens of files in `defs/` & cie).
3. Furthermore, in this case, the prelude currently imports `"@preview/ctheorems:1.1.2": *`, defines a `#definition` & cie; `defs/vector-space.typ` naturally contains a `#definition[…]` : for some reasons the output gets messed-up (counters ignored, content centered, etc.)

This last issue may be within `ctheorems`, but overall, I think a *dumb*, à-là-`cpp(1)` `#include` could be useful. Calling it e.g. `#input` (mimicking LaTeX's `\input`) wouldn't interfere with `#import/#include`; it could support arbitrary input file locations, eventually guarded by a command flag if desirable.

The only workaround I can think of so far is to have a separate pre-processing stage performing such dumb inclusions (a simple `awk` script should do).
