### ISSUE TITLE
Feature request: import module from common directory

### ISSUE THREAD

**Issue by George-Miao** [typst/typst#764]
For my current latex workflow, I have a `common.tex` at `~/texmk/tex/latex/commonstuff/` which can be included via `usepackage` directly using `latexmk` without specifying the relative or absolute directory, and it is used in all my paper and notes. I really wish I can do the same in typst. As of what I know, typst doesn't have such commonstuff directory? And, as a generalization of this idea, is plugins or even package managers planned for future? The modular design typst currently has is really suitable for such plugin system.

No matter what, thanks for creating such an amazing project!

**Comment by laurmaedje** [comment]
A package manager is planned. For now, a common directory could be realized by setting `TYPST_ROOT` to that directory and then using absolute paths with leading slash to import from there and relative paths otherwise. Note that TYPST_ROOT was only recently merged and is not in the latest release. In the future, we might also have a better solution for such a common directory.

**Comment by George-Miao** [comment]
I'm really interested in contributing to the project. Is there any way to get started, e.g. good first issues?

**Comment by KronosTheLate** [comment]
A package manager does not solve the use-case where I want to define a template locally, and have it accessable in any (local) typst document I create regardless of file location. Is that use-case covered elsewhere, or was this issue closed a little prematurely?

**Comment by laurmaedje** [comment]
You can make a local package: https://github.com/typst/packages#local-packages

**Comment by KronosTheLate** [comment]
True. That is a decent fix for now. 

Ideally there would be a config file (toml/yaml or something similar) where one could add a path, and when including a file, if it is not found in the local directory, it is looked for in that path. That would be better because it would 
- allow arbitrary file locations, 
- avoid having to make a rigid folder structure just to define a template, and 
- turn `#import "@local/mypkg:1.0.0": *` into `#import "template1.typ": *`. I would likely have to look up the former style several times, and find it a hassle having to think about versioning of a simple local template.

It also seems like something that would be simple to avoid breaking, whereas the local package solution has a warning about potential future breakage.
