### ISSUE TITLE
A bug about counter and page break?

### ISSUE THREAD

**Issue by lsl00** [typst/typst#804]
Here is the code:
```
#let chapterCounter = counter("chapter")
#chapterCounter.update(0)
#let chapte(chname,content) = {
  chapterCounter.step()
  set page(
    columns: 2,
    header: "Chapter" + chapterCounter.display("1. ")
    + chname,
    numbering: "1"
  )
  content
}

#chapte("First")[
  #lorem(100)
]
#chapte("Second")[
  #lorem(200)
]
```

And between chapter First and Second,there will be a blank page with nothing:
<img width="224" alt="Screenshot 2023-04-15 at 00 27 39" src="https://user-images.githubusercontent.com/39242557/232102202-288b6314-66a3-4dfe-b6f5-243804b89202.png">

**Comment by laurmaedje** [comment]
It's because `set page` forces a pagebreak if content is before it and the `counter.step()` is content (and it occupies the empty page). You can either try moving the steps/update after the set page rule, or just use one global set rule for pages in combination with queries as explained [here](https://typst.app/docs/reference/meta/query/). The current behaviour is expected, but certainly not ideal.

**Comment by laurmaedje** [comment]
Not ideal, but basically working as intended.
