### ISSUE TITLE
Parsing 5π/6 as frac(5π, 6) instead of 5 frac(π, 6)?

### ISSUE THREAD

**Issue by user202729** [typst/typst#820]
As in the title. I think the former behavior makes more sense _especially_ when there's no space between 5 and π.

**Comment by Enivex** [comment]
Write `(5pi)/6` if you want the former.

**Comment by user202729** [comment]
Yes but I think Typst tries to parse things "intelligently" e.g. it is parsing f(x)/g(x) as expected, and this would make the input more ergonomic as well.

**Comment by Enivex** [comment]
I would definitely expect it to render 5 frac(pi,6), and would prefer the least amount of "intelligence". The most frustrating experience is having to fight against behavior like that.

That f(x)/g(x) renders like frac(f(x),g(x)) is more natural, because f(x) is "one unit". Though I'm conflicted, because I'm imagining scenarios where even that is too intelligent.

**Comment by user202729** [comment]
Up to the developers then. I feel intelligence is "intended" for example because of the f(x)/g(x) as above.

**Comment by user202729** [comment]
Interestingly `∂(a, b)` does not get the same special treatment as `f(a, b)`. (this one is especially common in Jacobian notation for multivariate calculus)

**Comment by owiecc** [comment]
Julia has [numeric literal coefficients](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#man-numeric-literal-coefficients) and it is quite nice. Examples: `1/2π`, `x^2y`, `4x^3 +3x^2 + 2x + 1`. There are a few edge cases but you can alway be explicit there.

**Comment by laurmaedje** [comment]
I agree that this is probably a bit too smart, so I would rather not have this.
