### ISSUE TITLE
Text background-color

### ISSUE THREAD

**Issue by dsantiago** [typst/typst#855]
As discussed [here](https://github.com/typst/typst/discussions/845), I accepted the answer even tough I still think there should be a proper way to do this and, imo, it's a basic function to have background-color built-in for text.

**Comment by laurmaedje** [comment]
> it's a basic function to have background-color built-in for text.

I agree. I'll try to work on it soon-ish.

**Comment by jgclark** [comment]
As another workaround for now, kind soul @Enivex on Discord has produced these:
```typst
#let highlight(color, body) = {
  let whole = body.split()
  for word in whole {
    box(inset: (x: 0.125em), outset: (y: 0.25em),fill: rgb(#color),word)
  }
}
```

Or simpler still is to tweak strikethrough's overlay (though it can therefore change the text color a bit):
```
#let highlight(color, body) = strike(stroke: 1.1em + rgb(color),body)
```

**Comment by mangkoran** [comment]
May I know if there is any roadmap for this?

**Comment by laurmaedje** [comment]
I have to admit that I forgot about this. This should be fairly easy though so maybe somebody would be willing to pick it up. If not, I'll take a stab in the next weeks.

**Comment by laurmaedje** [comment]
The design with a `highlight` function akin to `strike` is a good one, I think and preferrable over a background property on the text function.

**Comment by jgclark** [comment]
However, strike comes in front of the text, so it partially obscures it. What I'm after is a form of highlighting (however that is implemented) where black text remains black, and not grey as it overlaid with a lighter colour. Thanks.

**Comment by laurmaedje** [comment]
> However, strike comes in front of the text, so it partially obscures it. What I'm after is a form of highlighting (however that is implemented) where black text remains black, and not grey as it overlaid with a lighter colour. Thanks.

Oh, I see how my comment could be confusing. I didn't mean that using strike to highlight things is a good solution. I meant that implement a new built-in `highlight` function with a similar design to `strike` is preferable to having a `background-color` option on the `text` function.

**Comment by jgclark** [comment]
> Oh, I see how my comment could be confusing. I didn't mean that using strike to highlight things is a good solution. I meant that implementing a new built-in `highlight` function with a similar design to `strike` is preferable over having a `background-color` option on the `text` function.

OK! Thanks for clarifying that, and thanks for considering the feature request.

**Comment by mangkoran** [comment]
> Oh, I see how my comment could be confusing. I didn't mean that using strike to highlight things is a good solution. I meant that implementing a new built-in highlight function with a similar design to strike is preferable over having a background-color option on the text function.

Thank you for the clarification. From what I thought based on your idea, it seems the reason is due to `background-color` could have several parameters, such as color, margin, padding, etc. However, it seems it is also possible to have it as `text` option with dictionary as its type, isn't it? (cmiiw)

**Comment by laurmaedje** [comment]
> However, it seems it is also possible to have it as text option with [dictionary](https://typst.app/docs/reference/types/dictionary) as its type, isn't it? (cmiiw)

It would, but the `highlight` design is cleaner in my opinion.

When something is a text property, you can do:
```
#set text(property: value) // everywhere
#text(property: value)[just here]
```

Whereas, when it is a function, you can do:
```
#show: highlight // everywhere
#highlight[just here]
```

Both approaches allow local and global customization, but text properties generally favor global whereas extras functions favor local. I think you typically want to highlight just a phrase as opposed to the full text. It also makes it easy to set individual properties of the highlighting with a set rule without actually highlighting something, which is not really possible for a text property:

```
#set highlight(fill: red.lighten(20%))
#highlight[I have a red background!]
```

**Comment by ntjess** [comment]
> Or simpler still is to tweak strikethrough's overlay (though it can therefore change the text color a bit):
> 
> ```
> #let highlight(color, body) = strike(stroke: 1.1em + rgb(color),body)
> ```

@jgclark You can avoid changing the text color by simply `place`ing this stroke behind the text:

```typst
#let highlight(body) = {
  place(strike(stroke: 1.1em + yellow, body))
  body
}
```

For me, this gives the right visual result at the cost of having text appear twice in the document if that is a concern:
![image](https://github.com/typst/typst/assets/23620506/ad2380e7-611b-4a90-94ff-1fd0b1fdb2bb)

**Comment by LuxxxLucy** [comment]
> > However, strike comes in front of the text, so it partially obscures it. What I'm after is a form of highlighting (however that is implemented) where black text remains black, and not grey as it overlaid with a lighter colour. Thanks.
> 
> Oh, I see how my comment could be confusing. I didn't mean that using strike to highlight things is a good solution. I meant that implementing a new built-in `highlight` function with a similar design to `strike` is preferable over having a `background-color` option on the `text` function.

Hi new comer here. I just started looking into this issue. From what I understand, the suggestion is that we implement the background color filling feature by a function `highlight`, internally it should be treated as a `Decoration` and it is layouted below the frame of content text. Is my understanding correct? 

*Question 1*: For the interface, it seems that the highlight does not need a stroke argument but simply a Paint/Color;  so the hightlight function can take a color as argument

```
#highlight(blue)[some text]
```

Is this an acceptable design?

*Question 2*: Internally I am thinking of wrapping the Stroke into the DecoLine enum and then maybe some refactoring on it so that the decoration function call will be able to handle both over/under/strike line with a stroke as well as the background highlight with a color. Is is okay?

If nothing goes wrong, I will try to push a PR soon.

**Comment by laurmaedje** [comment]
@LuxxxLucy This all sounds good. It's correct that it wouldn't need a stroke and the refactoring sounds fine too.

**Comment by LuxxxLucy** [comment]
Hi I just update with an initial version of the background highlight function #2076.  The examples are 

```
This is the built-in #highlight[highlight with default color]. We can also specify a customized value #highlight(fill: rgb("abcdef88"))[
```

which renders to like this 
<img width="717" alt="image" src="https://github.com/typst/typst/assets/19356905/db259b01-c1ea-4774-9761-ad915c665031">

Now, I would like to consult with you for two design issues.
1. I assume that most of the time people just uses `#highlight[some text]` instead of specifing a `fill`, so it is important to specify a good default color. What do you think to be a good default value?
2. Now I implemented the height of the background rectangle to be the sum of the descender and acsender of the font.
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Typography_Line_Terms.svg/880px-Typography_Line_Terms.svg.png). But I am not sure whether it is a good solution. There are other options, such as using the cap height plus descender height. Or  we can also compute it dynamically given the text, that is, that is, we compute the highest height and the lowest height give a text and uses these two to create an rectangle.

What do you guys think? I think I will need some input advice from you in order to proceed.

**Comment by laurmaedje** [comment]
@LuxxxLucy I responded to your design issues directly on the PR.

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/2076
