### ISSUE TITLE
Passing content inside " causes cryptic error

### ISSUE THREAD

**Issue by KronosTheLate** [typst/typst#865]
The following works fine:
![image](https://user-images.githubusercontent.com/61620837/232765004-b9d5c2c1-89c4-4824-8476-4ab07d82999b.png)

We see that both function calls pass `content` to the function. We can access the `text` field of content when using the first fuction call:
![image](https://user-images.githubusercontent.com/61620837/232765210-a54daa19-2d03-4b85-b1a4-c42d94c9bbc1.png)

However, when I uncomment the second call, I get the following error from the VSCode extension:
![image](https://user-images.githubusercontent.com/61620837/232765763-f692b694-2e23-4d15-864d-bc851dc6f38f.png)

The full error from the CLI is as follows:
![image](https://user-images.githubusercontent.com/61620837/232766016-b31efbea-fe35-4871-b07a-ab4db88d0167.png)

So if I could access the `text` field before, why can I not now? What fields does `content` have, and how can I get an overview?

Related is the fact that despite the quote "Wherever content is expected, you can also pass a [string](https://typst.app/docs/reference/types/string/) or none." from https://typst.app/docs/reference/types/content/, I get also an error when I pass a string instead of content:
```
#let bla(content) = {
    type(content)
    linebreak()
    content.text
}
#bla[test1]
#bla("test2")
```
gives
```
Report $typst compile 5_conclusion.typ 
error: cannot access fields on type string
  ┌─ 5_conclusion.typ:6:12
  │
6 │     content.text
  │             ^^^^

help: error occurred in this call of function `bla`
  ┌─ 5_conclusion.typ:9:1
  │
9 │ #bla("test2")
  │  ^^^^^^^^^^^^

Report $

```

**Comment by laurmaedje** [comment]
> So if I could access the text field before, why can I not now? What fields does content have, and how can I get an overview?

The fields depend on what the content contains. If you construct `#let it = heading(level: 1)[stuff]`, then you can access `it.level` and `it.body` because these are the two [arguments of the heading function](https://typst.app/docs/reference/meta/heading/) you provided. You can access the same fields on `#let it = [= stuff]` because its the same thing. The `.text` field is only available if the content consists of a single text element, which is not the case in your example because the quotes are [smartquotes](https://typst.app/docs/reference/text/smartquote/). If you have a content variable `x`, you can see the available fields with `repr(x)` or by hovering over it.

> Wherever content is expected, you can also pass a [string](https://typst.app/docs/reference/types/string/) or none.

This applies to built-in functions that accept content. Your `bla` function doesn't "expect content" in that sense since you can't specify at all what it expects. Just naming the variable `content` has no special effect, so you just get the string.

Hope this helps.
