### ISSUE TITLE
Image rotation is all wonky

### ISSUE THREAD

**Issue by KronosTheLate** [typst/typst#870]
The same image, with the same orientation and resolution, it rendered in 3 different orientations depending on the file type. Only `jpg` is the right way. The images and generated PDF can be found in [this drive folder](https://drive.google.com/drive/folders/1VvVjEUOg3EMbYVVM-Lf7VpnZj89KBETE?usp=sharing). The code to generate the relevant part of the pdf is 
```
#set image(width: 40%)
#figure(image("images/pictures/setup.jpg"))
#figure(image("images/pictures/setup.jpeg"))
#figure(image("images/pictures/setup.png"))
```

Below are screenshots for convenience:
![image](https://user-images.githubusercontent.com/61620837/232813067-3a22bc1f-74e8-46d5-9b57-bd380c09af88.png)
![image](https://user-images.githubusercontent.com/61620837/232813324-0311f09c-aece-464a-ad18-a10b61657355.png)

Version:
```
my_dir $typst --version
typst 0.2.0 (1e948f7f)
```

**Comment by laurmaedje** [comment]
The problem might be that the image specifies its rotation with EXIF metadata or something like that.

**Comment by KronosTheLate** [comment]
I have not had this problem with SVG, PNG or JPG in a little while, and figured it had been fixed. However, when transferring another image from my phone (Oneplus 6), the problem was back. So I have only observed the problem with images from my phone.

**Comment by Fevol** [comment]
Can confirm that this issue is related to the rotation only being specified by the EXIF metadata, which can be quite troublesome when importing dozens of images taken from your phone into a document. Rotating doesn't work perfectly either, as this doesn't affect the layout (yet).

Two possible bodges:
1. Rotating the image with `reflow` enabled (only possible once v0.11) 
2. Using an external tool like `jhead` to losslessly rotate the base images based on the EXIF orientation data (command: `jhead -autorot *.jpg`)
