### ISSUE TITLE
ref() does not properly allow supplement: none (and more)

### ISSUE THREAD

**Issue by Enivex** [typst/typst#873]
This was discussed in the Discord yesterday, and I thought I'd create an issue.

In mathematics equations are almost invariably referred to with (1) and not Equation 1 in text.
```
\begin{equation}
\label{name}
a^2 + b^2 = c^2
\end{equation}
```
In LaTeX this is achieved with `\eqref{name}` (while the latter would be \Cref{name} using cleveref).

In Typst it can be done with `(@name[])`, but this is obviously tedious to write (especially considering the parenthetical below). Therefore I would like to either make `@name` display this way automatically, or create an eqref function. However

`#let eqref1(x) = [(#ref(x,supplement: none))]` displays as (Equation 1), i.e. as if it was auto
`#let eqref2(x) = [(#ref(x,supplement: ""))]` and `#let eqref3(x) = [(#ref(x,supplement: []))]` display as ( 1), i.e. with a spurious space added.

(There should be boxes in all of these to prevent line breaks, but I didn't want to confuse the issue)

_Side question:_ Is it possible to define the function in such a way that it can be called more easily than `#eqref(<name>)`?

**Comment by Enivex** [comment]
I could add that @laurmaedje created the following workaround
````
#show ref: it => {
  let elems = query(it.target, it.location())
  if elems.len() > 0 and elems.first().func() == math.equation {
    let elem = elems.first()
    numbering(
      elem.numbering, 
      ..counter(math.equation).at(elem.location())
    )
  } else {
    it
  }
}
````
which makes @name display the correct way

**Comment by Enivex** [comment]
Related issues: https://github.com/typst/typst/issues/643 https://github.com/typst/typst/issues/523

**Comment by laurmaedje** [comment]
Setting the supplement to `none` should work now. I also added a new `supplement` parameter directly for equations, so you can do `#set math.equation(supplement: none)`. What's still missing then are the parentheses because these are trimmed by default: Prefix + suffix are removed because otherwise you'd get e.g.`Section 1.` instead of `Section 1` for heading numbering `1.`. For equations it removes the parenthesis. To get them back, you'd have to write a show rule for now, as follows (to undo the trimming only for equations):
```
#set math.equation(supplement: none)
#show ref: it => {
  if it.element != none and it.element.func() == math.equation {
    [(#it)]
  } else {
    it
  }
}
```
