### ISSUE TITLE
More efficient font subsetting

### ISSUE THREAD

**Issue by 0ip** [typst/typst#895]
Based on my own oberservations and this discussion (https://github.com/typst/typst/discussions/404), I am wondering if font subsetting in Typst is working adequately right now.

Brief demonstration: a simple document containing two embedded fonts results in a file size of 207 KB:

![image](https://user-images.githubusercontent.com/757230/233369689-deb08f59-ef16-423d-872b-d7ac571f37f8.png)

By applying font subsetting (which the [online tool](https://www.wecompress.com/en/analyze) apparently does), the file size can be drastically reduced to 13 KB:

![image](https://user-images.githubusercontent.com/757230/233370038-ed7dcc65-82b2-41d7-acdb-0e318cbd4f43.png)

Raw files:
- [main.pdf](https://github.com/typst/typst/files/11286313/main.pdf)
- [main_compressed.pdf](https://github.com/typst/typst/files/11286311/main_compressed.pdf)

**Comment by Wybxc** [comment]
This issue is more severe on the CJK character set. I tested it on the Source Han Serif font, and the original font file is about 18MB. The document generated by typst contains 2MB of fonts, but after further compression, the actual used glyph data is only 47KB.

**Comment by laurmaedje** [comment]
CFF font subsetting is unfortunately rather complicated.

**Comment by Andrew15-5** [comment]
Consider using binary prefixes to remove any confusion with the legacy SI prefixes. See https://en.m.wikipedia.org/wiki/Binary_prefix. Also note that KB is not an existing unit of measurement. There is either kB or KiB (which are 1000 B and 1024 B respectively).

**Comment by laurmaedje** [comment]
KB is very widely used, I don't see the problem here since the difference between 1000 and 1024 barely matters in the grand scheme of the differences here.

**Comment by Andrew15-5** [comment]
If we were talking about differences between 2 TB and 2 TiB, will you say that it barely matters then?

As I said, SI units are "deprecated" and shouldn't used in context of file/storage sizes. The modern and already wide-spread IEC prefixes should be used instead (a lot of FOSS software already uses it). Did you know that Window$ is using GB when referring to GiB? By not adapting the superior and very clear (in understanding) units, you are contributing to this confusion even more. I want to live in the world where everyone can easily undestand each other. But if the world will (still) use SI for file sizes... This will be not the world we should strive to.

And again, KB is more confusing because it isn't SI or IEC prefix. It simply does not exist. It's like saying "a file is 234 shmabytes. Do anyone know what shambytes is? No. Please stop using KB. Especially when you/everyone (now) know the truth. (As you and me in the past, a big majority of people doesn't know about IEC units, and assume that SI are computed as IEC units. My goal is to clear things up in that matter.)

**Comment by laurmaedje** [comment]
This issue is not the right place to discuss this.

**Comment by Andrew15-5** [comment]
Indeed. That's why I said "Consider ..." instead of "Why not ...? Let's discuss!".

**Comment by wdscxsj** [comment]
> CFF font subsetting is unfortunately rather complicated.

I agree. Just for the record, it took [over a year](https://www.princexml.com/forum/topic/4653/pdf-with-otf-subsetting-is-still-too-large) for PrinceXML to implement good CFF subsetting. And for Affinity Designer, it's still an issue after 3 years since it's [reported](https://forum.affinity.serif.com/index.php?/topic/117446-korean-glyphs-in-source-han-sans-cause-pdf-export-to-fail/).

**Comment by 0ip** [comment]
> Just for the record, it took [over a year](https://www.princexml.com/forum/topic/4653/pdf-with-otf-subsetting-is-still-too-large) for PrinceXML to implement good CFF subsetting

Apparently, the subsetter (along other font tools) used for PrinceXML was extracted into a [Rust library (allsorts)](https://github.com/yeslogic/allsorts). I'm no expert in terms of font shaping, subsetting etc. and neither do I know much about Rust, so forgive me if this library was already mentioned somewhere and deemed to be inapropriate to be used for Typst. I'd be happy to be proved wrong.
