### ISSUE TITLE
Don't include tracing in release mode?

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#951]
Saw https://github.com/typst/typst/pull/761 was merged, but it doesn't look like there are cfgs to remove the tracing code in release mode. If this is intentional, it'd be good to confirm with hyperfine that there is no performance penalty and do a binary size diff.

The tracing code can be removed in release mode with these feature flags: https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters

**Comment by SUPERCILEX** [comment]
Cc @Dherse

**Comment by Dherse** [comment]
It's been tested on multiple PCs and when tracing is disabled (by not enabling verbosity or flamegraph features) it has not performance impact that we could measure. However, if you have more samples such that it does cause performance issues, @dccsillag and I would be very interested!

Additionally, by default, tracing is fully disabled.

However, as we have a working benchmarking harness, I'll be testing again with conformal benchmarking ;)

**Comment by SUPERCILEX** [comment]
> by default, tracing is fully disabled

But not compiled out though, right? Lemme just test this lol so I can stop worrying about it. :)

**Comment by Dherse** [comment]
> But not compiled out though, right? Lemme just test this lol so I can stop worrying about it. :)

They're part of the final binary, but performance impact was, in our testing, not measurable/within the "noise floor".
However, as I said, I'll be running it in the benchmark harness while I sleep with a large number of samples just to be sure :)

**Comment by SUPERCILEX** [comment]
```
│ 2 │ new        │ file │ 21.8 MB │ a minute ago   │
│ 3 │ old        │ file │ 20.9 MB │ now            │
```

So a ~1MB increase in binary size. This feels like too much to me.

```
Benchmark 1: ./old compile tmp.typ
  Time (mean ± σ):     521.4 ms ±   3.0 ms    [User: 486.8 ms, System: 41.2 ms]
  Range (min … max):   517.4 ms … 528.2 ms    10 runs
 
Benchmark 2: ./new compile tmp.typ
  Time (mean ± σ):     533.9 ms ±   2.7 ms    [User: 504.2 ms, System: 36.5 ms]
  Range (min … max):   529.4 ms … 537.9 ms    10 runs
 
Summary
  './old compile tmp.typ' ran
    1.02 ± 0.01 times faster than './new compile tmp.typ'
```

And 1-2% slower. Again, not great IMO for something that should only be used in development.

**Comment by Dherse** [comment]
Assuming that typst reaches broad usage, we may run into issues where people cannot share their documents in case they run into bugs and for these people (that may also not have control over their environment), being able to send us trace, logs or flamegraphs can be very useful. As far as performance testing with hyperfine, I don't recommend it (@dccsillag can explain into details the statistical reasons why) and 1% is well within the noise of benching typst with 10 samples.

With regards to binary size, I hadn't compared it, but every time we add dependencies we add to the binary size. And I don't think it's tracing, it's more likely the flamegraph renderer (inferno) which imo, we could reduce by disabling the multithreading features, if that's a concern. That's after all, a very easy improvement.

**Comment by SUPERCILEX** [comment]
Actually, let me solidify my opinion: I think that no matter how insignificant, anything that is only needed for development should not affect the release binary. Exceptions to this rule should be rare and only allowed if the development costs significantly outweigh the release benefits.

In this specific instance, I'm pretty sure we just need to add a feature flag and cfg out the tracing code.

> 1% is well within the noise of benching typst with 10 samples.

Look at the specific timings. `new` fastest run is `529.4ms` which is still slower than `old`'s slowest run at `528.2ms`. I highly doubt this is noise, though would be curious to know why you disagree.

> we may run into issues where people cannot share their documents in case they run into bugs and for these people (that may also not have control over their environment)

Hmmm, so the idea is that we actually want to ship tracing in the code so that people can share traces? I don't think that's incompatible with the idea of using a feature flag, at least for the web app where binary size matters way more. And it can be enabled by default for the CLI, though honestly I feel like people using the CLI would be capable of compiling from source.

**Comment by Dherse** [comment]
Using cobench, a statistical benchmarking tool built by @dccsillag (not publically available, yet), we get, in a 95% confidence interval, a range between 46 ms faster and 45ms slower
![image](https://user-images.githubusercontent.com/9665250/233870436-5b9233f1-e813-4f6d-90d7-1058925e8376.png)

And to be more explicit, the only proper way of doing benchmarking is by limiting external variables which we take into account when benchmarking using cobench. We have been working for a week on proper benchmarking that ignores and limits sources of noise introduced by external factors.

> I think that no matter how insignificant, anything that is only needed for development should not affect the release binary. 
I agree with this statement, but I'd argue that tracing and the ability to provide traces/logs in general are not development only. There are many cases where production software has bug reporting tools that ship logs along with the error so that it's easier for maintainers/developers to investigate and debug. And we cannot make the assumption that every Typst user will be familiar with software development.

> Look at the specific timings. 
Ten runs are not sufficient to make this kind of conclusion: see @dccsillag my stats guru please explain <3

> at least for the web app where binary size matters way more.
While tracing is in the WASM binary, inferno which I am 99% sure is the source of the bloat is not. It is only packed in the CLI, same for the tracing subscribers which are the other likely source of bloat.

> would be capable of compiling from source.
This assumes that they have control over their environment which people working in banking, medical, etc. sectors often don't have. Additionally once the desktop Typst app is out, most people will likely stick to that and I hope that it will use platform specific binaries rather than relying on WASM but only @laurmaedje can answer that.

Additionally, having the setup to compile Rust is quite a bit more involved (especially on Windows) than installing a binary using a package manager.

**Comment by dccsillag** [comment]
About the statistical validity of hyperfine's output, a few points:

- Arguing in terms of mean and standard deviation implicitly assumes normality of your samples, which is often violated in performance benchmarking. Without that, they carry very little statistical meaning.
- Furthermore, the mean and standard deviation shown by hyperfine are essentially estimators of the parameters of the supposedly underlying normal distribution. However, these estimators are only guaranteed to be close to the real distribution's parameters asymptotically (i.e., as the number of samples grows arbitrarily). Moreover, you'd need to assume iid samples (which is, again, often violated in performance benchmarking). So I don't particularly trust the estimations for a mere 10 samples of a likely non-normally-distributed data generating process.
- Even if we were to assume that the above issues were resolved, subtracting the standard deviation from the mean only once gives you a "confidence interval" of just ~68% significance, which is quite low (subtract it twice to get ~95%).

**Comment by SUPERCILEX** [comment]
> Using cobench

That thing looks sweet! I'll look out for an r/rust announcement. :)

That said, you're using what looks like a dummy document. I'd like this checked on a real doc (I used my homework lol).

> inferno which I am 99% sure is the source of the bloat

I'm not sure. My assumption was that it would come from all the static strings that are generated for each trace macro.

> would be capable of compiling from source.

Ok, I'm convinced by your arguments.

---

How about this?
- Add a `trace` feature flag and gate all tracing + deps on it 
- Disable by default in cargo.
   - This improves rust compile times, the web app, and people building from source.
- In the release CI job, enable the feature so tracing is compiled in.

**Comment by dccsillag** [comment]
> That said, you're using what looks like a dummy document. I'd like this checked on a real doc (I used my homework lol).

Just briefly stepping in -- I was actually the one to run the `cobench` benchmark and send it over to @Dherse; it _is_ a real document (incidentally, also some homework). :smile:

Nevertheless, I think that being able to easily disable tracing at compiletime sounds good, especially for the webapp. That said, I think it should be enabled by default.

**Comment by SUPERCILEX** [comment]
> Nevertheless, I think that being able to easily disable tracing at compiletime sounds good, especially for the webapp. That said, I think it should be enabled by default.

Sweet! And yeah, it'll be a lot easier to fight over the default if it's just the flip of a switch.

**Comment by Dherse** [comment]
> In the release CI job, enable the feature so tracing is compiled in.

It was already discussed on Discord about having additional profiles (e.g with debug symbols) so that's definitely a solution! However, I am wondering, does it really have a negative impact on incremental build speed? I have a powerful computer so I would not have noticed it, but it may well be an issue for lower end hardware.

>  all the static strings

On my machine, a release build yields a 22MB binary (with instrumentation and inferno), a 21 MB binary (with instrumentation but no inferno) and a 21 MB binary (with no instrumentation), showing that inferno looks to be the culprit for bloat, therefore it would not be an issue for the WASM build.

Finally, I will run a full benchmark with 2k samples while I'm sleeping (which I should really be doing rn) to have a full range of test data for execution time impact.

**Comment by SUPERCILEX** [comment]
> have a negative impact on incremental build speed

I was thinking more CI build times since the caching there is not perfect.

**Comment by SUPERCILEX** [comment]
Oops, bumped button

**Comment by SUPERCILEX** [comment]
> showing that inferno looks to be the culprit for bloat, therefore it would not be an issue for the WASM build.

Awesome, that's reassuring.

> Finally, I will run a full benchmark with 2k samples while I'm sleeping

Lol, sounds good. Do you have prod docs? I can dm you my hw on the condition that it's deleted afterwards.

**Comment by Dherse** [comment]
Hey, just commenting with the results of the night-long benchmark (5h30 oof), I have three test documents that we have currently sourced from the community. Note that these tests were run on a PC with fixed clocks and almost no other processes running (outside of the OS essentially).

## `conformal_prediction.typ`
A test document by @dccsillag that is very query heavy and has, so far, been our "workhorse" document when it comes to benchmarking and profiling. Interestingly, it showed what looks to be a normal distribution with few outliers, therefore I will be using the mean and 2 sigma (to keep a 95% confidence interval):

|                      | Without instrumentation (mean +/- 2 * sigma) | With instrumentation (mean +/- 2 * sigma) |
|----------------------|----------------------------------------------|-------------------------------------------|
| Conformal prediction | 4.3928 +/- 0.167 s                           | 4.4058 +/- 0.0520                         |

This first test shows a slight slowdown of better than 0.3% which is well within the confidence interval of both tests, showing little to no performance impact.

## `jeff_numbers.typ`
This is a new addition to our test suit and it is not particularly interesting for native testing where it is essentially instantaneous, but it is quite slow on WASM, unfortunately the WASM harness is not ready yet. ¯\_(ツ)_/¯ It does **not** show a normal distribution at all, instead showing a "truncated" normal distribution with most simple at or close to the minimum (see histogram below). As this test as extremely short execution time, I don't consider it to be very relevant, however, it does show a slight slow down with instrumentation (around 1%), likely due to the extra cost of loading all of those static values. Interestingly, the case with instrumentation shows much lower spread, I cannot explain this at this time.

![jeff_numbers_hist](https://user-images.githubusercontent.com/9665250/233969208-d3f17acf-8d7e-4201-9778-c07c6a2044d7.png)

## `mandelbrot.typ`
This is a test meant to benchmark the performance of the evaluation loop itself, because of this, it has **very heavy** instrumentation since most of the instrumentation is in the evaluation loop. This one does show a more significant slowdown as can be explained by my previous statement. However, it is a **very** unrealistic document as it plots a mandelbrot of quite high resolution in pure typst, a task I would consider typst unsuited for. Again, the distributions are not normal and the case with instrumentation has lower "spread" something that I cannot explain at this time.

![mandelbrot](https://user-images.githubusercontent.com/9665250/233970173-e7557748-0902-48d7-8aa4-519b6eb4040e.png)

## Conclusion

To conclude, it has a performance impact in the evaluation loop, but as demonstrated with the `jeff_numbers` and `conformal_prediction` documents which are more realistic than the `mandelbrot` document, the impact is very small if measurable. Since most of the instrumentation is in the evaluation loop which, for most documents, is a very small part of the total compilation time, I would argue that it's an okay trade off for the rare cases where it matters. At present, the layout stage and the pdf export still take by far the longest part of the compilation process for a typical document and is therefore where optimization should be done first. I am of course open to continuing this discussion, but I hope that these test cases show the real impact of instrumentation and I hope that everyone will agree with me that the benefits (with regards to observability) outway the small performance cost.

If you would like me to compare it with your document/homework, please feel free to DM me your document on Github or on Discord :)

**Comment by SUPERCILEX** [comment]
Alright, I'm basically convinced. I still like the idea of being to compile out instrumentation, but if that's a pain to add then I don't think we need it.

**Comment by Dherse** [comment]
> Alright, I'm basically convinced. I still like the idea of being to compile out instrumentation, but if that's a pain to add then I don't think we need it.

I agree, if nothing but for devs on lower end hardware :) I don't have time to do that right now as I am working on #878 and the surprising performance results of actually comparing different implementations.

**Comment by SUPERCILEX** [comment]
Sounds good! Will open a PR if I have the time.
