### ISSUE TITLE
Utilize tree-sitter for embedded code blocks

### ISSUE THREAD

**Issue by nareha** [typst/typst#967]
### Description

Typst's syntax highlighting could be improved via ![tree-sitter](https://github.com/tree-sitter/tree-sitter). As an example, here is some Haskell code compiled by Typst

<img width="366" alt="image" src="https://user-images.githubusercontent.com/53708656/234119860-5dbcf132-b0cd-481d-ab34-db4815de8ba8.png">

versus code using tree-sitter syntax highlighting in Neovim.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/53708656/234119987-ceca1bca-77f3-46ca-98bb-7d1a50c0ef08.png">

tree-sitter is also used by other projects, such as Github's markdown code block rendering.

### Use Case

It allows for more expressive syntax highlighting.

**Comment by Enter-tainer** [comment]
The language parsers of treesitter are written in C (even C++, in some cases). It is very hard to make them work in rust+wasm environment.

BTW I once build a small tool to transform cpp source code to flowchat using treesitter-cpp.

**Comment by leiserfg** [comment]
Treesitter now supports loading parsers in wasm  so the language barrier should not be a problem any more.

**Comment by Freed-Wu** [comment]
PS: you can use tree-sitter in [LaTeX](https://texrocks.readthedocs.io/en/latest/topics/texcat.md.html) due to tree-sitter's lua binding and LuaTeX's APIs.

<img width="1275" height="1650" alt="Image" src="https://github.com/user-attachments/assets/0af7d487-3a8a-4c19-89d0-b2f34bd46c06" />

Hope typst support tree-sitter, too.
