### ISSUE TITLE
Call functions in dictionary without parentheses

### ISSUE THREAD

**Issue by AliasQli** [typst/typst#976]
### Description

It would be great if functions in a dictionary could be called without parentheses.

Currently, to call a function field using dot syntax, you have to write

```typst
#let dict = (add1: x => x + 1)

#(dict.add1)(5)
```

With this feature you should be able to write

```typst
#dict.add1(5)
```

### Use Case

This feature allows user-defined methods.

For example, some built-in functions have type `(xxx -> content) -> content`, like `style`, `locate`, `layout` and `query`. It would be convenient to pack them up as a monad (something like rust's `Result`), and write

```typst
#locate
  .then(loc => ...)
  .then(...)
  .run()
```

**Comment by s-cerevisiae** [comment]
Imo it will only make the *current* method syntax more inconsistent and misleading (since built-in methods can alter the receiver like operators, they are not actual functions)

**Comment by laurmaedje** [comment]
We've had this discussion before and the problem is that the dictionary's keys share a namespace with the built-in methods on dictionaries. This is problematic because we'd have to give precedence to one of them. If we choose the keys, then the methods suddenly stop working for some dictionaries (which is horrible) and if we choose the methods adding a new method is a breaking change, which is also not good.
